### ISSUE TITLE
Integrate Usage Policy from DejaCode License library. 

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#659] opened 2017-06-26 23:55 UTC
Older, semi-relevant tickets: #214, #280 

It would be nice to have some sort of integration between scancode and a customer's instance of DejaCode. Specifically, we would like the ability to access usage policy from Dejacode and integrate that data into scancode results file.

This process could be done during scan time, or as an external utility that runs on the scancode results file. This utility could also be a summarization feature of sorts, returning the number of licenses found during scanning that violate an org's usage policy and their file-paths.

All thoughts on this issue are welcome, especially from @mjherzog, @DennisClark and @pombredanne.

**Comment by pombredanne** [comment] 2017-06-27 16:42
IMHO this is a clear duplicate of #214 and there is code in the https://github.com/nexB/scancode-toolkit/tree/214-license-policy for this. Let me close this in favor of #214

**Closed by pombredanne** 2017-06-27 16:42 UTC
Labels: integration, license scan
