### ISSUE TITLE
Erroneous agpl-3.0 detection in Wordpress source files

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1902] opened 2020-02-12 20:33 UTC
agpl-3.0 is mistakenly detected in several files in Wordpress v 5.2.3 and above. For example, I have scanned `wordpress/wp-admin/async-upload.php` and it detected agpl-3.0 in the following string:

``` * Server-side file upload handler from wp-plupload or other asynchronous upload methods.```

Below is the full scan of the file:

```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.1.2",
      "options": {
        "input": [
          "/home/jono/Desktop/wordpress/wp-admin/async-upload.php"
        ],
        "--copyright": true,
        "--email": true,
        "--info": true,
        "--json-pp": "-",
        "--license": true,
        "--license-text": true,
        "--package": true,
        "--url": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2020-02-12T202919.143622",
      "end_timestamp": "2020-02-12T202923.321325",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "async-upload.php",
      "type": "file",
      "name": "async-upload.php",
      "base_name": "async-upload",
      "extension": ".php",
      "size": 3672,
      "date": "2019-09-04",
      "sha1": "cece11d9383346eb142d96241c56f6068e4fd630",
      "md5": "f9e165d508dd62dd7a470a4b3b408517",
      "mime_type": "text/x-php",
      "file_type": "PHP script, ASCII text",
      "programming_language": "PHP",
      "is_binary": false,
      "is_text": true,
      "is_archive": false,
      "is_media": false,
      "is_source": true,
      "is_script": true,
      "licenses": [
        {
          "key": "agpl-3.0",
          "score": 80.0,
          "name": "GNU Affero General Public License 3.0",
          "short_name": "AGPL 3.0",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/agpl-3.0.html",
          "text_url": "http://www.fsf.org/licensing/licenses/agpl-3.0.html",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:agpl-3.0",
          "spdx_license_key": "AGPL-3.0-only",
          "spdx_url": "https://spdx.org/licenses/AGPL-3.0-only",
          "start_line": 3,
          "end_line": 3,
          "matched_rule": {
            "identifier": "agpl-3.0_100.RULE",
            "license_expression": "agpl-3.0",
            "licenses": [
              "agpl-3.0"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": true,
            "is_license_tag": false,
            "matcher": "2-aho",
            "rule_length": 1,
            "matched_length": 1,
            "match_coverage": 100.0,
            "rule_relevance": 80.0
          },
          "matched_text": " * Server-side file upload handler from wp-plupload or other asynchronous upload methods."
        }
      ],
      "license_expressions": [
        "agpl-3.0"
      ],
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "emails": [],
      "urls": [],
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": []
    }
  ]
}
```

**Comment by DennisClark** [comment] 2020-02-12 20:53
problem reproduced on scancode.io with the file available from
https://github.com/WordPress/WordPress/archive/5.3.1.tar.gz

Scan results attached.  I have a hunch that it gets sidetracked by the word `plupload` . 

[WordPress-5.3.1.tar.gz_scan.json.zip](https://github.com/nexB/scancode-toolkit/files/4194977/WordPress-5.3.1.tar.gz_scan.json.zip)

**Comment by DennisClark** [comment] 2020-02-12 20:56
the overall license should be gpl-2.0-plus  as stated in 
https://github.com/WordPress/WordPress/blob/5.3.1/license.txt

**Comment by JonoYang** [comment] 2020-02-20 22:43
@DennisClark `plupload` is definitely the problem word. I will create a fix for this.

**Comment by JonoYang** [comment] 2020-02-20 23:04
Interesting. I have created:
`false_positive29.RULE`, which contains:
```
plupload
```

`false_positive29.yml`, which contains:
```
is_false_positive: yes
notes: found in WordPress source files

```

and I am a license rule conflict when I run scancode:

```
$ scancode -il ~/Desktop/plupload.txt --json-pp -
Setup plugins...
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try 'scancode --help' for help on options and arguments.

Error: Invalid value: ERROR: failed to setup plugin: scan:licenses:
Traceback (most recent call last):
  File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 762, in run_scan
    plugin.setup(**requested_options)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/plugin_license.py", line 129, in setup
    get_index(return_value=False)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/cache.py", line 68, in get_index
    _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/cache.py", line 249, in get_cached_index
    idx = LicenseIndex(rules, _spdx_tokens=spdx_tokens)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/index.py", line 244, in __init__
    rules, _legalese=_legalese, _spdx_tokens=_spdx_tokens)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/index.py", line 527, in _add_rules
    raise AssertionError(msg)
AssertionError: Duplicate rules: 
file:///home/jono/nexb/src/scancode-toolkit/src/licensedcode/data/rules/agpl-3.0_100.RULE
file:///home/jono/nexb/src/scancode-toolkit/src/licensedcode/data/rules/false_positive29.RULE
```

@pombredanne Any insights into what's happening?

**Comment by JonoYang** [comment] 2020-02-20 23:35
@pombredanne It appears that the contents of `agpl-3.0_100.RULE` and `false_positive29.RULE` hash to the same value:
 
```
$ scancode -il ~/Desktop/plupload.txt --json-pp -
Setup plugins...
Rule(identifier='agpl-3.0_100.RULE', license_expression='agpl-3.0', minimum_coverage=0.0, only_known_words=False, relevance=80.0, length=1)
b'7\xec\x91\xf3\x9e\xa2\xea\x9b\x132E\xff\x99\xf6\xec\x82'
Rule(identifier='false_positive29.RULE', license_expression=None, minimum_coverage=0.0, only_known_words=False, relevance=100, length=1)
b'7\xec\x91\xf3\x9e\xa2\xea\x9b\x132E\xff\x99\xf6\xec\x82'
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try 'scancode --help' for help on options and arguments.

Error: Invalid value: ERROR: failed to setup plugin: scan:licenses:
Traceback (most recent call last):
  File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 762, in run_scan
    plugin.setup(**requested_options)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/plugin_license.py", line 129, in setup
    get_index(return_value=False)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/cache.py", line 68, in get_index
    _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/cache.py", line 249, in get_cached_index
    idx = LicenseIndex(rules, _spdx_tokens=spdx_tokens)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/index.py", line 244, in __init__
    rules, _legalese=_legalese, _spdx_tokens=_spdx_tokens)
  File "/home/jono/nexb/src/scancode-toolkit/src/licensedcode/index.py", line 530, in _add_rules
    raise AssertionError(msg)
AssertionError: Duplicate rules: 
file:///home/jono/nexb/src/scancode-toolkit/src/licensedcode/data/rules/agpl-3.0_100.RULE
file:///home/jono/nexb/src/scancode-toolkit/src/licensedcode/data/rules/false_positive29.RULE
```

**Comment by pombredanne** [comment] 2020-02-21 08:08
@JonoYang you cannot have duplicate rules... But the rationale for `plupload` to return an AGPL license is straight forward: plupload AGPL-licensed https://www.plupload.com/download/ (or alternatively commercial)

**Comment by pombredanne** [comment] 2020-02-21 08:30
Note that before the [AGPL](https://github.com/moxiecode/plupload/commit/a32eab6fb30e714c0935e2a111f86ffa9ccb0485), this was using a mishmash of GPL and LGPL references or a commercial license nothing quite clear to me https://github.com/moxiecode/plupload/tree/d55ef20c7e9ff352e76afb7fe2317fd649196f3e

> ### Contributing
> 
> We are open to suggestions and code revisions, however there are some rules and limitations that you might want to consider first.
> 
>     Code that you contribute will automatically be licensed under the LGPL, but will not be limited to LGPL.
>     Although all contributors will get the credit for their work, copyright notices will be changed to Moxiecode Systems AB.
>     Third party code will be reviewed, tested and possibly modified before being released.
> 
> These basic rules help us earn a living and ensure that code remains Open Source and compatible with LGPL license. All contributions will be added to the changelog and appear in every release and on the site.
> 
> An easy place to start is to translate Plupload to your language.
> 
> You can read more about how to contribute at: http://www.plupload.com/contributing
> ### License
> 
> Copyright 2013, Moxiecode Systems AB
> Released under GPLv2 License.
> 
> We also provide commercial license.


So in all cases we have a copyleft license in the front end. Some older versions are GPL-licensed and newer versions are using the AGPL-3.0. I would still want to keep `plupload` as a rule that returns AGPL somehow as this is a popular tool.

Alternatively, what we could do instead is check in details https://github.com/moxiecode/plupload/tree/v2.1.9 (what seems to be the latest GPL version) and a recent AGPL version and create a bunch of specific rules (bigger than just `plupload`) so that the AGPL `plupload` would be triggered only in a few cases. I am not sure this can work in this case.

**Comment by pombredanne** [comment] 2021-08-20 08:01
I have really gotten good mileage from that rule with a solo `plupload` word. IMHO we should keep this as is and I am closing this ticket for now!

**Closed by pombredanne** 2021-08-20 08:01 UTC
Labels: bug, license scan
