### ISSUE TITLE
Fail to scan on user home with ~

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1748] opened 2019-10-06 11:28 UTC
### Description
A scan to ~/ fails:
```
$ ./scancode -i ~/misc/licenses/ --json -
Setup plugins...
Collect file inventory...
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try 'scancode --help' for help on options and arguments.

Error: Invalid value: ERROR: failed to collect codebase at: '/home/misc/licenses/'
Traceback (most recent call last):
  File "/scancode-toolkit/src/scancode/cli.py", line 860, in run_scan
    max_in_memory=max_in_memory
  File "/scancode-toolkit/src/scancode/resource.py", line 284, in __init__
    self._populate()
  File "/scancode-toolkit/src/scancode/resource.py", line 443, in _populate
    parent = parent_by_loc.pop(top)
KeyError: '/home/licenses/javascript/rcs
```

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? https://github.com/nexB/scancode-toolkit/tree/2529cd7e2b3f9e41522d657fe26697be142b4645
* What installation method was used to install/run scancode? git clone

**Comment by JonoYang** [comment] 2019-10-07 18:51
@pombredanne Is scancode failing to scan a folder in your home directory? I am unable to reproduce the error.

**Comment by pombredanne** [comment] 2019-10-07 21:02
good catch... this is not the root cause.
The small zip attached fails with:
```
unzip scan.zip
scancode --json-pp - scan
```
[scan.zip](https://github.com/nexB/scancode-toolkit/files/3699426/scan.zip)

**Comment by JonoYang** [comment] 2019-10-07 21:47
@pombredanne Thanks, I am able to reproduce the error with the attached zip.

**Comment by JonoYang** [comment] 2019-10-07 22:12
@pombredanne The issue is with the directory `scan.zip/rcs/`. ScanCode will ignore the `rcs` directory since it's shares the same name as RCS, the version control system.

**Comment by pombredanne** [comment] 2019-10-08 13:43
OK, I think we can now drop ignoring RCS ten... I have not seen RCS directories in ages, and digging in them if we ever meet some real ones is not a problem IMHO.

We still need to avoid this kind of errors too BEFORE removing skipping rcs

**Comment by JonoYang** [comment] 2019-10-17 22:09
We now scan the RCS directory and we properly ignore directories when creating the codebase. Closing.

**Closed by JonoYang** 2019-10-17 22:09 UTC
Labels: bug, core and api

**Comment by adambhere** [comment] 2020-08-24 16:06
I've come across this same problem running scancode 3.0.2 on ubuntu 18.04. The directory named "rcs" was ignored by scancode, but not its contents. It seems to me that it might be a good idea not only to remove "RCS" from the ignored list but also to make checks case sensitive (except on Windows) -- get_matches() in fileste.py changes the case of the item to be ignored to lower and I suggest it shouldn't.

**Comment by pombredanne** [comment] 2020-08-24 16:55
@adambhere Let's create a new ticket for that then. Do you have the same problem using the tip of the develop branh?

**Comment by adambhere** [comment] 2020-08-25 09:50
@pombredanne We have plans to move to it, but the decision is out of my hands.
