### ISSUE TITLE
Timeout for test XML file in Ivy 2.4.0

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#695] opened 2017-07-20 11:35 UTC
This is yet another case like #641 or #694. Scanning [obr.xml](https://git-wip-us.apache.org/repos/asf?p=ant-ivy.git;a=blob;f=test/test-obr/obr.xml;h=36c7b17e5663730e5397caacd7d350d213a73c27;hb=0b9db35ee7a94a719e538b04122b86cb997f3a17) from Apache Ivy 2.4.0 times out after 120s (also tried with 600s):

    {
       "scancode_notice":"Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
       "scancode_version":"2.0.1.post76.865d2487",
       "scancode_options":{
          "--copyright":true,
          "--license":true,
          "--package":true,
          "--license-score":0,
          "--ignore":[

          ],
          "--format":"json"
       },
       "files_count":1,
       "files":[
          {
             "path":"test-obr/obr.xml",
             "scan_errors":[
                "ERROR: Processing interrupted: timeout after 120 seconds."
             ]
          }
       ]
    }

@pombredanne let me know if you don't like me to report these individual cases. I'm not sure how generically they can be solved, and I don't believe hard-coding individual work-arounds per file is feasible.

**Comment by pombredanne** [comment] 2017-07-20 12:01
@sschuberth Thanks . I love these reports on these individual cases and this way I can evolve the code to be more generic. I am not hardcoding per-file workarounds at all ;)

**Comment by pombredanne** [comment] 2017-07-20 13:04
The obr.xml file is a 74MB xml file with 266K+ lines 
Scanning gives with this with develop head:
- copyright: 59s. I think is acceptable
- license: this is the culprit. This case is interesting. There 1232 instances of a link to the Apache-1.1 license (e.g. this [rule](https://github.com/nexB/scancode-toolkit/blob/865d24874fa39acaca40e690ea111efb5edaa8ff/src/licensedcode/data/rules/apache-1.1_36.RULE)) which are valid license statements IMHO. They are found very quickly, then the detection goes in a deeper round of finding better approximate matches around this small match... and this is the problem because there are no better matches... but its trying hard nonetheless.
This is likely something I can make better and avoid diving deeper when certain common conditions are met


Now the whole idea of a timeout has been to guard against wasting too much time with such large files.
- An alternative could be to filter out, ignore some files based on some rules.
- Another approach could be to limit the number of "clues" returned in any given file by a maximum option (this is needed for urls and emails for instance see #384 ) and this could be extended to any file... For instance stop any given scan if there are more than X number of findings found and add a warning in these cases that the

**Comment by sschuberth** [comment] 2017-07-20 15:15
> For instance stop any given scan if there are more than X number of findings found and add a warning in these cases

I believe that's the most viable option: Report whatever results are available until the timeout occurred. Knowing something about the file is better than knowing nothing, esp. since most license text are headers in the beginning of files.

**Comment by pombredanne** [comment] 2017-07-20 21:16
In general and in the case of license this is not entirely trivial... as the license matches are not streamed ... but need merging and filtering at the end.

Some ideas:
- run the detection in two steps: one that only looks at the start of a file, say as big as the biggest license text plus a one KB then a second step... return the first step only if the second step timedout
- bake the timeout handling inside license detection and use this as a not to exceed time. Before the time limit is reached, stop finding further matches, and return the results available so far with a warning message.

**Comment by sschuberth** [comment] 2017-07-21 06:31
Yes, your second suggestion basically was what I was thinking about.

**Comment by pombredanne** [comment] 2017-09-27 18:23
So beside not scanning inside binary files (e.g. #712 ), I came to the conclusion that the only sane way to avoid going into the rabbit holes that large files can be is to avoid scanning them entirely.
So rather than having a complicated way to get whatever was scanned until a timeout which is hard, I will add instead a CLI option with a default to only scan up XXX MB of any file where XXX default would in the range of a few MB. May be something like `--max-file-size 1MB` and the logic would be to only scan the first MB of any file that are bigger than that.

**Comment by pombredanne** [comment] 2017-09-27 18:25
It is otherwise really hard to state that a file may be containing a log list of licenses like here. Besides this we could also create pre-scan filtering plugins that can make other specific decisions to skip scanning certain files based on custom heuristics

**Comment by sschuberth** [comment] 2017-09-28 10:14
> any file where XXX default would in the range of a few MB

I believe the default should be "unlimited" to not break with current behavior. Also, it should be a conscious decision to potentially omit input data. Other than that, I like the idea of introducing a `--max-file-size` option.

> we could also create pre-scan filtering plugins that can make other specific decisions to skip scanning certain files based on custom heuristics

That sounds like a really good idea!

**Comment by pombredanne** [comment] 2018-03-21 21:53
I have been playing with another approach which is to split large files in smaller files (using `split`). This works suprisingly well. I will digging in this direction a nit more.

**Comment by sschuberth** [comment] 2018-03-22 07:54
Out of curiosity, how do you ensure to not split in the middle of potential findings, which would then not be found? Do you use some kind of overlap?

**Comment by armijnhemel** [comment] 2018-03-22 09:40
I think it would be better to first verify what kind of file you are trying to scan before determining a strategy as it might be different per file type. For example, for a graphics file you might only want to look at EXIF or XMP information, and skip everything else.

**Comment by pombredanne** [comment] 2018-03-22 20:17
@sschuberth re:
> Out of curiosity, how do you ensure to not split in the middle of potential findings, which would then not be found? Do you use some kind of overlap?

The worst case that could happen is if a fixed length split happens smack in the middle of a license text. In this case this would yield two possibly incorrect and partial license detection. 

A way to handle this is after the detection: check the matches in file chunks and if they happen close to the end and close to the start of two contiguous chunks, redo a detection on these chunks merged as one chunk. 

Or do it before the fact if there are license-related tokens towards the end and the start of two contiguous chunks, then treat these tow chunks as one.

With or without these we would still get a detection in anycase.

**Comment by pombredanne** [comment] 2018-03-22 20:37
@armijnhemel re:

> I think it would be better to first verify what kind of file you are trying to scan before determining a strategy as it might be different per file type. For example, for a graphics file you might only want to look at EXIF or XMP information, and skip everything else.

Entirely agree to this: the way text is extracted and considered for detection is already mostly type-specific (but always needs to be improved and refined). 

Here the issue is with very large text files; and in some cases as with `.js.map` map/debug symbol files these may be both very large text files that are 1. structured JSON and 2. may contain a lot of source code with copyrights/licenses: this information may not be part otherwise of the other package files.

This is weird thing that happens with some popular node.js/npm packages where the packages contains minified JS combining many libraries of various origins and licenses in a single minified file AND there a .js.map file that contains the original, pre-minification source code.


To get a practical understanding of the issue, see https://github.com/ant-design/ant-design
The npm package https://registry.npmjs.org/antd/-/antd-3.3.1.tgz contains multimegabyte .map files in `dist/` that in turn contain all the sources of all the third-party they minify .
This package also contains the minified and un-minified versions.... In the end there are many copies of code in various stages. I would like to handles these nicely and at the minimum never choke on these larger text files if possible. Ideally we would want to handle these duplications more intelligently too in the future.
For all practical purposes, a minified JS file is mostly like a compiled binary and the .js.map file is like debug symbols with the added twist that it can also contain the whole source code of the binaries.

**Comment by pombredanne** [comment] 2019-06-03 09:14
In the PR #1552  the obr.xml scans correct (and reports the 1241 instances of Apache 2.0 notices or tags in that file). The feature is the introduction of a deadline and is an implementation of this idea https://github.com/nexB/scancode-toolkit/issues/695#issuecomment-316832638:

> bake the timeout handling inside license detection and use this as a not to exceed time. Before the time limit is reached, stop finding further matches, and return the results available so far with a warning message. Take the same approach for copyright detection

The timeout is converted to a deadline time (a not to exceed time) and each scanner receives it as an argument and can decide to do something with it or not.

Both copyright and license use this deadline to eventually stop processing and return matches found so far after the basic detection steps.

**Comment by pombredanne** [comment] 2019-10-16 14:08
This is fixed and merged in develop! Thanks

**Closed by pombredanne** 2019-10-16 14:08 UTC
Labels: fixed pending review, license scan, timeout
