### ISSUE TITLE
Non ASCII characters in path cause problems

### ISSUE THREAD

**Issue by camillem** [nexB/scancode-toolkit#867] opened 2017-12-11 18:47 UTC
Hi,
It seems that Ubuntu 17.10 is not currently supported.
Any plans to add it ?
Thanks, 
Camille

**Comment by pombredanne** [comment] 2017-12-11 18:53
@camillem Always at the vanguard! Can you tell me what problems you have encountered? And error message you got? Normally it should run on it OK, but I never tried it.

**Comment by camillem** [comment] 2017-12-11 18:58
@pombredanne I'm prolly missing something obvious :-/

> scancode-toolkit-2.2.1$ ./scancode --help
./scancode: ligne 114: scancode-toolkit-2.2.1/bin/scancode: Aucun fichier ou dossier de ce type

**Comment by pombredanne** [comment] 2017-12-11 19:01
@camillem did you take the release archive for 2.2.1? and do you have Python 2.7 available on your distro?

**Comment by camillem** [comment] 2017-12-11 19:11
> the release archive for 2.2.1

yes

> do you have Python 2.7 available

Looks like it:
```
scancode-toolkit-2.2.1$ python --version
Python 2.7.14
```

**Comment by pombredanne** [comment] 2017-12-11 19:24
hum... Let me try to debug this is a VM or container

**Comment by camillem** [comment] 2017-12-11 19:40
Ooops, I think I got it. I tried on 16.04 and had the same problem, so...
It happens when you have an non ASCII character in your path. Like ~/Téléchargements/...

**Comment by camillem** [comment] 2017-12-11 19:42
So, I should may be rename the issue to Python 3 support ;-) ?

**Comment by pombredanne** [comment] 2017-12-11 19:47
@camillem `non ASCII character in your path. Like ~/Téléchargements/...` is not a Python3 issue, but a plain bug. Let me fix this!

**Comment by camillem** [comment] 2017-12-11 19:50
@pombredanne Thanks. Let me know if I can help testing.

**Comment by pombredanne** [comment] 2017-12-11 20:22
The root cause is this bug https://github.com/pypa/virtualenv/issues/457 and indeed the problem does not happen with virtualenv on Python 3  
At this stage and until we completed the migration to Python there is no way out but to use a path that contains only ASCII charactersl

**Comment by pombredanne** [comment] 2017-12-11 20:28
I added a FAQ entry and details in the comprehensive installation doc.
I will keep this open until fixed.
@camillem Thank you ++ for this report and sorry for the inconvenience!

**Comment by pombredanne** [comment] 2019-02-18 17:28
https://github.com/pypa/virtualenv/issues/457 has been closed :| ... anyway this should go away with Python3 and this will be part of the port things to review

**Comment by camillem** [comment] 2019-02-18 17:34
Thanks for following up on this. And, yep, Python 3 ftw :-)

**Comment by pombredanne** [comment] 2020-01-02 17:52
@camillem and at last https://github.com/pypa/virtualenv/issues/457 has been fixed upstream by @gaborbernat so we should have this land in scancode pretty soon!

**Comment by camillem** [comment] 2020-01-02 17:53
And that's brilliant news to start the new year with :-) Thanks !

**Comment by gaborbernat** [comment] 2020-01-02 18:15
We'll release it via 20.0.0 (see https://github.com/pypa/virtualenv/milestone/7), so look out for that, my hope is by end of month.

**Comment by pombredanne** [comment] 2020-01-02 18:29
@gaborbernat thank you ++
You rock and virtualenv is a life saver!

**Comment by pombredanne** [comment] 2021-09-24 12:10
This has long been merged and fixed... closing
Thanks!

**Closed by pombredanne** 2021-09-24 12:10 UTC
Labels: bug, installation and packaging, Python3
