### ISSUE TITLE
something wrong with output_html.py

### ISSUE THREAD

**Issue by arthur657834** [nexB/scancode-toolkit#1292] opened 2018-11-21 08:09 UTC
run command:  /opt/scancode-toolkit/scancode --license --copyright --package --html=scancode-2018-11-21.html --verbose ./test-master

and i get this:

16:04:13 Scanning done.
16:04:13 Some files failed to scan properly:
16:04:13 ERROR: failed to run output plugin: html:
16:04:13 Traceback (most recent call last):
16:04:13   File "/opt/scancode-toolkit/src/scancode/cli.py", line 864, in run_codebase_plugins
16:04:13     plugin.process_codebase(codebase, **kwargs)
16:04:13   File "/opt/scancode-toolkit/src/formattedcode/output_html.py", line 86, in process_codebase
16:04:13     write_templated(html, results, version, template_or_format='html')
16:04:13   File "/opt/scancode-toolkit/src/formattedcode/output_html.py", line 165, in write_templated
16:04:13     raise Exception(msg)
16:04:13 Exception: ERROR: Failed to write output for: u'\n            <tr>\n              <td>RD-front-master-extend/app/static/imgs/\u6570\u636e.svg</td>\n              <td>file</td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n              <td></td>\n            </tr>\n        '
16:04:13 Traceback (most recent call last):
16:04:13   File "/opt/scancode-toolkit/src/formattedcode/output_html.py", line 160, in write_templated
16:04:13     output_file.write(template_chunk)
16:04:13 UnicodeEncodeError: 'ascii' codec can't encode characters in position 75-76: ordinal not in range(128)

**Comment by pombredanne** [comment] 2018-11-22 10:05
@arthur657834 Thanks for the report and sorry for that. This looks like the file and directory names you scanned where using special character encodings... and  that not should be a problem.
I was able to reproduce this this way:
```
$ mkdir han
$ touch  han/据.svg
$ $ scancode -i --html h.html han/
Setup plugins...
Collect file inventory...
Scan files for: info with 1 process(es)...
[####################] 1              
ERROR: failed to run output plugin: html:
Traceback (most recent call last):
  File "/tmp/scancode-toolkit/src/scancode/cli.py", line 864, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/tmp/scancode-toolkit/src/formattedcode/output_html.py", line 86, in process_codebase
    write_templated(html, results, version, template_or_format='html')
  File "/tmp/scancode-toolkit/src/formattedcode/output_html.py", line 165, in write_templated
    raise Exception(msg)
Exception: ERROR: Failed to write output for: u'\n            <tr>\n              <td>han/\u636e.svg</td>\n              <td>file</td>\n              <td>\u636e.svg</td>\n              <td>.svg</td>\n              <td>2018-11-22</td>\n              <td>0</td>\n              <td>None</td>\n              <td>None</td>\n              <td></td>\n              <td>inode/x-empty</td>\n              <td>empty</td>\n              <td>None</td>\n              <td>False</td>\n              <td>True</td>\n              <td>False</td>\n              <td>False</td>\n              <td>False</td>\n              <td>False</td>\n            </tr>\n        '
Traceback (most recent call last):
  File "/tmp/scancode-toolkit/src/formattedcode/output_html.py", line 160, in write_templated
    output_file.write(template_chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u636e' in position 40: ordinal not in range(128)


Scanning done.
Some files failed to scan properly:
ERROR: failed to run output plugin: html:
Traceback (most recent call last):
  File "/tmp/scancode-toolkit/src/scancode/cli.py", line 864, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/tmp/scancode-toolkit/src/formattedcode/output_html.py", line 86, in process_codebase
    write_templated(html, results, version, template_or_format='html')
  File "/tmp/scancode-toolkit/src/formattedcode/output_html.py", line 165, in write_templated
    raise Exception(msg)
Exception: ERROR: Failed to write output for: u'\n            <tr>\n              <td>han/\u636e.svg</td>\n              <td>file</td>\n              <td>\u636e.svg</td>\n              <td>.svg</td>\n              <td>2018-11-22</td>\n              <td>0</td>\n              <td>None</td>\n              <td>None</td>\n              <td></td>\n              <td>inode/x-empty</td>\n              <td>empty</td>\n              <td>None</td>\n              <td>False</td>\n              <td>True</td>\n              <td>False</td>\n              <td>False</td>\n              <td>False</td>\n              <td>False</td>\n            </tr>\n        '
Traceback (most recent call last):
  File "/tmp/scancode-toolkit/src/formattedcode/output_html.py", line 160, in write_templated
    output_file.write(template_chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u636e' in position 40: ordinal not in range(128)


Summary:        info with 1 process(es)
Errors count:   1
Scan Speed:     9.41 files/sec. 
Initial counts: 2 resource(s): 1 file(s) and 1 directorie(s) 
Final counts:   2 resource(s): 1 file(s) and 1 directorie(s) 
Timings:
  scan_start: 2018-11-22T100350.641961
  scan_end:   2018-11-22T100350.753523
  scan: 0.11s
  total: 0.14s
Removing temporary files...done.
```

**Comment by pombredanne** [comment] 2018-11-28 21:11
This has been fixed and merged in develop. Thanks!

**Closed by pombredanne** 2018-11-28 21:11 UTC
Labels: GUI and outputs, Priority: high, bug, core and api, must have
