### ISSUE TITLE
Error in `summary-by-facet` Plugin

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1759] opened 2019-10-15 01:43 UTC
### Description

Running the following command:
``./scancode -clpieu --json-pp facet_summary.json samples --summary --facet dev=*.java --summary-by-facet``

Generates the following Error
```
ERROR: failed to run post-scan plugin: summary-by-facet:
Traceback (most recent call last):
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/scancode/cli.py", line 1033, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 410, in process_codebase
    summarize_codebase_by_facet(codebase, **kwargs)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 452, in summarize_codebase_by_facet
    [(key, sorted_counter(counter)) for key, counter in summary_counters])
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 448, in <genexpr>
    for key, values in summarizable_values_by_key.items()
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 305, in summarize_values
    return value_summarizers_by_attr[attribute](values)
KeyError: u'packages'

Scanning done.
Some files failed to scan properly:
ERROR: failed to run post-scan plugin: summary-by-facet:
Traceback (most recent call last):
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/scancode/cli.py", line 1033, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 410, in process_codebase
    summarize_codebase_by_facet(codebase, **kwargs)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 452, in summarize_codebase_by_facet
    [(key, sorted_counter(counter)) for key, counter in summary_counters])
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 448, in <genexpr>
    for key, values in summarizable_values_by_key.items()
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/summarycode/summarizer.py", line 305, in summarize_values
    return value_summarizers_by_attr[attribute](values)
KeyError: u'packages'

```
### System configuration
* What OS are you running on? Ubuntu 16.04 LTS
* What version of scancode-toolkit was used to generate the scan file? v3.1.1
* What installation method was used to install/run scancode? [source download]

**Comment by AyanSinhaMahapatra** [comment] 2019-10-15 01:44
[Update] 
Running `` ./scancode -clieu`` instead of `` ./scancode -clpieu`` doesn't give error.

**Comment by pombredanne** [comment] 2019-10-15 10:24
thank you: good catch!
side note, always quote patterns in a facet to avoid shell glob expansion e.g. use `dev="*.java"` and not `dev=*.java`

**Comment by AyanSinhaMahapatra** [comment] 2019-10-15 19:15
Noted. I will update docs accordingly.

**Comment by Iamshankhadeep** [comment] 2019-10-23 03:35
and can I work on this too?

**Comment by pombredanne** [comment] 2019-10-23 16:37
@Iamshankhadeep let's do one at a time if that works for you!

**Comment by inishchith** [comment] 2019-12-13 05:15
@pombredanne Please let me know if I can work on this.

Thanks!

**Comment by pombredanne** [comment] 2019-12-13 11:56
@inishchith please go for it: thanks! You may need to sync up with @JonoYang that is working in the same area too

**Comment by inishchith** [comment] 2019-12-13 15:19
@pombredanne @AyanSinhaMahapatra Do we have an implementation of package summarizer or is it being worked on?

**Comment by inishchith** [comment] 2019-12-13 18:57
@JonoYang Any pointers on what work is done until now?
I could reproduce the error, but I'm finding it difficult to understand reason for the `KeyError`

**Comment by JonoYang** [comment] 2019-12-16 18:24
@inishchith If you look in the error message, there is a filename and line number where the function of what is being called resides in. With this error, the problem is in line 305 of `scancode-toolkit-3.1.1/src/summarycode/summarizer.py`. The key error is occurring because we are not handling packages at all.

https://github.com/nexB/scancode-toolkit/blob/develop/src/summarycode/summarizer.py#L290

**Comment by inishchith** [comment] 2019-12-17 18:26
@JonoYang Thanks for the response. 

Yes, I get that. 
The part which I didn't get ( because I have just started exploring the tool ) is what should be the result format for the package summary by facet? (an example would really help)

I've currently added a method ( which returns a counter object  like: [summarize_licenses](https://github.com/nexB/scancode-toolkit/blob/develop/src/summarycode/summarizer.py#L241) ) which clears the error. I need an example result to know for sure what is expected. 😅 

Thanks!

**Comment by JonoYang** [comment] 2019-12-18 00:33
@inishchith I think it would make sense to make something like summarize_licenses (as you pointed to) that returns a mapping of package PURL and the number of instances of that package, i.e `{package_purl: count of occurences}`

**Comment by inishchith** [comment] 2019-12-18 05:57
@JonoYang Don't you think the logic of returning the mapping of package PURL and the number of instances of that package should be a part of `package_summarizer` method, just the like the `license_summarizer`? ( returning something like: `[ {"value": "<purl>", "count": } .. ]` )

The current version of `package_summarizer` seems to return a whole lot of information.
Please do let me know in case I missed something out.

Thanks!

**Comment by inishchith** [comment] 2019-12-19 09:19
@AyanSinhaMahapatra I could reproduce this issue on the `v3.1.1 release` and solved it (ref. above). But when I clone this repository in order to suggest a fix. 
- **`Error Log`**
```sh
 Nishchith@inishchith  ~/GitHub/scancode-toolkit   develop  ./scancode -clpieu --json-pp facet_summary_test.json ../spdx-license-diff --summary --facet dev="*.js" --summary-by-facet
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages, emails, urls with 1 process(es)...
[####################] 40                                        
ERROR: failed to run post-scan plugin: summary-by-facet:
Traceback (most recent call last):
  File "/Users/Nishchith/GitHub/scancode-toolkit/src/scancode/cli.py", line 1044, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/Nishchith/GitHub/scancode-toolkit/src/summarycode/summarizer.py", line 410, in process_codebase
    if TRACE_LIGHT: logger_debug('ScanByFacetSummary:process_codebase')
  File "/Users/Nishchith/GitHub/scancode-toolkit/src/summarycode/summarizer.py", line 442, in summarize_codebase_by_facet
    # each summary is a mapping with value/count: we transform back to discrete values
KeyError: u'value'

Scanning done.
Some files failed to scan properly:
ERROR: failed to run post-scan plugin: summary-by-facet:
Traceback (most recent call last):
  File "/Users/Nishchith/GitHub/scancode-toolkit/src/scancode/cli.py", line 1044, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/Nishchith/GitHub/scancode-toolkit/src/summarycode/summarizer.py", line 410, in process_codebase
    if TRACE_LIGHT: logger_debug('ScanByFacetSummary:process_codebase')
  File "/Users/Nishchith/GitHub/scancode-toolkit/src/summarycode/summarizer.py", line 442, in summarize_codebase_by_facet
    # each summary is a mapping with value/count: we transform back to discrete values
KeyError: u'value'
```
Knowing more on what aspects of the scan have been changed in the due course would help me understand the problem.

Please do have a look.
Thanks!

/cc @pombredanne @JonoYang

**Comment by pombredanne** [comment] 2021-09-24 11:39
This is now merged and fxied.

**Closed by pombredanne** 2021-09-24 11:39 UTC
Labels: bug, good first issue, summaries
