### ISSUE TITLE
scancode fails to start by complaining missing Python packages and  "......bin/scancode: No such file or directory"

### ISSUE THREAD

**Issue by george-kuanli-peng** [nexB/scancode-toolkit#2329] opened 2020-11-19 08:26 UTC
### Description

scancode, extracted from GitHub releases, fails to start by complaining missing Python packages and  "......bin/scancode: No such file or directory"

### How To Reproduce

1. Download a scancode tar.bz2 archive from GitHub release assets.
1. Extract `scancode-toolkit-3.x.x.tar.bz2`.
1. Enter the extracted directory and create a Python3 virtual environment workspace by `python3 -m venv venv`
1. Activate Python3 virtual environment by `. ./venv/bin/activate`.
1. Initialize scancode by `./scancode --help`.

In the last step, I got the console messages something like:

```
(venv) user@user-virtualbox:~/tools/scancode-toolkit-3.1.1$ ./scancode --help
* Configuring ScanCode for first use...
ERROR: Could not find a version that satisfies the requirement future>=0.16.0 (from scancode-toolkit==3.1.1->-r /home/user/tools/scancode-toolkit-3.1.1/etc/conf/requirements_base.txt (line 10)) (from versions: none)                
ERROR: No matching distribution found for future>=0.16.0 (from scancode-toolkit==3.1.1->-r /home/user/tools/scancode-toolkit-3.1.1/etc/conf/requirements_base.txt (line 10))                                                           
Traceback (most recent call last):
  File "/home/user/tools/scancode-toolkit-3.1.1/etc/configure.py", line 573, in <module>
    install_3pp(configs, root_dir, thirdparty_dirs, quiet=quiet)
  File "/home/user/tools/scancode-toolkit-3.1.1/etc/configure.py", line 284, in install_3pp
    run_pip(requirements, root_dir, tpp_dirs, quiet)
  File "/home/user/tools/scancode-toolkit-3.1.1/etc/configure.py", line 310, in run_pip
    call(pcmd, root_dir)
  File "/home/user/tools/scancode-toolkit-3.1.1/etc/configure.py", line 137, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/home/user/tools/scancode-toolkit-3.1.1/bin/pip" install --upgrade --no-index --no-cache-dir --find-links="/home/user/tools/scancode-toolkit-3.1.1/thirdparty" -qq --requirement "/home/user/tools/scancode-toolkit-3.1.1/etc/conf/requirements_base.txt"' returned non-zero exit status 1.
./scancode: line 114: /home/user/tools/scancode-toolkit-3.1.1/bin/scancode: No such file or directory
```

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Ubuntu 20.04.
* What version of scancode-toolkit was used to generate the scan file? [Release candidate 2 for 3.1.x](https://github.com/nexB/scancode-toolkit/releases/tag/v3.1.1) and [v3.2.x release](https://github.com/nexB/scancode-toolkit/releases/tag/v3.2.3).
* What installation method was used to install/run scancode? installation as an application (Download a release archive, extract and run).

**Comment by george-kuanli-peng** [comment] 2020-11-19 08:56
I am using Python 3.8, installed by default on Ubuntu 20.04. Would that be the main problem?

Installing by `pip install scancode-toolkit` also failed. (some "failed building wheel" errors)

**Comment by pombredanne** [comment] 2020-11-19 14:51
@george-kuanli-peng Soryy for the issue!
Can you try the latest release? 3.1.1 is a very old one.
Please try again with 3.2.3 

Also if you are using the full release tarball, use `./scancode -h` directly... it will create its own virtualenv and install all its bundled dependencies on first use. BUT at this stage we are not yet full set on Python 3.8... you would need Python 3.6 in the short term

**Comment by pombredanne** [comment] 2020-11-19 15:04
> Installing by pip install scancode-toolkit also failed. (some "failed building wheel" errors)

Can you paste your errors here?

**Comment by george-kuanli-peng** [comment] 2020-11-20 05:29
Hi @pombredanne , thanks for your quick reply.

I had tried the steps in Issue description without luck for both [Release candidate 2 for 3.1.x](https://github.com/nexB/scancode-toolkit/releases/tag/v3.1.1) and [v3.2.x release](https://github.com/nexB/scancode-toolkit/releases/tag/v3.2.3).

I am not sure where to download the full release tarball in the release page. When I run `./scancode -h` within the extracted directory from scancode-toolkit-3.2.3.tar.bz2 (this step requires installation of python-is-python3 on Ubuntu 20.04, though), I got these console messages:

```
user@user-virtualbox:~/tools/scancode-toolkit-3.2.3$ ./scancode -h
* Configuring ScanCode for first use...
ERROR: Could not find a version that satisfies the requirement future>=0.16.0 (from scancode-toolkit==3.2.3->-r /home/user/tools/scancode-toolkit-3.2.3/etc/conf/requirements_base.txt (line 1)) (from versions: none)                                                                                                                    
ERROR: No matching distribution found for future>=0.16.0 (from scancode-toolkit==3.2.3->-r /home/user/tools/scancode-toolkit-3.2.3/etc/conf/requirements_base.txt (line 1))                                                                                                                                                               
Traceback (most recent call last):
  File "/home/user/tools/scancode-toolkit-3.2.3/etc/configure.py", line 562, in <module>
    install_3pp(configs, root_dir, thirdparty_dirs, quiet=quiet)
  File "/home/user/tools/scancode-toolkit-3.2.3/etc/configure.py", line 286, in install_3pp
    run_pip(requirements, root_dir, tpp_dirs, quiet)
  File "/home/user/tools/scancode-toolkit-3.2.3/etc/configure.py", line 312, in run_pip
    call(pcmd, root_dir)
  File "/home/user/tools/scancode-toolkit-3.2.3/etc/configure.py", line 158, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/home/user/tools/scancode-toolkit-3.2.3/bin/pip" install --upgrade --no-index --no-cache-dir --find-links="/home/user/tools/scancode-toolkit-3.2.3/thirdparty" -qq --requirement "/home/user/tools/scancode-toolkit-3.2.3/etc/conf/requirements_base.txt"' returned non-zero exit status 1.
./scancode: line 114: /home/user/tools/scancode-toolkit-3.2.3/bin/scancode: No such file or directory
```

Note in the last line, "bin/scancode" is still not found.

**Comment by bnowacky** [comment] 2021-02-08 14:31
I'm getting the same errors with pythons 3.8, running on Mac. I can get SC 3.2.3 to run successfully on older releases of pythons (2.x, but nothing 3.x), so it seems it's at least a python version issues in 3.2.3

**Comment by bnowacky** [comment] 2021-02-08 16:39
actually fixed this error by copying packages from my main python site_packages directory to the /lib/python3.8/sitepackages directory in the Scancode-toolkit directory I downloaded. There were a few specifically, futures, unicodecsv and pyahocorasick.  pluggy, commoncode (specifically 20.10.20, you have to install --force) 

Once you manually do this, you can run ./scancode -h and installs successfully. Note, I did not try this with pip install, just cloning repo.

**Comment by pombredanne** [comment] 2021-02-08 17:07
@bnowacky I am working on a new release that should hopefully fix all this. And the latest develop branch in git should be work fine too

**Comment by bnowacky** [comment] 2021-02-08 17:32
Thanks @pombredanne , just trying to get some additional clarity on the issue and a workaround I found in case it helped identify the issue. Appreciate the help on a fix !

**Comment by pombredanne** [comment] 2021-02-13 10:44
@bnowacky ping here (also did on https://github.com/nexB/scancode-toolkit/issues/2391 ) as I trying to fix this

**Comment by pombredanne** [comment] 2023-01-04 16:58
I am not able to reproduce this with the latest versions.... closing!

**Closed as completed by pombredanne** 2023-01-04 16:58 UTC
Labels: bug
