### ISSUE TITLE
.wmz files not extracted

### ISSUE THREAD

**Issue by bobgob** [nexB/scancode-toolkit#155] opened 2015-12-14 23:55 UTC
Tested in scancode-toolkit-1.4.3.  .wmz files are not extracted.  A .wmz is:

```WMZ is a file extension for a skin file format in/for/used by Windows Media Player. A WMZ file is basically a zipped WMF file in XML. The zipped file contains JavaScript code and images to change the appearance of the Windows Media Player (WMP) user interface (UI).```

so it could contain interesting (license/copyright/author) data.

**Comment by pombredanne** [comment] 2015-12-15 16:55
@bobgob Thanks for the report. I committed a test but I could not reproduce this. Do you have a sample file that had the problem?

**Comment by bobgob** [comment] 2015-12-15 17:44
I should have mentioned this was on Ubuntu 12.04.4.  GitHub won't allow me to attach a .wmz to this issue and it isn't accepting the .zip file I created from it.  So I'll email it to you.

**Closed** 2015-12-15 18:31 UTC
Labels: archive extraction, bug, minor

**Comment by pombredanne** [comment] 2015-12-15 18:32
@bobgob Thanks! I added this file as a test and fixed it. The wrong archive handler was selected (a tar.gz handler) instead of a gzip handler. That file is in fact a plain gzip file.

**Comment by pombredanne** [comment] 2015-12-15 18:33
@bobgob FWIW the fact that it was on Ubuntu should not have an impact in most cases as this is the same code that runs on Mac, Windows and Linux
