### ISSUE TITLE
Some files failed to scan properly errors

### ISSUE THREAD

**Issue by geneh** [nexB/scancode-toolkit#1674] opened 2019-08-07 18:48 UTC
### Description
"Some files failed to scan properly" errors from clearlydefined crawler:
`/opt/scancode-toolkit-3.0.2/scancode --copyright --license --info --license-text --is-license-text --package --license-diag --strip-root --email --url --license-clarity-score --classify --generated --summary --summary-key-files --timeout 1000 -n 2 --json-pp /tmp/cd-fuyuU8 /tmp/cd-YsiJvd`

### System configuration
* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 3.0.2
* What installation method was used to install/run scancode? download

### Errors
component@cd:/pypi/pypi/-/youtube-dl/2014.09.14.3
```
Some files failed to scan properly:
Path: youtube_dl/extractor/dbtv.py
```

component@cd:/nuget/nuget/-/linq2db.t4models/2.8.0
```
Some files failed to scan properly:
Path: Data/Northwind.MS.sqlite
Path: Data/Northwind.sqlite
```

component@cd:/gem/rubygems/-/fastlane/2.127.2
```
Some files failed to scan properly:
Path: fastlane_core/lib/fastlane_core/ui/github_issue_inspector_reporter.rb
Path: spaceship/spec/tunes/fixtures/iap_pricing_tiers.json
```

component@cd:/gem/rubygems/-/puppet/6.7.2
```
Some files failed to scan properly:
Path: locales/ja/puppet.po
```

component@cd:/maven/mavencentral/com.github.binarywang/weixin-java-miniapp/3.4.8.B
```
Some files failed to scan properly:
Path: cn/binarywang/wx/miniapp/api/WxMaMediaService.java
Path: cn/binarywang/wx/miniapp/bean/WxMaUniformMessage.java
```

component@cd:/npm/npmjs/@vue/cli-plugin-unit-mocha/4.0.0-beta.0
```
Some files failed to scan properly:
Path: docs/ru/config/README.md
Path: docs/zh/config/README.md
Path: docs/zh/guide/build-targets.md
```

component@cd:/npm/npmjs/@material-ui/utils/4.3.0
```
Some files failed to scan properly:
Path: docs/src/pages/components/use-media-query/use-media-query-zh.md
```

component@cd:/pypi/pypi/-/django-simpleui/2.6
```
Some files failed to scan properly:
Path: django-simpleui-2.6/simpleui/templates/admin/login.html
```

component@cd:/npm/npmjs/-/cytoscape/3.7.5
```
Some files failed to scan properly:
Path: documentation/md/style.md
```

component@cd:/gem/rubygems/-/pdf-reader/2.2.1
```
Some files failed to scan properly:
Path: spec/data/broken_string.pdf
Path: spec/data/encrypted_version1_revision2_128bit_rc4_no_doc_id.pdf
Path: spec/data/kids-as-direct-objects.pdf
Path: spec/data/mediabox_missing.pdf
Path: spec/data/screwey_xref_offsets.pdf
Path: spec/data/invalid/linearized_bad_xref_offset.pdf
Path: spec/data/invalid/page_reference_is_not_a_dict.pdf
Path: spec/data/invalid/trailer_root_is_not_a_dict.pdf
```

component@cd:/gem/rubygems/-/cocoapods-core/1.7.5
```
Some files failed to scan properly:
Path: lib/cocoapods/user_interface/inspector_reporter.rb
```

component@cd:/npm/npmjs/-/eslint-plugin-taro/1.3.10
```
Some files failed to scan properly:
Path: docs/debug.md
```

**Comment by pombredanne** [comment] 2019-08-07 18:50
@geneh Thank you ++ for this report. Let me make sure we get this before the next major release which is planned for anytime now!

**Comment by pombredanne** [comment] 2019-08-09 17:17
@geneh 

> component@cd:/pypi/pypi/-/youtube-dl/2014.09.14.3
> ```
> Some files failed to scan properly:
> Path: youtube_dl/extractor/dbtv.py
> ```

No longer an issue in latest `develop` branch. 

youtube_dl-2014.09.14.3-py2.py3-none-any.whl-extract/youtube_dl/extractor/dbtv.py


> component@cd:/nuget/nuget/-/linq2db.t4models/2.8.0
> 
> ```
> Some files failed to scan properly:
> Path: Data/Northwind.MS.sqlite
> Path: Data/Northwind.sqlite
> ```

The files are not there, but https://github.com/linq2db/linq2db/tree/5e26fa1693208b92b0791dff445ab7b42e79fb1b instead

https://github.com/linq2db/linq2db/raw/5e26fa1693208b92b0791dff445ab7b42e79fb1b/Data/Northwind.sqlite
https://github.com/linq2db/linq2db/raw/5e26fa1693208b92b0791dff445ab7b42e79fb1b/Data/Northwind.MS.sqlite

Both were sources of timeouts but's that no loger the case in develop.
There is a pending bug as there are copyrights detected incorrectly becasue of this https://github.com/audreyr/binaryornot/issues/43


> component@cd:/gem/rubygems/-/fastlane/2.127.2
> 
> ```
> Some files failed to scan properly:
> Path: fastlane_core/lib/fastlane_core/ui/github_issue_inspector_reporter.rb
> Path: spaceship/spec/tunes/fixtures/iap_pricing_tiers.json
> ```

One file is in the gem, but second file is not.

fastlane-2.127.2.gem-extract/data.tar.gz-extract/fastlane_core/lib/fastlane_core/ui/github_issue_inspector_reporter.rb

At https://github.com/fastlane/fastlane/raw/2.127.2/spaceship/spec/tunes/fixtures/iap_pricing_tiers.json we have a large JSON data file that triggered a timeout using 3.0.2.

Both are not an issue anymore in latest `develop` branch. 
 

> component@cd:/gem/rubygems/-/puppet/6.7.2
> 
> ```
> Some files failed to scan properly:
> Path: locales/ja/puppet.po
> ```

Not an issue in latest `develop` branch. 

puppet-6.7.2.gem-extract/data.tar.gz-extract/locales/ja/puppet.po

> component@cd:/maven/mavencentral/com.github.binarywang/weixin-java-miniapp/3.4.8.B
> 
> ```
> Some files failed to scan properly:
> Path: cn/binarywang/wx/miniapp/api/WxMaMediaService.java
> Path: cn/binarywang/wx/miniapp/bean/WxMaUniformMessage.java
> ```

Not an issue in latest `develop` branch:

weixin-java-miniapp-3.4.8.B-sources.jar-extract/cn/binarywang/wx/miniapp/bean/WxMaUniformMessage.java
weixin-java-miniapp-3.4.8.B-sources.jar-extract/cn/binarywang/wx/miniapp/api/WxMaMediaService.java


> component@cd:/npm/npmjs/@vue/cli-plugin-unit-mocha/4.0.0-beta.0
> 
> ```
> Some files failed to scan properly:
> Path: docs/ru/config/README.md
> Path: docs/zh/config/README.md
> Path: docs/zh/guide/build-targets.md
> ```

This is only in the Git repo and not in the npm tarball (and in fact no even in the subset of the repo from which the npm tarball was created) so are these coordinates correct?

vue-cli-4.0.0-beta.0.tar.gz-extract/vue-cli-4.0.0-beta.0/docs/ru/config/README.md
vue-cli-4.0.0-beta.0.tar.gz-extract/vue-cli-4.0.0-beta.0/docs/zh/config/README.md
vue-cli-4.0.0-beta.0.tar.gz-extract/vue-cli-4.0.0-beta.0/docs/zh/guide/build-targets.md

Not an issue in latest `develop` branch:



> component@cd:/npm/npmjs/@material-ui/utils/4.3.0
> 
> ```
> Some files failed to scan properly:
> Path: docs/src/pages/components/use-media-query/use-media-query-zh.md
> ```

Not in the npm tarball, in the repo only at https://raw.githubusercontent.com/mui-org/material-ui/8c28ed9c67e7b6ad02a8826178352aa4e9901b50/docs/src/pages/components/use-media-query/use-media-query-zh.md
Not an issue in latest `develop` branch.

> component@cd:/pypi/pypi/-/django-simpleui/2.6
> 
> ```
> Some files failed to scan properly:
> Path: django-simpleui-2.6/simpleui/templates/admin/login.html
> ```


Not an issue in latest `develop` branch. 
django-simpleui-2.6.tar.gz-extract/django-simpleui-2.6/simpleui/templates/admin/login.html


> component@cd:/npm/npmjs/-/cytoscape/3.7.5
> 
> ```
> Some files failed to scan properly:
> Path: documentation/md/style.md
> ```

Not in the npm tarball, but in the Git repo at https://raw.githubusercontent.com/cytoscape/cytoscape.js/eb80f7acdf5eb4845fc17377188e990ad08162fa/documentation/md/style.md

Not an issue in latest `develop` branch:



> component@cd:/gem/rubygems/-/pdf-reader/2.2.1
> 
> ```
> Some files failed to scan properly:
> Path: spec/data/broken_string.pdf
> Path: spec/data/encrypted_version1_revision2_128bit_rc4_no_doc_id.pdf
> Path: spec/data/kids-as-direct-objects.pdf
> Path: spec/data/mediabox_missing.pdf
> Path: spec/data/screwey_xref_offsets.pdf
> Path: spec/data/invalid/linearized_bad_xref_offset.pdf
> Path: spec/data/invalid/page_reference_is_not_a_dict.pdf
> Path: spec/data/invalid/trailer_root_is_not_a_dict.pdf
> ```

Not in the Gem tarball. But in the source repo at https://github.com/yob/pdf-reader/archive/164d7af9bf97989ca3ca022997de470fea9b9de8.zip
These are PDF files ued for testing in this package and they are broken by design....
ScanCode tries to extract text from them, but they are broken alright hence the parsing errors.
These are difficult, as these are files we would want to ignore eventually as they will break PDF readers by design.
One thing we could do there too is only report warnings.


> component@cd:/gem/rubygems/-/cocoapods-core/1.7.5
> 
> ```
> Some files failed to scan properly:
> Path: lib/cocoapods/user_interface/inspector_reporter.rb
> ```

Not in the Gem tarball, but in the source repo at https://raw.githubusercontent.com/CocoaPods/CocoaPods/1.7.5/lib/cocoapods/user_interface/inspector_reporter.rb

Not an issue in latest `develop` branch:

But we have another problem: https://github.com/CocoaPods/Core/releases/tag/1.7.5 is the source repo
Not https://github.com/CocoaPods/CocoaPods/ where the file was found.


> component@cd:/npm/npmjs/-/eslint-plugin-taro/1.3.10
> 
> ```
> Some files failed to scan properly:
> Path: docs/debug.md
> ```

Not in the npm tarball. But in the git repo at https://raw.githubusercontent.com/NervJS/taro/f866d884ae0357ea8718f5a0c0265adab7fd9a71/docs/debug.md


Not an issue in latest `develop` branch

**Comment by geneh** [comment] 2019-08-09 17:49
Thanks, @pombredanne! Please feel free to close the issue.

**Comment by pombredanne** [comment] 2019-10-15 17:09
This is all in 3.1.1RC and will be in the next 3.1.2 too and is in develop. Closing

**Closed by pombredanne** 2019-10-15 17:09 UTC
Labels: bug, fixed pending review, license scan
