### ISSUE TITLE
license_expression result can be improved 

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1383] opened 2019-02-18 14:06 UTC
When using maven parser to pare this pom file:
http://repo1.maven.org/maven2/edu/psu/swe/commons/commons-jaxrs/1.22/commons-jaxrs-1.22.pom

The better result should be this instead of empty.
"license_expression": "apache-2.0 AND unknown",

**Comment by pombredanne** [comment] 2019-02-18 14:53
@linexb when I run a scan on that pom with a `--package` I get this:
```
...


      "packages": [
        {
          "type": "maven",
          "namespace": "edu.psu.swe.commons",
          "name": "commons-jaxrs",
          "version": "1.22",
          "qualifiers": null,
          "subpath": null,
          "primary_language": "Java",
          "description": "Common JAXRS Libraries\nCommon classes to make creating REST services more consistent.",
          "release_date": null,
          "parties": [ ....
          ],
          "keywords": [],
          "homepage_url": "https://github.com/PennState/commons-jaxrs",
          "download_url": null,
          "size": null,
          "sha1": null,
          "md5": null,
          "sha256": null,
          "sha512": null,
          "bug_tracking_url": null,
          "code_view_url": "https://github.com/PennState/commons-jaxrs",
          "vcs_url": "git+ssh://git@github.com:PennState/commons-jaxrs.git",
          "copyright": null,
          "license_expression": "apache-2.0",
          "declared_license": "The Apache License, Version 2.0\nhttp://www.apache.org/licenses/LICENSE-2.0.txt",
          "notice_text": null,
          "manifest_path": null,
...
```

Are you using the latest ScanCode? You might want to try the 3.0.2?

**Comment by pombredanne** [comment] 2019-03-06 17:35
@linexb ping ... I could not reproduce this for this specific POM, but I know the problem exists. Note that with #1403 we will be able to be smarter when normalizing the declared license and avoid several of these "unknown"

**Comment by pombredanne** [comment] 2019-03-26 08:49
@linexb is this still happening with your latest updates for #1403 that were merged in develop?

**Comment by linexb** [comment] 2019-03-26 08:52
@pombredanne  The changes of #1403 was not merged into develop yet. :)

**Comment by pombredanne** [comment] 2019-06-02 17:59
This is now fixed in the `improved-license-rules-04-29` branch

**Closed by pombredanne** 2019-06-02 17:59 UTC
Labels: bug, license scan, package scan
