### ISSUE TITLE
Copyright detection should ignore license copyrights

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#819] opened 2017-10-25 15:25 UTC
Copyright detection reports the copyrights on license texts from codebases.  These are a distraction, and not helpful. Typical examples are the FSF and the Apache Software Foundation.

**Comment by pombredanne** [comment] 2017-10-25 15:28
Closed as dupe of #372 .... Thanks!

**Closed by pombredanne** 2017-10-25 15:28 UTC
Labels: bug, copyright scan, duplicate, license scan
