### ISSUE TITLE
Running v3.1.1 fails with "cannot import name RPM"

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#1875] opened 2020-01-09 07:45 UTC
### Description

Running `scancode --version` for v3.1.1 on Windows yields:

```
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
cannot import name RPM
========================================================================
Traceback (most recent call last):
  File "C:\Users\sebastian\Development\GitHub\nexB\scancode-toolkit\bin\scancode-script.py", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "C:\Users\sebastian\Development\GitHub\nexB\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\sebastian\Development\GitHub\nexB\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\sebastian\Development\GitHub\nexB\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\sebastian\Development\GitHub\nexB\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\sebastian\development\github\nexb\scancode-toolkit\src\scancode\cli.py", line 228, in <module>
    raise e
ImportError: cannot import name RPM
```

### How To Reproduce

I'm building ScanCode from Git sources on Windows. I was on tag `v3.0.2` (which works fine on Windows) and then switched to tag `v3.1.1`:

    $ git checkout v3.1.1
    $ ./configure --clean
    $ ./configure
    $ ./scancode --version

### System configuration

* What OS are you running on? Windows 10 x64 with Git Bash
* What version of scancode-toolkit was used to generate the scan file? 3.1.1
* What installation method was used to install/run scancode? Git

**Comment by pombredanne** [comment] 2020-01-09 12:11
@sschuberth I am not sure we ever tested Windows 10 x64 with Git Bash... 
Do you have the same issue from a plain command prompt as oppsoed to running gitbash (which is really Cygwin and is therefore a completely different beast than Windows... something like a crossover of POSIX and Windows)

**Comment by sschuberth** [comment] 2020-01-09 12:33
It indeed works when configuring ScanCode from *cmd* instead of *Git Bash*, i.e. when using `configure.bat` instead of `configure.sh` on Windows. As a quick work-around, how about issuing a warning and aborting `configure.sh` if the `OS` environment variable it set to `Windows_NT`?

**Comment by pombredanne** [comment] 2020-01-17 14:36
>  As a quick work-around, how about issuing a warning and aborting configure.sh if the OS environment variable it set to Windows_NT?

that would be great. I wish we could support Cygwin... but that's a can of worms that I have already played with in the past and that's really painful as instead of getting the best of Windows and POSIX it feels to me that you are instead faced with all the bugs and quirks of the union of both!

**Comment by arthur657834** [comment] 2020-03-04 02:12
this problem did not fix on linux, the code is update today

./configure --clean && ./configure is not work, and same error

Python 2.7.5
CentOS Linux release 7.5.1804 (Core)


10:04:55  ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
10:04:55  Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
10:04:55  The following plugin(s) are referenced and cannot be loaded/imported:
10:04:55  cannot import name RPM[0m
10:04:55  ========================================================================
10:04:55  Traceback (most recent call last):
10:04:55    File "/opt/scancode-toolkit/bin/scancode", line 11, in <module>
10:04:55      load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
10:04:55    File "/opt/scancode-toolkit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
10:04:55      return get_distribution(dist).load_entry_point(group, name)
10:04:55    File "/opt/scancode-toolkit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
10:04:55      return ep.load()
10:04:55    File "/opt/scancode-toolkit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
10:04:55      return self.resolve()
10:04:55    File "/opt/scancode-toolkit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
10:04:55      module = __import__(self.module_name, fromlist=['__name__'], level=0)
10:04:55    File "/opt/scancode-toolkit/src/scancode/cli.py", line 229, in <module>
10:04:55      raise e
10:04:55  ImportError: cannot import name RPM

**Comment by sschuberth** [comment] 2020-06-25 13:13
@pombredanne I'm actually seeing this error again on latest `develop`, but on Linux! Is there a regression?

**Comment by pombredanne** [comment] 2020-07-08 09:20
@sschuberth let me recheck. This was a non-starter solution https://github.com/nexB/scancode-toolkit/pull/1949#issuecomment-597691979

**Comment by pombredanne** [comment] 2020-07-10 07:22
@sschuberth

>  I'm actually seeing this error again on latest `develop`, but on Linux! Is there a regression?
> 
> _Edit:_ I just realized the PR that was supposed to fix this was closed unmerged!

Your PR fixed this alright and was merged 
@arthur657834 PR was not merged as it did not fix anything.

The issue on Windows is the original problem and was a gitbash/cygwin issues that you fixed

@sschuberth if you have a Linux issue, let's create a new ticket instead.
I created https://github.com/nexB/scancode-toolkit/issues/2108 ... can you add you details there?
@arthur657834 please do so too, as I would like to keep the windows and linux issues separated.
FWIW, I am not able to reproduce on a vanilla CentOS install

**Closed by pombredanne** 2020-07-10 07:22 UTC
Labels: documentation, installation and packaging
