### ISSUE TITLE
Improve license scan for proprietary license

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#560] opened 2017-03-16 08:20 UTC
```
Copyright (c) Wi-Fi Alliance 2006 - Confidential not for redistribution

=======================================================================
LICENSE
=======================================================================



License is granted only to Wi-Fi Alliance members and designated  Wi-Fi
contractors and, unless otherwise expressly authorized in writing by the
Wi-Fi Alliance, is limited for use solely in testing Wi-Fi equipment in
conjunction with a Wi-Fi certification program. This license is not
transferable or sublicensable, and it does not extend to and may not be
used with non-Wi-Fi applications.

Commercial derivative works or applications that use this software are NOT
AUTHORIZED without specific prior written permission from Wi-Fi Alliance.

Non-Commercial derivative works for your own internal use are authorized
and are limited by the same restrictions.

Neither the name of the author nor "Wi-Fi Alliance"
may be used to endorse or promote products that are derived
from or that use this software without specific prior written
permission from Wi-Fi Alliance.

THIS SOFTWARE IS PROVIDED BY WIFI ALLIANCE "AS IS" AND ANY EXPRESSED OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A  PARTICULAR PURPOSE,
ARE DISCLAIMED. IN NO EVENT SHALL WIFI ALLIANCE BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, THE COST OF PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```
The above proprietary license notice is detected as 
```
"key":"bsd-new","score":51.64
```

I cannot complain it is wrongly detected as the score is only 50%. However, can we somehow improve the scanning for the above notice.

**Comment by pombredanne** [comment] 2017-03-16 15:22
@chinyeungli Thanks. This is a great one.
It could even warrant to be added to ScanCode as its own license as this is common enough in Android and Linux contexts:
-  https://github.com/search?q=%22License+is+granted+only+to+Wi-Fi+Alliance%22&type=Code
- https://www.google.com/search?q=%22License%20is%20granted%20only%20to%20Wi-Fi%20Alliance%22&pws=0&gl=us&gws_rd=cr
- https://searchcode.com/?q=%22License+is+granted+only+to+Wi-Fi+Alliance%22

@DennisClark @richardfontana what would be your take?

**Comment by richardfontana** [comment] 2017-03-16 21:32
@pombredanne I don't think I have encountered this license before. I generally am in strong support of improving the ability of ScanCode to detect "things that look like they are probably licenses, but don't match anything known".

**Comment by pombredanne** [comment] 2017-03-16 23:23
@mjherzog @richardfontana thanks for the feedback. I am adding this as a new license.

@richardfontana you wrote:
>  I generally am in strong support of improving the ability of ScanCode to detect "things that look like they are probably licenses, but don't match anything known".

What ScanCode does is to detect these by construction and by design: if it looks like a license it will be eventually matched to some existing parts of some existing license with a low/lower score. The matched  license would not be the right one as in this case here. And the price to pay is also a few false positives like the ones you have reported over the last few weeks. The false positives are inevitable but can be cured with new detection rules over time. The interpretation of a partial match to an existing license needs review and these should become less and less frequent over time the more licenses and licenses rules we add to the data set. 

In recap, whenever you do not have a 100% detection score we have tow possible cases:
- partial, under detection: there are fewer detected words than present in an existing rule or license text. This can be either:
  - a correct detection, 
  - or a false positive,
  - or a detection of an unknown new license. This is the case we have here. 
I have not found a way yet to disambiguate these. Very low scores could be either a false positive or an unknown license. High scores could mean very close match and correct detection or the next case of over detection or an unknown license.

- over detection: there are more detected words than present in an existing rule or license text. e.g. there is extra text inserted that is not present in the reference matched license. This is an important and recent addition following a bug report by a kernel committer in #534

And the more rules and license we track, the better the detection becomes including in detecting rare and unknown licenses.

**Comment by pombredanne** [comment] 2017-03-18 17:57
This is fixed with the latest commit in develop

**Closed by pombredanne** 2017-03-18 17:57 UTC
Labels: bug, license scan
