### ISSUE TITLE
develop branch: scancode dies after scanning large number of files

### ISSUE THREAD

**Issue by 55jr55** [nexB/scancode-toolkit#289] opened 2016-08-05 15:09 UTC
running on MacOS against repository with approx 30k files. Error messages below.
# 

  [-----------------------------------#]  29688  Scanning: Makefile               [--------------------------#---------]  29689  Scanning: MANIFEST  
Scanning done.
Traceback (most recent call last):
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.6.3', 'console_scripts', 'scancode')()
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 664, in **call**
    return self.main(_args, *_kwargs)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/utils.py", line 61, in main
    standalone_mode=standalone_mode, *_extra)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(_args, *_kwargs)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/cli.py", line 248, in scancode
    results = scan(input, copyright, license, package, email, url, info, verbose, quiet)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/cli.py", line 315, in scan
    scan_result.update(scan_one(res, scanners))
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/cli.py", line 332, in scan_one
    scan = scan_func(input_file)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/api.py", line 178, in get_package_infos
    package = recognize_packaged_archives(location)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/packagedcode/recognize.py", line 58, in recognize_packaged_archives
    return package.get_package(location)
AttributeError: type object 'CpanModule' has no attribute 'get_package'
LWRVLC02RD20TG8WL:tigo-source jreynolds$

**Comment by pombredanne** [comment] 2016-08-05 21:52
Thank for reporting this . This is a bug.
I reckon you are using the develop branch, right?
This should not happen in the master branch. but this is a bug alright.

**Comment by pombredanne** [comment] 2016-08-07 22:58
@55jr55 can you tell which exact version of MacOSX you run?

**Comment by 55jr55** [comment] 2016-08-08 17:01
You are correct. I was using the develop branch. I'm on Mac OS 10.11.6.

**Comment by pombredanne** [comment] 2016-08-08 17:42
@55jr55 that latest commit should fix the problem for now. 

There is still something I do not like too much about the class hierarchy and code structure but develop should no longer exhibit this bug
I also merged in first @balusarakesh #281 which had most of the fix.
Note that develop is not always 100% stable... but your testing there is super valuable!

Unrelated since you are a Mac user in #290 I am thinking about dropping entirely support for older MacOSX versions < 10.9. In your experience would you see this as a big deal?

**Comment by 55jr55** [comment] 2016-08-09 14:19
I don't think dropping support for older MacOSX versions would be a big deal.

**Comment by pombredanne** [comment] 2016-08-09 14:47
@55jr55 Thank you for the feedback.

**Comment by pombredanne** [comment] 2016-08-09 14:47
Were you able to get you scan through?

**Comment by pombredanne** [comment] 2016-08-09 14:47
(with the latest develop code  of course)

**Comment by 55jr55** [comment] 2016-08-10 11:42
I did a pull to get the latest code and ran it again against the same code base. It got a lot farther then died. Output below.
----------------------------------------------------------------------
[----#-------------------------------]  93926  Scanning: src                   
[-#----------------------------------]  93927  Scanning: ProSLIC_API_Release_N  
[-#----------------------------------]  93928  Scanning: ProSLIC_API_Specification_Rev_3_8.pdf                             
Scanning done.
Traceback (most recent call last):
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.6.3', 'console_scripts', 'scancode')()
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/utils.py", line 61, in main
    standalone_mode=standalone_mode, **extra)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/cli.py", line 248, in scancode
    results = scan(input, copyright, license, package, email, url, info, verbose, quiet)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/cli.py", line 315, in scan
    scan_result.update(scan_one(res, scanners))
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/cli.py", line 334, in scan_one
    scan = list(scan)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/scancode/api.py", line 58, in get_copyrights
    for copyrights, authors, _years, holders, start_line, end_line in detect_copyrights(location):
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/cluecode/copyrights.py", line 69, in detect_copyrights
    for numbered_lines in candidate_lines(analysis.text_lines(location)):
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/cluecode/copyrights.py", line 836, in candidate_lines
    for line_number, line in enumerate(lines):
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/textcode/analysis.py", line 578, in unicode_text_lines_from_pdf
    for line in pdf.get_text_lines(location):
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/src/textcode/pdf.py", line 55, in get_text_lines
    interpreter.process_page(page)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 832, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 843, in render_contents
    self.init_resources(resources)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 347, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 195, in get_font
    font = self.get_font(None, subspec)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdfinterp.py", line 186, in get_font
    font = PDFCIDFont(self, spec)
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdffont.py", line 654, in __init__
    StringIO(self.fontfile.get_data()))
  File "/Users/jreynolds/git/nexB-GitHub-scanner/scancode-toolkit/lib/python2.7/site-packages/pdfminer/pdffont.py", line 373, in __init__
    (ntables, _1, _2, _3) = struct.unpack('>HHHH', fp.read(8))
struct.error: unpack requires a string argument of length 8

**Comment by pombredanne** [comment] 2016-08-10 12:21
This is a bug in the upstream PDFminer by @euske
There seems to be patches for this so it should be an easy fix. Beyond this I also need to strengthen the pdf parsing such that we never error out from a failed parse

**Comment by pombredanne** [comment] 2016-08-24 09:00
@55jr55 I could not reproduce or find a PDF that would exhibit the same issue as your `ProSLIC_API_Specification_Rev_3_8.pdf` .... But I am taking another route altogether:
a scan should **NEVER** fail, and certainly not fail because there is a weird file or a bug in some libraries used in scancode.

So the new approach is to catch all errors (aka exceptions) and reports errors at a file level in the scan results themselves if for any reason a file was not scanned.

**Comment by pombredanne** [comment] 2016-08-24 09:25
@55jr55 If you mind trying the latest develop branch using that one faulty PDF file, the scan should no longer fail. Thank you++ for reporting this

**Comment by 55jr55** [comment] 2016-08-24 21:50
I could not reproduce the error when just scanning the one PDF file using the original version I reported the error on. I was also unable to reproduce the error with the latest code but that wasn't much of a test. I'm running the latest code against the entire tree, 30k files. I should have the results in the morning.

**Comment by pombredanne** [comment] 2016-11-29 16:01
@55jr55 The latest code in the develop branch should handle this kind of errors without failure of the scan now. If there is an error on a single file, the error will be reported for that file in a `scan_errors` attribute for that file . The rest of the scan will not be affected and will continue alright.  If you do not mind giving a shot that would be great.

**Comment by pombredanne** [comment] 2016-11-30 14:20
This is all fixed in develop now. Closing. Thank you for your patience!

**Closed by pombredanne** 2016-11-30 14:20 UTC
Labels: bug, major, package scan
