### ISSUE TITLE
Building License detection index killed

### ISSUE THREAD

**Issue by ChinnuJose** [nexB/scancode-toolkit#1520] opened 2019-04-10 09:17 UTC
### Description
I have been using ScanCode without any issues for a while. Currently i am getting an error while scan  "Scanning files for: licenses, copyrights, packages with 10 process(es)...
Building license detection index...Killed "

### System configuration

* I am using Linux RedHat7.3
* scancode-toolkit-2.2.1
* I have used pip

**Comment by pombredanne** [comment] 2019-04-10 10:07
@ChinnuJose thank you for the report. Is this on Intel 32 or 64 bits? Which version of Python do you have there? Is this local pip install in a virtualenv or is this a global installation?
I am pretty sure that a pip installation might have problems with 2.2.1. You should try with 3.0.2

Also would you have the problem if you use a tarball installation instead?

**Comment by ChinnuJose** [comment] 2019-04-10 10:35
I have Python 2.7 & its a VM

**Comment by ChinnuJose** [comment] 2019-04-11 06:54
Scan Code works for options -c -p, it fails only for -l. We have tried rebuilding license index but that also got killed. Any solution for this?

**Comment by pombredanne** [comment] 2019-04-11 07:19
@ChinnuJose how much memory do you have on this VM? Typically the initial license index creation takes about 1.5GB. 

Also can you paste the full error trace you should have if you run this using ScanCode 3.0.2:
`scancode --verbose --license --json-pp - NOTICE`

**Comment by pombredanne** [comment] 2019-04-11 07:20
I assume above that you are in the scancode installation directory. Scanning any other file than NOTICE will work too.

**Comment by ChinnuJose** [comment] 2019-04-30 12:11
I have updated scancode toolkit to version 3.0.2. I am getting the below error while scanning : 

Traceback (most recent call last):
  File "/opt/Talko_scancode/scancode-toolkit-3.0.2/bin/scancode", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: scancode-toolkit

**Comment by pombredanne** [comment] 2019-04-30 13:16
@ChinnuJose Can you tell me how you updated scancode?

**Comment by ChinnuJose** [comment] 2019-04-30 13:37
Dowloaded scancode toolkit 3.0.2 zip and extracted to /opt and ran ./scancode.

**Comment by pombredanne** [comment] 2019-04-30 14:12
@ChinnuJose can you confirm you setup:
1. OS is RH EL 7.3 on X86_64 processor
2. You have only 1.5GB RAM
3. You have Python 2.7.x (please confirm the version)

Also could you extract the released zip in your home directory rather than in /opt for now?

**Comment by ChinnuJose** [comment] 2019-05-02 09:22
We have 64GB RAM in the VM.
Currently we are using Python 2.7.5

I have tried extracting the released zip to home folder still the error persist

**Comment by pombredanne** [comment] 2019-05-02 12:18
@ChinnuJose thanks. This is really not normal. I would need to know exactly which OS version you use exactly so that we can try to reproduce. Do you know if there is a trial version of RHEL 7.3 somewhere? or do you experience the same issue with CentOS?

**Comment by ChinnuJose** [comment] 2019-05-03 05:19
Issue faced in RHEL 7.3 only. 
We are using Red Hat Enterprise Linux Server release 7.3

**Comment by ChinnuJose** [comment] 2019-05-06 03:52
"pkg_resources.DistributionNotFound: The 'scancode-toolkit' distribution was not found and is required by the application"
Updated the pip to 8.1.2 same error is coming along with the description above

**Comment by pombredanne** [comment] 2019-05-06 13:53
@ChinnuJose thank you. I fetched a 7.3 trial ISO of RHEL and I will look into this.
I am a bit puzzled though: are you doing a pip installation ? or are you installing from a release archive from https://github.com/nexB/scancode-toolkit/releases ?

I would need to know exactly which command you used to be able to reproduce your installation.

**Comment by ChinnuJose** [comment] 2019-05-07 10:04
I have installed from the release archive. 
Downloaded the zip and extracted the file and used the ./scancode --help command to configure scancode.

DistributionNotFound error is fixed now, It was not supporting the command we used in the older version. We changed the command it is now working. 

Now the issue is while scanning using --l & --p we are getting the below error
Setup plugins...
Killed

Issue is not faced when using the --copyright option. Could you please help on this

**Comment by ChinnuJose** [comment] 2019-05-17 05:17
@pombredanne For scancode 3.0.2 is it possible to edit the output html format like in older version. Now custom-template option is used only for jinja template.

**Comment by pombredanne** [comment] 2019-05-22 13:28
@ChinnuJose yes it is. See my reply in #1567

**Comment by pombredanne** [comment] 2019-05-22 13:28
@ChinnuJose do you still have the "Killed" issue here? I could not reproduce it

**Comment by pombredanne** [comment] 2021-09-24 12:43
The index is now bundled so reindexing is no a requirement. Closing.

**Closed by pombredanne** 2021-09-24 12:43 UTC
Labels: bug, installation and packaging
