### ISSUE TITLE
Cannot install scancode toollkit from pip

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2480] opened 2021-04-07 16:13 UTC
### Description
```
pip install scancode-toolkit


$ scancode -h
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
No module named 'pytest'
========================================================================
Traceback (most recent call last):
  File "/tmp/bin/scancode", line 5, in <module>
    from scancode.cli import scancode
  File "/tmp/lib/python3.6/site-packages/scancode/cli.py", line 121, in <module>
    raise e
  File "/tmp/lib/python3.6/site-packages/scancode/cli.py", line 108, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/tmp/lib/python3.6/site-packages/plugincode/__init__.py", line 207, in load_plugins
    mgr_setup = manager.setup()
  File "/tmp/lib/python3.6/site-packages/plugincode/__init__.py", line 233, in setup
    raise e
  File "/tmp/lib/python3.6/site-packages/plugincode/__init__.py", line 231, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/tmp/lib/python3.6/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/tmp/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/home/pombreda/.pyenv/versions/3.6.10/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/lib/python3.6/site-packages/summarycode/plugin_consolidate.py", line 24, in <module>
    from summarycode import copyright_summary
  File "/tmp/lib/python3.6/site-packages/summarycode/copyright_summary.py", line 155, in <module>
    def summarize_copyrights(texts, _detector=CopyrightDetector()):
  File "/tmp/lib/python3.6/site-packages/cluecode/copyrights.py", line 134, in __init__
    import nltk
  File "/tmp/lib/python3.6/site-packages/nltk/__init__.py", line 142, in <module>
    from nltk.chunk import *
  File "/tmp/lib/python3.6/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/tmp/lib/python3.6/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/tmp/lib/python3.6/site-packages/nltk/parse/__init__.py", line 102, in <module>
    from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser
  File "/tmp/lib/python3.6/site-packages/nltk/parse/corenlp.py", line 23, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```
This was found by @AyanSinhaMahapatra

**Comment by pombredanne** [comment] 2021-04-07 16:14
The core issue is https://github.com/nltk/nltk/pull/2629#issuecomment-815036244 and https://github.com/nltk/nltk/issues/2690

**Comment by AyanSinhaMahapatra** [comment] 2021-04-07 16:14
Just running `pip install pytest` would get rid of this issue temporarily, as the problem has to be fixed on nltk side.

**Comment by pombredanne** [comment] 2021-04-07 16:18
Our dep is now `nltk >= 3.2, < 4.0` and needs to be updated to `nltk >= 3.2, !=3.6, < 4.0`

**Comment by pombredanne** [comment] 2021-04-08 06:13
nltk 3.6. has been replaced by 3.6.1 at https://pypi.org/project/nltk/3.6.1/ so the pressure is now lesser to make an urgent release on our side

**Comment by Pushpit07** [comment] 2021-04-11 11:16
running ``./configure`` still installs nltk version 3.2 even after ``nltk >= 3.2, !=3.6, < 4.0``

**Comment by pombredanne** [comment] 2021-04-23 07:01
@Pushpit07 re:

> running ./configure still installs nltk version 3.2 even after nltk >= 3.2, !=3.6, < 4.0

yes because there are two different things:

1. setup contain the direct dependencies expressed as ranges of supported versions
2. requirements contain pinned dependencies with exact versions

We support `nltk >= 3.2, !=3.6, < 4.0` in  https://github.com/nexB/scancode-toolkit/blob/bb044200ae86770f9bb01560c0033037ee18b947/setup.cfg#L78

But we install `nltk == 3.2` in https://github.com/nexB/scancode-toolkit/blob/bb044200ae86770f9bb01560c0033037ee18b947/requirements.txt#L35

**Comment by pombredanne** [comment] 2021-04-23 07:02
I think we are all set here. Closing!

**Comment by sschuberth** [comment] 2022-03-10 12:13
This is [happening again](https://github.com/oss-review-toolkit/ort/runs/5494035652?check_suite_focus=true#step:5:1465) as of today, but this time regarding `charset_normalizer`:

```
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
No module named 'charset_normalizer'
========================================================================
Traceback (most recent call last):
  File "/home/runner/.local/bin/scancode", line 5, in <module>
    from scancode.cli import scancode
  File "/home/runner/.local/lib/python3.8/site-packages/scancode/cli.py", line 122, in <module>
    raise e
  File "/home/runner/.local/lib/python3.8/site-packages/scancode/cli.py", line 109, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/runner/.local/lib/python3.8/site-packages/plugincode/__init__.py", line 207, in load_plugins
    mgr_setup = manager.setup()
  File "/home/runner/.local/lib/python3.8/site-packages/plugincode/__init__.py", line 233, in setup
    raise e
  File "/home/runner/.local/lib/python3.8/site-packages/plugincode/__init__.py", line 231, in setup
[...skipping 1 lines...]
  File "/home/runner/.local/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/runner/.local/lib/python3.8/site-packages/summarycode/plugin_consolidate.py", line 24, in <module>
    from summarycode import copyright_summary
  File "/home/runner/.local/lib/python3.8/site-packages/summarycode/copyright_summary.py", line 14, in <module>
    import fingerprints
  File "/home/runner/.local/lib/python3.8/site-packages/fingerprints/__init__.py", line 1, in <module>
    from fingerprints.generate import generate
  File "/home/runner/.local/lib/python3.8/site-packages/fingerprints/generate.py", line 3, in <module>
    from normality import collapse_spaces, stringify
  File "/home/runner/.local/lib/python3.8/site-packages/normality/__init__.py", line 13, in <module>
    from normality.encoding import guess_encoding, guess_file_encoding
  File "/home/runner/.local/lib/python3.8/site-packages/normality/encoding.py", line 4, in <module>
    from charset_normalizer import from_bytes, CharsetMatches
ModuleNotFoundError: No module named 'charset_normalizer'
```

**Comment by sschuberth** [comment] 2022-03-10 12:54
BTW, @pombredanne, following up on a comment by @maxhbr in ORT, what *is* the recommended way to install ScanCode nowadays?

We seem to have 3 options by now:
- from source
- via pip (see this issue)
- from the release archive (currently suffers from #2762 and #2869)

According to [ScanCode docs](https://github.com/nexB/scancode-toolkit/blob/develop/docs/source/getting-started/install.rst#installation-on-linux-and-mac), using the release archive seems to be the recommended way. Is that so?

**Comment by pombredanne** [comment] 2022-03-10 19:42
@sschuberth re: charset_normalizer: issue above

> This is happening again as of today, but this time regarding charset_normalizer:

Sorry for this, but there quite a bit of churn these on PyPI packages changing their minimal Python version and dropping Python 3.6 and I noted that this has many side effects. I am not sure this comes from our side though.

We have three options:
- 1. for developers, a git checkout or git tarball then run `./configure` or `./configure --dev`. This comes with fully locked dependencies.
- 2. for advanced users that want to control the set of dependencies and typically would use scancode as a library: `pip install scan ode-toolkit`. We cannot guarantee that the set of installed dependent version will work as it can vary over time. We are testing pip installs in the CI. We also have requirement constrain files that is used in 1. and 3. and that could be used technically but this is a bit more involved to obtain. These is the requirements.txt file at the root of the repo and is designed to be used with `pip install scancode-toolkit -c requirements.txt` and this would mean you would need to fetch the right requirements.txt file from the git tag for the SCTK version you are about to pip install
- 3. for regular users, the built release archive for a given OS/Python version. This comes with fully locked and bundled dependencies and can be installed offline on a machine that has only Python. **This is the recommended way.**


We are working to make sure that all these modes work fine in the upcoming 31.x version and that any quirk is fixed before a final release. There is going to be a beta and a few RCs to this effect. Windows (and macOS somehwat) are always the squeaky wheels making things harder of course.

**Comment by sschuberth** [comment] 2022-03-10 20:39
Ok, so that leaves us only with the option to build from source, I guess, as `pip install` does not work right now, and neither do the release archives due to #2869. I'll make the changes in ORT.

**Comment by pombredanne** [comment] 2022-03-10 21:49
> Ok, so that leaves us only with the option to build from source, I guess, as `pip install` does not work right now, and neither do the release archives due to #2869. I'll make the changes in ORT.

@sschuberth Can you tell me what is your exact setup? Because I can install from pip alright on Python 3.8 on Linux. There are no specific issues in general at this stage. There can be quirks at times, but most are rare. It could very much be that the "charset_normalizer" issues you have is a transient failure or an heisenbug. 

If the problem is that in https://github.com/nexB/scancode-toolkit/issues/2869#issuecomment-1064532365 then two notes:

1. this is not any of the recommended and documented ways to install so you will likely have problems
2. there was a transient DDoS issue 3 weeks ago that has since been resolved and that led to some installation issues for less than a day


If you use a proper release archive from https://github.com/nexB/scancode-toolkit/releases/tag/v30.1.0 for the exact Python and OS you use you only need to extract the tarball and run. You could ./scancode -h once (if you want to get things configured for instance in a pre-built Docker image layer)

**Comment by pombredanne** [comment] 2022-03-10 21:50
@sschuberth also FWIW I do not think your issue is related to this issue at all.

**Comment by sschuberth** [comment] 2022-03-15 14:28
> There can be quirks at times, but most are rare. It could very much be that the "charset_normalizer" issues you have is a transient failure or an heisenbug.

That indeed seems to have been the case, as the issue not reproducible anymore 🤷🏻‍♂️

**Closed as completed by sschuberth** 2022-03-15 14:28 UTC
Labels: bug
