### ISSUE TITLE
Scan output doesn't came up with a root directory

### ISSUE THREAD

**Issue by nspsjsu** [nexB/scancode-toolkit#447] opened 2017-01-11 21:00 UTC
I ran scans on a directory named gulp-3.9.1 by using the latest version of scancode-toolkit to get a .json & html output. Everything went well other than having a root directory! As a user i was expecting an overall root directory out of the scan result rather than having sub directories & files at the top level tree view!

**Comment by pombredanne** [comment] 2017-01-11 21:07
@nspsjsu yes, there is no root directory indeed. And it did not used to be the case. I have been thinking about the fact it is indeed a tad weird.  

Do you think we should always have one? and if so what would it be:
- If scan `/this/that/foo/` would this be `foo`?
- If I scan a single file `/this/that/foo/file.txt` would this be `foo` too?
- If I scan the root directory (rare) `/` would this be `/`?

**Comment by pombredanne** [comment] 2017-01-11 21:10
Yet, even if no root feels a tad weird, I am still wondering what is the benefit of a root directory?

**Comment by pombredanne** [comment] 2017-01-11 21:12
ah... I think I get it: if there is no root directory for a scan, I cannot ever summarize all of a scan under a single license and origin if that's the case, say for a package, as there is root to summarize to.

**Comment by nspsjsu** [comment] 2017-01-11 21:14
Yes, you're right. Sometimes it also helps us to determine the correct version & name.

**Comment by jdaguil** [comment] 2017-01-11 21:17
somewhere between `rc1` and `rc2` the `path`  value changed. For example: 

`"path": "/Users/jilliandaguil/Downloads/gulp-3.9.1/LICENSE", `

is now

`"path": "LICENSE",`

**Comment by pombredanne** [comment] 2017-01-11 21:20
@jdaguil @nspsjsu Thanks... this makes sense. Anyone else? with an opinion on the topic?

**Comment by mjherzog** [comment] 2017-01-11 21:25
I thought we had agreed to re-establish a root somehow - the issue is not summarizing at the level - the issue is very simply context

**Comment by majurg** [comment] 2017-01-11 21:39
I thinking having the 'root' makes a lot of sense and for me, its much easier to navigate around in the node view.

**Comment by pombredanne** [comment] 2017-01-11 21:44
@sschuberth any preference?

**Comment by sschuberth** [comment] 2017-01-11 21:51
I'd prefer to have relative paths WRT the directory to scan (as given on the command line) in the output. Scan results with absolute paths are not "portable" and might disclose unwanted information, like the user name. The caller always knows the root directory as that's what's being passed to ScanCode, and could amend the scan report with that information if required.

**Comment by pombredanne** [comment] 2017-01-11 21:58
@sschuberth so if you scan `scancode /a/b/c/` would the path values be OK if they are `c/foo/bar.txt`, `c/foor/baz/` or is using the `c/` as a the root an issue?

**Comment by sschuberth** [comment] 2017-01-11 22:03
IMO, running `scancode /a/b/c/` should list files like `d/foo/bar.txt` given that the absolute path to `bar.txt` is `/a/b/c/d/foo/bar.txt`. I.e. the concatenation of the path to scan (as given on the command line) and the path in the scan result output is the absolute path to the file.

**Comment by pombredanne** [comment] 2017-01-13 13:48
OK anyone else with an opinion? @akaihola ?

It sounds like we need both as both sides have a valid point.
It can be done with a command line option. Either:
- `--rooted-path` `Ensure that all paths are rooted in a single directory which is the last directory segment of a scanned path ` --> If as a default we continue to have current behavior eg. not root dit
- `--strip-root` `Strip the first root directory segment of all paths.` --> if as a default we restore the v1.x and 2.0.rc1 behavior.

**Comment by jdaguil** [comment] 2017-01-24 16:30
Any update @pombredanne? I agree with having an option to strip the root.

**Comment by sschuberth** [comment] 2017-01-24 19:30
Just one more comment from my side: SPDX even [requires the path to be relative](https://spdx.org/spdx-specification-21-web-version#h.37m2jsg) to the package root. So for SPDX output, it should always be relative even if a `--strip-root` option was not specified on the command line.

**Comment by pombredanne** [comment] 2017-02-24 16:43
@sschuberth the SPDX path is relative to the package root, but it does not specify what the package root is. It can be a directory alright in all cases. And in the case of a scan in any case we may be scanning a package or not.

**Comment by pombredanne** [comment] 2017-02-28 10:32
This is merged in develop

**Closed by pombredanne** 2017-02-28 10:32 UTC
Labels: bug, help wanted
