### ISSUE TITLE
GLIBC_2.14' not found issue and report not generated

### ISSUE THREAD

**Issue by aparnaNammi** [nexB/scancode-toolkit#463] opened 2017-01-23 11:04 UTC
Hi, Please resolve the below issue when I run this command : 
./scancode --format html project_R1.17New/lib project_R1.17New_result_lib_3Run.html --verbose

OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /app/share/scancode-toolkit-2.0.0rc1/src/typecode/bin/linux-64/lib/libmagic.so)
Thanks, Aparna

**Comment by pombredanne** [comment] 2017-01-23 14:10
@aparnaNammi Thank you for the report. 
Can you tell which exact version of Linux you are running?

**Comment by aparnaNammi** [comment] 2017-01-24 05:58
thanks .. this is the version of Linux : 2.6.32-642.11.1.el6.x86_64

**Comment by pombredanne** [comment] 2017-01-24 07:51
@aparnaNammi `2.6.32-642.11.1.el6.x86_64` is the version of your Linux Kernel (which is likely either a CentOS 6 or RHEL 6) but which distro and exact distro version do you use exactly?

I need to know that for any attempt to reproduce the issue you are facing.

**Comment by aparnaNammi** [comment] 2017-01-25 07:26
1.  uname -a
Linux ruvra86a0050 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Oct 26 10:25:23 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
2.  cat /proc/version 
Linux version 2.6.32-642.11.1.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Wed Oct 26 10:25:23 EDT 2016

**Comment by aparnaNammi** [comment] 2017-01-25 07:29
I have taken latest scan code zip and executed
./scancode html-app proj proj_result.html  and  ./scancode html proj proj_result.html
 commands, but still I am getting this error : OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /app/share/scancode/scancode-toolkit-develop/src/typecode/bin/linux-64/lib/libmagic.so)
This is the version of Linux I have :
Linux version 2.6.32-642.11.1.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Wed Oct 26 10:25:23 EDT 2016

**Comment by pombredanne** [comment] 2017-01-25 07:30
@aparnaNammi Thanks .... while you are at it: can you print `cat /etc/lsb-release` ?

And what does ScanCode say when you run `./scancode --version` ?

**Comment by pombredanne** [comment] 2017-01-25 07:40
and may be do you have a ` lsb_release` command too? I need to be able to reproduce: e.g if you can tell me: This is CentOS 6.5 x64, or Fedora 22 x64 or RHEL 6 that's all I need to know. Do you have that info?

**Comment by pombredanne** [comment] 2017-01-25 07:48
@aparnaNammi This may help: can you install this tool? https://github.com/nir0s/distro#installation and then run `distro` and paste the output? This should tell which exact Linux distro flavor and version you are running.

**Comment by aparnaNammi** [comment] 2017-01-25 09:31
Hi,
 I am not able to find lsb-release 
cat: /etc/lsb-release: No such file or directory
 ./scancode --version
ScanCode version 2.0.0rc3

**Comment by aparnaNammi** [comment] 2017-01-25 09:47
Red Hat Enterprise Linux Server release 6.7 (Santiago) 
written in the etc/redhat-release.
I do not have permission to install any thing on my Linux server

**Comment by pombredanne** [comment] 2017-01-25 09:58
@aparnaNammi  thanks. That hopefully be enough for me to debug this issue. Though per https://access.redhat.com/articles/3078#RHEL6 it looks like you are running a 6.8 Kernel, though that should not matter much. Now the difficulty for me will be to put my hands on a downloadable trial ISO  for this so I could test it in a VM.... 

Any idea? May be the trial from https://access.redhat.com/products/red-hat-enterprise-linux/evaluation ?

If not I might have to use CentOS that should be close enough. Or some old Fedora as I can read in this note: `Codename: Santiago (based on a mix of Fedora 12, Fedora 13, and several modifications)`

**Comment by aparnaNammi** [comment] 2017-01-25 10:40
I have no idea Philippe.. I'm sorry

**Comment by aparnaNammi** [comment] 2017-01-30 05:51
Hi .. Any luck on the fix for this issue

**Comment by pombredanne** [comment] 2017-01-30 08:57
Not yet: but some progress....

I downloaded a trial of RHEL 6 `rhel-server-6.7-x86_64-dvd.iso`. I will try later today to spin a VM and run ScanCode tests on it.

I also found this thread: https://www.redhat.com/archives/rhelv6-list/2012-August/msg00011.html which shows this is an issue other have faced

@akaihola Since you run Fedora and seem familiar with the RH/RHEL/Fedora-based distros I wonder if you have any idea on what could be a fix?

**Comment by akaihola** [comment] 2017-02-03 07:18
@pombredanne, I believe this is a very difficult issue to avoid as long as you distribute binaries of any required system libraries. It would help if you relied on pre-installed packages from Linux distributions instead.

Also, distributing binaries forces users to trust that the committers or their toolchains didn't inject malicious code.

I would prefer a more conventional installation procedure where
- I create the virtualenv myself
- all Python requirements are defined in `setup.py` and installed from PyPI, not included in the repository (as source nor binary)
- the list of required Linux system packages in `README.rst` would include all system library and compiler toolchain dependencies, and no binaries would be included in the repository
- I run `python setup.py install` or `python setup.py develop` in the virtualenv to prepare the environment

I see these points in the `README.rst` file:
> * Third-party components are vendored in the /thirdparty/ directory. ScanCode is self contained and should not require network access for installation or configuration of third-part libraries.
>* Additional pre-compiled vendored binaries are stored in bin/ sub-directories of the /src/ directory with their sources in this repo: https://github.com/nexB/scancode-thirdparty-src/

If the installation method based on precompiled binaries is required for some users, I'd prefer those binaries to be distributed separately from the main repository, in the same way as you've done for source code of third-party libraries. An alternative installation script would install using that set of binaries.

**Comment by pombredanne** [comment] 2017-02-22 09:33
@aparnaNammi RHEL 6.7 comes with Python 2.6.6 as stock Python. This is not supported for ScanCode.
What is the python version you have on your RHEL box? and how was it installed?

**Comment by pombredanne** [comment] 2017-02-22 11:16
@aparnaNammi I installed RHEL 6.7 in a VM and it does not have Python 2.7. 
https://developers.redhat.com/blog/2013/02/14/setting-up-django-and-python-2-7-on-red-hat-enterprise-6-the-easy-way/ explains how to get it but I need to know how you did install it exactly rather than relying on some article.

**Comment by pombredanne** [comment] 2018-11-11 18:51
As explained... this cannot run unless you install Python 2.7.x. Closing now

**Closed by pombredanne** 2018-11-11 18:51 UTC
Labels: bug, installation and packaging
