### ISSUE TITLE
segmentation fault error while running scans in an ubuntu instance in AWS

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#267] opened 2016-05-23 17:05 UTC
I cloned into the github repo `scancode-toolkit` in an Ubnuntu instance `(AWS-EC2 AMI - ami-06116566)` and used the command `./scancode --help` to configure scancode for the first time.
The next time when I try to run a command `./scancode --license file.txt` I'm getting the error

```
/scancode: line 16:  8253 Segmentation fault      (core dumped) $SCANCODE_ROOT_DIR/bin/scancode "$@"
```

**Comment by pombredanne** [comment] 2016-05-23 17:09
Do you have some more details on the OS version, architecture and version of Python used there?

**Comment by balusarakesh** [comment] 2016-05-23 17:12
`Ubuntu Server 14.04 LTS (HVM)`

**Comment by balusarakesh** [comment] 2016-05-24 02:47
@pombredanne  Python version is 2.7.6

**Comment by pombredanne** [comment] 2016-05-24 06:36
And which architecture? 32 or 64 bits?

**Comment by balusarakesh** [comment] 2016-05-24 06:37
64 bit

**Comment by balusarakesh** [comment] 2016-07-19 23:50
2.7 version of Python

**Comment by yahalom5776** [comment] 2016-10-18 07:05
Sorry to bring this up again but I seem to have a very similar issue when scanning a large project:
`./scancode: line 16:  2977 Killed $SCANCODE_ROOT_DIR/bin/scancode "$@"`

It is the current development branch installed on Debian 8 running in a VM with 2GB of RAM.

Python:
`python --version: 
Python 2.7.9`

OS:
`uname -a: 
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux`

Let me know if you need more information. Thank you.

**Comment by pombredanne** [comment] 2016-10-18 08:40
@yahalom5776 Thanks for the report. Can you tell me which command line options you used?

My best guess is that you have been prockilled' rather than segfaulted' based on your error message. This is something that should go away pretty soon. 
The issue is simple: at the moment the results of scanning each file is accumulated in RAM for all files.
Eventually when scanning larger codebase, this will exhaust available RAM and the kernel may prockill the scancode process in this case. The solution is going to be saving on disk the scan results of each file on the go and then streaming the final JSON at the end such that the scan results are never fully held in memory.
This is something I am working on in the orm-models branch https://github.com/nexB/scancode-toolkit/tree/orm-models 

The short term solution is to scan smaller chunks of a larger codebase. I am hoping to get some fix sometimes this week. In any case I will ping you to test the fix ass soon as this is ready.

**Comment by yahalom5776** [comment] 2016-10-18 09:46
I used only the "-l" switch in combination with the HTML output because I wanted to get a quick overview of the codebase. 

Thank you for the explanation, I am looking forward to the update. Please let me know if I can help with additional information or testing.

**Comment by sschuberth** [comment] 2016-11-04 15:18
Just chiming in that I also see

    scancode: line 16: 10193 Killed                  $SCANCODE_ROOT_DIR/bin/scancode "$@"

when running on Jenkins inside a VM and scanning [Apache Flink](https://flink.apache.org/) (incl. the source code of all its Maven dependencies). The command line used simply is

    scancode -f html . flink-scancode-50eaeec.html

> I am hoping to get some fix sometimes this week.

Is there an update? Any work on this would be very much appreciated!

**Comment by pombredanne** [comment] 2016-11-04 15:27
@sschuberth I am working on it and this is top priority

**Comment by pombredanne** [comment] 2016-11-04 15:27
No ETA yet though

**Comment by JonoYang** [comment] 2016-11-04 18:51
@sschuberth I am attempting to reproduce the issue. Could you tell me how to get the source code for Flink's Maven dependencies?

**Comment by sschuberth** [comment] 2016-11-04 21:24
Sure, in general for Maven you can use something like

    mvn dependency:unpack-dependencies \
        -Dclassifier=sources \
        -DoutputDirectory="$OUTDIR" \
        -Dmdep.useSubDirectoryPerArtifact=true \
        -Dmdep.useSubDirectoryPerScope=true

**Comment by JonoYang** [comment] 2016-11-04 23:41
@sschuberth I played with this and the size of the extracted source is about 13 gigabytes. @pombredanne is working on a solution. Hang in there!

**Comment by pombredanne** [comment] 2016-11-07 18:12
At this stage the branch `cache-and-stream-scan-results` in #354 should have a reasonable working solution that caches scan results on disk and then stream reads the cached results to create the final JSON output at the end. This should avoid pathological cases of large scans with million files being held in memory and eventually exhausting RAM.

The fix here should also address the issue reported in #341 as it was developed for both tickets.

**Comment by pombredanne** [comment] 2016-11-07 18:14
@sschuberth @yahalom5776 if you can run a test on your side in the same setup that triggered a failure that would be quite neat. This would mean using the `cache-and-stream-scan-results` branch here: https://github.com/nexB/scancode-toolkit/tree/cache-and-stream-scan-results either with a checkout or a plain download.

**Comment by sschuberth** [comment] 2016-11-07 21:34
Unfortunately, I'm still getting

    scancode: line 16: 20559 Killed                  $SCANCODE_ROOT_DIR/bin

with the `cache-and-stream-scan-results` branch when scanning Apache Flink plus dependencies. I've used JSON instead of HTML output this time. Will double-check tomorrow to see if I did something wrong.

**Comment by pombredanne** [comment] 2016-11-07 21:51
@sschuberth Thanks for running the test. So there is another problem then. Digging further ...

**Comment by pombredanne** [comment] 2016-11-07 22:15
this is surely on scancode's side

**Comment by pombredanne** [comment] 2016-11-07 22:36
@sschuberth do you mind trying to run the scan with `--verbose` and tell me which is the last file path from Apache Flink that is being processed (as displayed on screen) when the scan is eventually proc killed?

**Comment by pombredanne** [comment] 2016-11-08 00:51
So the issue is likely due to a single file taking a very long time to scan and accumulating several stuffs internally such as many junk license matches that are then filtered out (but they are not filtered because the accumulation just make the thing blow up before).

There is going to be a few directions to fix this:
1. implement a timeout on scanning a single file: this is an OK proxy to find of these pathological cases. Eventually this should be adaptive based on a file size and/or type
2. possibly reject scanning very large single file (e.g. GB-size and similar)
3. fixing the issue in license detection

With 1 and 2 the scan would not fail anymore at least but report a timeout of a problematic file instead
3 will be fixed too, but 1 and 2 would guard against any re-occurrence of a similar problem. 

In any case the caching and streaming I implemented was needed anyway so this is not time wasted at all.

**Comment by sschuberth** [comment] 2016-11-08 08:20
> do you mind trying to run the scan with `--verbose`

One of the issues I already had earlier is: If you run ScanCode on Jenkins CI, it seems to be "smart" and does not show any progress or verbose output as no TTY is attached. How about making an explicit `--verbose` disable that logic and make ScanCode still show verbose output in that case?

**Comment by yahalom5776** [comment] 2016-11-09 15:32
@pombredanne Thank you for implementing this very important improvement! I will re-run the scans and let you know if the problems still persist with my test cases.

**Comment by pombredanne** [comment] 2016-11-09 16:15
@yahalom5776 Per @sschuberth the fix is not enough, so I am still working on something else to implement time outs and a few other fixes to avoid excessive memory usage in some corner cases.

**Comment by yahalom5776** [comment] 2016-11-09 20:26
@pombredanne Sure, I would just like to add another data point to the discussion. My suspicion (not verified so far) is that the scan of large archive files is the culprit. In my test case I had many nested archives extracted by _extractcode_ and when I ran the scan I realized the archives were still there and _ScanCode_ probably processed them. 

So could we perhaps improve the situation also by adding a new functionality to _extractcode_: "Delete archive(s) after successful extraction"?

**Comment by pombredanne** [comment] 2016-11-09 20:49
@yahalom5776 this is definitely a bug: do you mind entering it separately?

**Comment by yahalom5776** [comment] 2016-11-09 21:03
@pombredanne Sure, I will verify it and then file a separate issue with the details.

**Comment by pombredanne** [comment] 2016-11-09 21:24
@yahalom5776 thanks!

**Comment by yahalom5776** [comment] 2016-11-10 10:19
@pombredanne Regarding the proc kill: It still happens in my testcase but I was probably able to identify the file that causes it: 
m32c-desc.c from GNU binutils 2.17.50 (in the opcodes subdirectory). File size: 4.2 MB, 63,218 lines. At least one other C file in that directory has a similar size.

Header states:
`/* CPU data for m32c.

THIS FILE IS MACHINE GENERATED WITH CGEN.
`

**Comment by pombredanne** [comment] 2016-11-14 08:00
@sschuberth this latest commit adds numerous improvements that should both help handle the issue you are facing AND help diagnose it:

 * a scan can be interrupted if it takes too long and exceeds a timeout: so if there is a problem somewhere, it should timeout rather than suck all the memory and get proc killed (hopefully)
 * a scan can run on multiple processes with the -n option (this is a nice side effect of handling timeouts and can also speed up scanning of course, but would use more RAM) 
 * --verbose output is always send to stdout, as you requested above.
 * a summary of the scan statistics is displayed at the end: this help diagnose errors as it will list all the paths that failed to scan alright.
 * Note that at this stage the tests and extractcode and tests are not up to date/working yet and need fxing still

So running a `--verbose` scan on this would likely tell exactly which is the file that is causing an error.

**Comment by pombredanne** [comment] 2016-11-14 08:01
@yahalom5776 Thanks. This is going to be very useful! The latest code in the `long-scan-timeout` branch should normally no longer error out. I will test using that file tomorrow.

**Comment by sschuberth** [comment] 2016-11-14 09:01
Thanks @pombredanne for all of your work, I'll start running some scans right away. However, it might take the whole day to actually get the results (if ScanCode manages to go through :-)

**Comment by pombredanne** [comment] 2016-11-14 16:44
@sschuberth No rush. If this ever still fails, I can add another "limit" to a scanned file that would be a memory quota not to exceed using essentially the same approach as the timeout (eg. a combo of multithreading and multiprocessing). I did not implement it just yet as this would slow down the scanning overall

**Comment by pombredanne** [comment] 2016-11-15 02:29
ouch... I just realized I made a typo: 1024*1024 is one MB and 1024*1024*1024 is one GB...
I need to learn how to count! :school:  ... this makes all the timeouts and max_memory computation wrong by a small 1000 factor. duh.

**Comment by pombredanne** [comment] 2016-11-15 07:44
The latest commit now makes memory checks by default and fixed the flawed timeout and max_memory computation. 

@sschuberth @yahalom5776 Your scans should not fail any more with the latest code in the `long-scan-timeout ` branch and if any, scan errors should be reported (but the scan should not crash).

**Comment by sschuberth** [comment] 2016-11-15 08:46
My yesterday's scan using ScanCode Git revision eb2c9cb completed after 8 hours and 59 minutes running in a Jenkins CI job. The good news is that is *did* complete after all without getting proc-killed:

    Scan statistics: 34632 files scanned in 32163s.
    Scan options:    licenses, copyrights, packages with 1 processes.
    Scanning speed:  1.1 files per sec.
    Scanning time:   32048s.
    Indexing time:   114s.

Today I'll try your latest long-scan-timeout branch with Apache Flink again.

**Comment by pombredanne** [comment] 2016-11-16 19:17
At this stage everything is mostly working but there are some test failures I still need to correct.... Interestingly the failures are different on Windows (now just some path issue), Linux (test randomly runs too slow or too fast) and Mac (hangs on multithreading tests) 

... multithreading and multiprocessing across OS is a tad devilish to get right: hang in there, we are almost there!

**Comment by pombredanne** [comment] 2016-11-16 19:18
@sschuberth note that with the new `--processes` option you could run on multiple processes (if you have them and enough RAM)  and this would/should speed up scanning quite a bit..

**Comment by pombredanne** [comment] 2016-11-17 01:51
Status update: we are getting there: the build pass now on Windows and Linux. Mac is still queued for now.

**Comment by sschuberth** [comment] 2016-11-17 08:46
> note that with the new `--processes` option you could run on multiple processes

It's great to have that option now, and it certainly helps speeding up scans on my local machine where I have enough RAM. On our CI (which runs on a virtual machine) I guess it will not help that much, but I'll experiment with it.

**Comment by yahalom5776** [comment] 2016-11-17 09:00
@pombredanne No luck for me. I tried a scan with the code from 580b4ca and it hangs when trying to scan  the CloudFoundry bosh package. The scan ran during the night,  package was extracted with extratcode. 
![scancode](https://cloud.githubusercontent.com/assets/19911347/20382409/22b360ba-acac-11e6-9625-c37233521295.PNG)

The file is an ELF binary, ca. 10 MB in size. The VM is Debian 8 (x64) with two vCPUs and 3GB RAM.

Any ideas? Thanks.

**Comment by sschuberth** [comment] 2016-11-17 09:08
@yahalom5776 There's a bunch of more fixes on top of `580b4ca` in https://github.com/nexB/scancode-toolkit/pull/369. Would you mind trying the latest state of that PR?

**Comment by yahalom5776** [comment] 2016-11-17 09:37
@sschuberth @pombredanne Will do and report back.

**Comment by pombredanne** [comment] 2016-11-17 16:55
All the CI builds completed and are now all passing :green_heart:  The timeout branch has been merged in develop!

@yahalom5776 I hope the latest code will fix this new crash of yours. 

@yahalom5776 do you have a download URL to the CF Bosh package?


All: Note that the `max_memory` quota is fixed in code rather than being configurable. I guess I could add a command option to configure it? What do you think?

**Comment by sschuberth** [comment] 2016-11-17 19:21
> I guess I could add a command option to configure it?

I agree. You already introduced `--processes` to specify how much hardware resources to use (in terms of CPU), and a `--max-memory` option would fall into the same category.

**Comment by pombredanne** [comment] 2016-11-17 23:12
@sschuberth  you wrote:
> I agree. You already introduced --processes to specify how much hardware resources to use (in terms of CPU), and a --max-memory option would fall into the same category.

Thanks. This make sense. Let me add that later today.

**Comment by pombredanne** [comment] 2016-11-17 23:17
@yahalom5776 I think I found the download URL for the releases of https://github.com/pivotal-golang/s3cli  at https://s3cli-artifacts.s3.amazonaws.com/s3cli-0.0.53-linux-amd64
Let me test that one

**Comment by yahalom5776** [comment] 2016-11-18 08:20
@pombredanne Thanks, the package I use for the tests is from here: http://bosh.cloudfoundry.org/d/github.com/cloudfoundry/bosh?v=260
`sha1: f8f086974d9769263078fb6cb7927655744dacbc`

Still no luck with the most current commit, though.
The `--max-memory` option would be a good addition to the tool.

**Comment by pombredanne** [comment] 2016-11-18 18:26
@yahalom5776 thanks. I pushed a new branch `267-cli-options-for-timeout-and-max_memory` to have explicit timeout and max-memory CLI options as you and @sschuberth suggested.
I am also looking into the reason why we exceed the quotas on the two test files you listed.

btw, does your VM have any virtual memory/swap at all?

**Comment by pombredanne** [comment] 2016-11-18 19:58
The code in #371 adds the timeout and memory options. All tests pass. Review welcomed! I will likely merge this in over the week-end.

**Comment by pombredanne** [comment] 2016-11-22 08:18
Just updating the status: I am refining a fairly significant refactoring to fix the memory leak that is the root cause for this error after all: this is because of these two innocent looking lines here:
https://github.com/nexB/scancode-toolkit/blob/c12948ce1d687b69bfb710900d95927295035196/src/licensedcode/match.py#L294

They eventually create monster duplicated dictionaries (and after digging these are useless in that form) that end up growing and growing in size at each license match merge run and in some corner cases until the RAM blows up.

**Comment by pombredanne** [comment] 2016-11-24 16:11
@yahalom5776 I added new tests for the two test files you submitted here. The latest commits in PR #376 should now provide a comprehensive fix for the memory leak and memory quotas, timeouts and cache streaming on disk, plus a few extra side refinements.
@sschuberth your feedback is welcomed too :)

**Comment by yahalom5776** [comment] 2016-11-24 17:03
@pombredanne Thanks a lot, I hope I'll be able to test it tomorrow. If forgot to answer your question above, sorry. Swap is 2.5 GB for this VM, about 900 MB were used when ScanCode hung.

**Comment by pombredanne** [comment] 2016-11-30 14:18
Even though this ticket was originally about some AWS issue and evolved in memory issues, I think this is all fixed now and I am closing this. Thank you all for the inputs and tests!

**Closed by pombredanne** 2016-11-30 14:18 UTC
Labels: bug

**Comment by sschuberth** [comment] 2016-11-30 14:22
@pombredanne Just to confirm: With these fixes ScanCode is now running much more stable and also faster on our Jenkins CI which is running in a VM. Your recent work as been nothing short of awesome, thanks a lot for that!

**Comment by yahalom5776** [comment] 2016-11-30 16:13
@pombredanne I second that, thank you!
