### ISSUE TITLE
'EnhancedProgressBar' object is not an iterator

### ISSUE THREAD

**Issue by adamhowardprice** [nexB/scancode-toolkit#2284] opened 2020-10-15 23:38 UTC
### Description

> Please leave a brief description of the bug or feature request:

Cannot run `scancode` without hitting error: `'EnhancedProgressBar' object is not an iterator`

### How To Reproduce

> Tell us how to reproduce the issue. 

In my repo with a lot of Python, Ruby, and C++ code, run `extractcode` and then `scancode -clpeui -n 2 --json-pp software.json .`

```
extractcode .
scancode -clpeui -n 2 --json-pp software.json .
```

Output:
```
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages, emails, urls with 2 process(es)...
Removing temporary files...done.
Traceback (most recent call last):
  File "/Users/aprice/.pyenv/versions/software-3.6.3/bin/scancode", line 10, in <module>
    sys.exit(scancode())
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/scancode/utils.py", line 70, in main
    standalone_mode=standalone_mode, **extra)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/scancode/cli.py", line 530, in scancode
    *args, **kwargs)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/scancode/cli.py", line 927, in run_scan
    quiet=quiet, verbose=verbose, kwargs=requested_options, echo_func=echo_func,
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/scancode/cli.py", line 1118, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/Users/aprice/.pyenv/versions/3.6.3/envs/software-3.6.3/lib/python3.6/site-packages/scancode/cli.py", line 1212, in scan_codebase
    location, rid, scan_errors, scan_time, scan_result, scan_timings = next(scans)
TypeError: 'EnhancedProgressBar' object is not an iterator
```

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
MacOS 10.15.7
* What version of scancode-toolkit was used to generate the scan file?
`scancode-toolkit==3.2.0`
* What installation method was used to install/run scancode? (pip/source download/other)
`pip install scancode`

**Comment by pombredanne** [comment] 2020-10-16 06:55
You may have been hitting a Click bug such as https://github.com/pallets/click/issues/1125
Could you run this an attach the results here?
`pip freeze > requirements-lock.txt`
I would need to verify that this is a version with issues.

Also can you try using the release tarball if the issue is still present?
Thanks!

**Comment by pombredanne** [comment] 2020-10-16 12:56
Actually I have a fix and this is indeed because of https://github.com/pallets/click/issues/1125

**Comment by pombredanne** [comment] 2020-10-17 05:37
@adamhowardprice I merged https://github.com/nexB/scancode-toolkit/pull/2288 and this should fix the bug. Can you check out develop and try if this works for you? Thanks!

**Comment by pombredanne** [comment] 2020-10-20 17:37
This is tested and merged, so I am closing this now. Thank you ++

**Closed by pombredanne** 2020-10-20 17:37 UTC
Labels: bug
