### ISSUE TITLE
Consider using CirceCI for MacOS (and Linux?) builds

### ISSUE THREAD

**Issue by alisianoi** [nexB/scancode-toolkit#582] opened 2017-03-30 08:31 UTC
As pointed out [here][1] and [here][2], having a redundant build service is not a bad idea. Also, it might turn out to be easier to maintain/setup. Give it a thought/try to make `scancode-toolkit` build there.

Here is [`spdx/tools-python`][3] that builds on CircleCI on MacOS

[1]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-289993567
[2]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-289995854
[3]: https://github.com/spdx/tools-python/blob/master/circle.yml

**Comment by pombredanne** [comment] 2017-03-30 15:32
Thank you.
and @sschuberth has some experience too in that space.

**Comment by tdruez** [comment] 2017-03-31 09:23
@all3fox https://github.com/joerick/cibuildwheel is very new but looks promising.
Do you think it could be valuable here?

**Comment by all3fox** [comment] 2017-03-31 10:22
@tdruez I still don't quite get the workflow of wheel-building services.

As far as I understand, the scenario looks like this:

1. You introduce a new dependency lib/bump the version of your dependency lib.
2. You do not want to `pip install` the lib for any reason, so you want to ship it (vendor it?) together with your code.
3. You create a wheel out of your dependency (because that is more convenient than the source?)
4. That wheel can be either an easy one (a universal `py2.py3-none-any` wheel you can build on your machine whith `pip install wheel && python setup.py bdist_wheel`) or a hard one (you have to build the wheel for specific pythons/OSes).
5. In case when it's a hard one, you can use any trick up your sleeve to generate those platform-specific wheels.

The tricks I know of:

1. Hope the package actually ships all those wheels you need, like probably [coverage][1] does.
2. Use some repo (like you are linking to, or like [linked here][2])
3. Have enough different physical machines at home to build wheels (unlikely and slightly crazy)

If you are going with 2., then the only requirement I can think of is this: you must be able to precisely control the build environment on the CI server and get out the wheels you want/need. The repo you are linking to seems to do that. So do other repos though :)

So, finally, no idea how valuable that could be :) Whatever works for you `¯\_(ツ)_/¯` 

[1]: https://pypi.python.org/pypi/coverage
[2]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-289630703

**Comment by pombredanne** [comment] 2017-04-01 14:53
@all3fox you wrote:
> I still don't quite get the workflow of wheel-building services. As far as I understand, the scenario looks like this:
> 1. You introduce a new dependency lib/bump the version of your dependency lib.
> 2. You do not want to `pip install` the lib for some reason, so you want to ship it (vendor it?) together with your code.

Actually you still want to `pip install` it, but either:
1. there is no pre-built wheel available on Pypi
2. you want to build it with specific options
3. it contains native code and/or is pure Python bu not universal. And the corresponding wheel do not exists as pre-built. This is the main use case: in particular you cannot assume that a regular user would have a compiler installed on macOS and Windows, and therefore a pre-built wheel is best.

Now beside this the installation of a wheel is mostly a plain unzip and does not execute code in the wheel so it many times faster than an actual build.

> 3. You create a wheel out of your dependency (because that is more convenient than the source?)

Because if the reasons I outlined above: it is faster and does not require a compiler for packages with native C/C++ code.

> 4. That wheel can be either an easy one (a universal `py2.py3-none-any` wheel you can build on your machine whith `pip install wheel && python setup.py bdist_wheel [--universal]`) or a hard one (you have to build the wheel for specific pythons/OSes).
> 5. In case it's a hard one, you can use any trick up your sleeve to generate those wheels.
>
> The tricks I know of:
>
> 1. Hope the package actually ships all those wheels you need, like probably [coverage][1] does.

And when this is the case, the problem is solved.

> 2. Use some repo (like you are linking to, or like [linked here][2]) that relies on CI services

https://github.com/pombreda/thirdparty and https://github.com/pombreda/thirdparty-manylinux/ have been some simple attempts of mine in that realm


> 3. Have enough different physical machines at home to build wheels (unlikely and slightly crazy)

This is not practical. Been there and done that and it is a major pain. VMs can work too and less painful, but still a PITA to maintain when you do not use these not too frequently.

[1]: https://pypi.python.org/pypi/coverage
[2]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-289630703

**Comment by pombredanne** [comment] 2022-02-02 08:06
We have now a fairly decent support for multiple OS arch in tests with Azure. Closing at last.

**Closed by pombredanne** 2022-02-02 08:06 UTC
Labels: installation and packaging, task
