### ISSUE TITLE
Archives of scancode 1.4.0 don't run.

### ISSUE THREAD

**Issue by rrjohnston** [nexB/scancode-toolkit#142] opened 2015-12-01 21:45 UTC
After unpacking either the bz2 or zip file onto 3.13.0-32-generic #57~precise1-Ubuntu machine, trying to run the utility on a source directory (after running './scancode --help') always results in the following error (this particular example was scanning the scancode-toolkit-1.4.0/src directory):

$: ./scancode --format html src src.html
Scanning files...
  [------------------------------------]  1  Scanning: textcode
Scanning done.
Traceback (most recent call last):
  File "/<path>/scancode-toolkit-1.4.0/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.4.0', 'console_scripts', 'scancode')()
  File "/<path>/scancode-toolkit-1.4.0/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/<path>/scancode-toolkit-1.4.0/src/scancode/utils.py", line 61, in main
    standalone_mode=standalone_mode, **extra)
  File "/<path>/scancode-toolkit-1.4.0/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/<path>/scancode-toolkit-1.4.0/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/<path>/scancode-toolkit-1.4.0/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/<path>/scancode-toolkit-1.4.0/src/scancode/cli.py", line 244, in scancode
    results = scan(input, copyright, license, package, info, verbose, quiet)
  File "/<path>/scancode-toolkit-1.4.0/src/scancode/cli.py", line 312, in scan
    scan_result.update(scan_one(res, scanners))
  File "/<path>/scancode-toolkit-1.4.0/src/scancode/cli.py", line 329, in scan_one
    scan = scan_func(input_file)
  File "/<path>/scancode-toolkit-1.4.0/src/scancode/api.py", line 137, in get_package_infos
    from packagedcode.recognize import recognize_packaged_archives
ImportError: No module named packagedcode.recognize

**Comment by jdaguil** [comment] 2015-12-01 23:27
@rrjohnston I've reproduced the error from the release archives as well. Although the issue is not present when cloning from master or downloading the archive directly from the master branch.

**Comment by pombredanne** [comment] 2015-12-03 07:32
I found the culprit: https://github.com/nexB/scancode-toolkit/blob/9be433a8e6f1741aa75de64fe00d0fdc458625c5/etc/release/MANIFEST.in.release#L8
This is the release script. Let me re-run and push a new .release

**Comment by pombredanne** [comment] 2015-12-03 07:36
I will also be adding a release test (either a plain script or as part of the CI configs)

**Comment by pombredanne** [comment] 2015-12-03 12:40
This is fixed in the new release 1.4.2. And from now on, sanity checks are included in the release script. 
@rrjohnston Thank you for the report!

**Closed by pombredanne** 2015-12-03 12:40 UTC
Labels: bug, major
