### ISSUE TITLE
Incorrect detection of GPL-2.0

### ISSUE THREAD

**Issue by LeChasseur** [nexB/scancode-toolkit#1733] opened 2019-09-19 15:32 UTC
Scanning of the following file (clearly MIT only) 
https://github.com/WordPress/WordPress/blob/master/wp-includes/js/thickbox/thickbox.js
provides the following result:

 "type": "file",
      "licenses": [
        {
          "key": "mit",
          "score": 50.0,
          "name": "MIT License",
          "short_name": "MIT License",
          "category": "Permissive",
          "is_exception": false,
          "owner": "MIT",
          "homepage_url": "http://opensource.org/licenses/mit-license.php",
          "text_url": "http://opensource.org/licenses/mit-license.php",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:mit",
          "spdx_license_key": "MIT",
          "spdx_url": "https://spdx.org/licenses/MIT",
          "start_line": 5,
          "end_line": 5,
          "matched_rule": {
            "identifier": "mit_or_gpl-2.0_14.RULE",
            "license_expression": "mit OR gpl-2.0",
            "licenses": [
              "mit",
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 24,
            "matched_length": 12,
            "match_coverage": 50.0,
            "rule_relevance": 100.0
          },
          "matched_text": "Licensed under the MIT License: http://www.opensource.org/licenses/mit-license.php"
        },
        {
          "key": "gpl-2.0",
          "score": 50.0,
          "name": "GNU General Public License 2.0",
          "short_name": "GPL 2.0",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
          "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0",
          "spdx_license_key": "GPL-2.0-only",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0-only",
          "start_line": 5,
          "end_line": 5,
          "matched_rule": {
            "identifier": "mit_or_gpl-2.0_14.RULE",
            "license_expression": "mit OR gpl-2.0",
            "licenses": [
              "mit",
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 24,
            "matched_length": 12,
            "match_coverage": 50.0,
            "rule_relevance": 100.0
          },
          "matched_text": "Licensed under the MIT License: http://www.opensource.org/licenses/mit-license.php"
        }
      ],
      "license_expressions": [
        "mit OR gpl-2.0"
      ],
      "copyrights": [
        {
          "value": "Cody Lindley (http://www.codylindley.com) Copyright (c) 2007",
          "start_line": 3,
          "end_line": 5
        }
      ],
      "holders": [
        {
          "value": "Cody Lindley",
          "start_line": 3,
          "end_line": 5
        }
      ],
      "authors": [],
      "emails": [],
      "urls": [
        {
          "url": "http://www.codylindley.com/",
          "start_line": 3,
          "end_line": 3
        },
        {
          "url": "http://www.opensource.org/licenses/mit-license.php",
          "start_line": 5,
          "end_line": 5
        }
      ],
      "scan_errors": []
    },

It seems that the tool is confused by the  "mit OR gpl-2.0". I haven't found any indication for a dual licensing here. The header is as follows:

/*
 * Thickbox 3.1 - One Box To Rule Them All.
 * By Cody Lindley (http://www.codylindley.com)
 * Copyright (c) 2007 cody lindley
 * Licensed under the MIT License: http://www.opensource.org/licenses/mit-license.php
*/

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 3.1.1.post16.e9272cd,
* What installation method was used to install/run scancode? source download

**Comment by pombredanne** [comment] 2019-09-20 08:01
@LeChasseur Thank you for the report. I think this has been fixed in the `develop` branch.

**Comment by pombredanne** [comment] 2019-10-02 09:10
Note that the score was low: 50/100

**Comment by pombredanne** [comment] 2019-10-02 09:10
I am closing this now, since this is confirmed fixed in the develop branch

**Closed by pombredanne** 2019-10-02 09:10 UTC
Labels: fixed pending review, license scan
