### ISSUE TITLE
Familiarisation of using Path.py  #1610

### ISSUE THREAD

**Issue by Abhishek-Dev09-zz** [nexB/scancode-toolkit#1637] opened 2019-07-02 14:43 UTC
This is an extension of #1610

This give us guide line how deal with path for porting the path #295 
a)macOS
b)linux
c)Window
Pypa package- path.py
Outcome- This support both python 2 and 3.
For reference: https://github.com/jaraco/path.py and https://pypi.org/project/path.py
https://github.com/jaraco/path.py/issues/130

**Comment by Abhishek-Dev09** [comment] 2019-07-02 22:37
As dependencies has been added in PR #1639

**Comment by Abhishek-Dev09** [comment] 2019-07-03 15:11
@pombredanne : How to deal here in path like https://github.com/nexB/scancode-toolkit/blob/develop/src/commoncode/fileutils.py#L84

**Comment by Abhishek-Dev09** [comment] 2019-07-03 15:27
@jaraco :Does path.py supports macOS mojave encoding also(APFS)?

**Comment by dankegel** [comment] 2019-07-03 20:43
BTW I'm not sure I understand this issue.

Usually it's considered good form for issues to state a problem which can then be solved by a pull request.

Is the problem "scancode uses byte strings, which are no longer supported on python3"?  If so, that should probably be the title of this issue.

**Comment by Abhishek-Dev09** [comment] 2019-07-03 20:49
> BTW I'm not sure I understand this issue.
> 
> Usually it's considered good form for issues to state a problem which can then be solved by a pull request.
> 
> Is the problem "scancode uses byte strings, which are no longer supported on python3"? If so, that should probably be the title of this issue.

No,Problem is that i am not able to get it how to use path.py at here https://github.com/nexB/scancode-toolkit/blob/develop/src/commoncode/fileutils.py#L84 .If you know help me.

**Comment by dankegel** [comment] 2019-07-03 20:53
That's... not a bug in scancode.   That's more like a forum question.

Issue trackers aren't really for personal todo lists, but if you want to use them like that, please make the description clearer.

**Comment by Abhishek-Dev09** [comment] 2019-07-03 20:55
> That's... not a bug in scancode. That's more like a forum question.
> 
> Issue trackers aren't really for personal todo lists, but if you want to use them like that, please make the description clearer.

Thats why i have written, familiarisation of path.py

**Comment by dankegel** [comment] 2019-07-03 21:13
That is a very unclear description.  Maybe something like:

  I don't know how to port src/commoncode/fileutils.py to Path.py

**Comment by Abhishek-Dev09** [comment] 2019-07-03 21:23
> That is a very unclear description. Maybe something like:
> 
> Help... not clear how to port src/commoncode/fileutils.py to Path.py

No, this is not about only this file. I want to how to use ``path.py`` in porting the path.

**Comment by dankegel** [comment] 2019-07-03 21:56
OK, how about

Help... not clear how to port scancode to use Path.py!

which really doesn't sound like something that should be in the issue tracker...?

But hang on, why are you using Path.py?  It dropped python2 support a while ago...

**Comment by Abhishek-Dev09** [comment] 2019-07-03 22:00
pombredanne has said that it supports both python 2 and 3. So, it can manage both version and he had tested with pathlib which doesn't work.

**Comment by Abhishek-Dev09** [comment] 2019-07-03 22:07
> OK, how about
> 
> Help... not clear how to port scancode to use Path.py!
> 
> which really doesn't sound like something that should be in the issue tracker...?
> 
> But hang on, why are you using Path.py? It dropped python2 support a while ago...

It will support python 2 on 11.x series of bugfixes

**Comment by dankegel** [comment] 2019-07-03 22:11
OK.

Sorry to give you a hard time about issue style.  Now that I kind of understand what's going on, how about

  Port path handling to use Path.py

  This is an alternative to #1610

**Comment by Abhishek-Dev09** [comment] 2019-07-03 22:13
> OK.
> 
> Sorry to give you a hard time about issue style. Now that I kind of understand what's going on, how about
> 
> Port path handling to use Path.py
> 
> This is an alternative to #1610

I have already mentioned in description that :  ``This is an extension of #1610``

**Comment by dankegel** [comment] 2019-07-03 22:30
But that was confusing.  It's a completely different direction, not an extension.

Maybe I should just accept that I find the description unclear, and not ask you to clarify it further.

**Comment by Abhishek-Dev09** [comment] 2019-07-03 22:33
> But that was confusing. It's a completely different direction, not an extension.
> 
> Maybe I should just accept that I find the description unclear, and not ask you to clarify it further.

Anyways you know how to use path.py ? If yes, Help me

**Comment by jaraco** [comment] 2019-07-03 23:09
> Does path.py supports macOS mojave encoding also(APFS)?

Yes. Since 2015, I've been developing on macOS with APFS without any issues.

**Comment by pombredanne** [comment] 2019-07-04 08:38
@Abhishek-Dev09 re:

> Does path.py supports macOS mojave encoding also(APFS)?

Since the key is to support os.fsencode/fsdecode, I do not see any reason why this would not work. You could craft a test for that to verify this BUT if this is not the case that will NOT stop us to use path.py ... instead we would work to update path.py to properly support this.

I do not consider macOS 10.14 as a major OS that would be a show stopper for us.

**Comment by pombredanne** [comment] 2022-02-02 08:58
I am closing this for now.

**Closed by pombredanne** 2022-02-02 08:58 UTC
