### ISSUE TITLE
spdx-rdf results in output error

### ISSUE THREAD

**Issue by abuhman** [nexB/scancode-toolkit#633] opened 2017-06-12 16:11 UTC
I am running into this error for the spdx-rdf output type:
'TypeError: must be unicode, not string'

When I run this command, it scans as expected with no errors:
    'sudo scancode --format spdx-tv test.py output.SPDX'
However, this command results in the TypeError above:
    'sudo scancode --format spdx-rdf test.py output.SPDX'

The error appears to happen when ScanCode tries to write to the output file. In fact, if I delete 'output.SPDX' from the command above and allow it to instead send the rdf to standard output, I do not get this error.

**Comment by pombredanne** [comment] 2017-06-13 06:08
@abuhman Thank you for the report.... though I could not reproduce this bug. Can you tell me which file you used for this and which version/commit of ScanCode you used?

**Comment by abuhman** [comment] 2017-06-13 11:46
I downloaded ScanCode from this link:  https://github.com/nexB/scancode-toolkit/archive/v2.0.0.rc2.zip .  While I did originally have this issue when running ScanCode from a file, I also have the same problem when I tried again running the same command directly from the command line, so it shouldn't need the file in order to be reproduced.  

This is the file I ran it from when I first had the issue: https://github.com/spdx/spdx-github/blob/master/run_scan/download_repo_run_scan.py.  This morning I've tried the scancode command from the command line again after typing 'source bin/activate' to make sure the virtual environment is running.  It also results in this error after starting the virtual environment.

**Comment by pombredanne** [comment] 2017-06-13 13:54
@abuhman ok, and which file did you scan? I am trying to know if this is a generic problem or specific to a certain file.

**Comment by abuhman** [comment] 2017-06-13 15:53
Okay, this is the file I scanned:

https://github.com/spdx/spdx-github/blob/master/run_scan/unit_test.py

I am also able to duplicate the error by scanning a local directory that does not contain this file.

**Comment by pombredanne** [comment] 2017-06-13 16:49
@abuhman can you paste the exact error you see here?

**Comment by pombredanne** [comment] 2017-06-13 17:19
@abuhman also ideally, could you contribute a test that fails and reproduces your bug?

**Comment by abuhman** [comment] 2017-06-13 18:10
Traceback (most recent call last):
  File "/usr/local/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit===2.0.0.rc2.post322.a11ef2a', 'console_scripts', 'scancode')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/utils.py", line 76, in main
    standalone_mode=standalone_mode, **extra)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 361, in scancode
    save_results(scanners, only_findings, files_count, results, format, options, input, output_file)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 760, in save_results
    write_formatted_output(scanners, files_count, version, notice, results, format, options, input, output_file, echo_stderr)
  File "/usr/local/lib/python2.7/dist-packages/formattedcode/writers.py", line 222, in write_formatted_output
    output_file.write(str_buffer.getvalue())
TypeError: must be unicode, not str

**Comment by abuhman** [comment] 2017-06-13 18:12
[test.txt](https://github.com/nexB/scancode-toolkit/files/1072433/test.txt)

**Comment by abuhman** [comment] 2017-06-13 18:13
test.txt is a test in Python, but I couldn't upload it as test.py so I changed it to test.txt. It tries to scan itself and fails.

**Comment by pombredanne** [comment] 2017-06-13 21:29
thanks!

**Comment by pombredanne** [comment] 2017-06-16 08:10
@abuhman this is fixed in develop. Thanks for the report!

**Closed** 2017-06-16 08:10 UTC
Labels: bug, GUI and outputs
