### ISSUE TITLE
I can only see the resources displayed as a table instead of a tree.

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#45] opened 2015-07-31 10:38 UTC
I ran: scancode --format html-app samples samples.html on my windows machine.

And the result on my machine only shows table on left resource panel. 
![sample](https://cloud.githubusercontent.com/assets/13014965/9005734/435abfc6-37b3-11e5-9341-dcfe144619e5.png)

**Comment by pombredanne** [comment] 2015-07-31 10:41
This is likely due to using backslashes vs posix paths.

**Comment by pombredanne** [comment] 2015-07-31 10:42
This is a tree alright but not broken down in nodes

**Comment by pombredanne** [comment] 2015-07-31 10:43
The issue is posix path vs. windows path separator on the one hand and also #46 absolute vs. relative path on the other hand

**Comment by pombredanne** [comment] 2015-08-10 16:18
This is fixed now

**Closed by pombredanne** 2015-08-10 16:18 UTC
Labels: bug
