### ISSUE TITLE
Solve appveyor CI failure due to overtime

### ISSUE THREAD

**Issue by all3fox** [nexB/scancode-toolkit#581] opened 2017-03-30 08:26 UTC
Currently, [appveyor builds][1] of `scancode-toolkit` fail because they need more than 60 minutes to complete. And appveyor fails them because that is too long. Need to figure out why or at least fix it.

Here is a project that has some nice (though cryptic) scripts/examples for many CIs, including appveyor:

https://github.com/SethMichaelLarson/python_project_template

[1]: https://ci.appveyor.com/project/nexB/scancode-toolkit

**Comment by pombredanne** [comment] 2017-03-30 15:25
Thanks! This is a bug that I introduced with my fix for #521
I am working on it!

**Comment by pombredanne** [comment] 2017-04-18 22:42
Actually the timeout can only be solved by spawning multiple jobs rather than one big one. That was the settings before. Any reason why this could no longer be the case?

**Comment by pombredanne** [comment] 2017-04-18 22:43
Note that the issue appears also at time on Mac: https://travis-ci.org/nexB/scancode-toolkit/jobs/223258406

**Comment by armijnhemel** [comment] 2017-04-18 23:00
Just out of curiosity: which version of Python is used? I remember seeing KeyErrors with Python's multithreading when there were jobs that would be running for a very long time. I was never able to reproduce the errors, very frustrating. Just search online for 'multiprocessing' and 'KeyError' and it will pop up quite a few hits.

Of course, I am likely wrong in this case (and this is a different issue), but passing around smaller data structures might help.

**Comment by pombredanne** [comment] 2017-04-19 08:26
It sounds like the issue is that coveralls does not support a build matrix where each job is not a full run maybe? https://github.com/lemurheavy/coveralls-public/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20matrix

**Comment by pombredanne** [comment] 2017-04-19 08:31
And this and other comments hint than codecov.io might be the cure. 
https://github.com/lemurheavy/coveralls-public/issues/761#issuecomment-291165622

**Comment by all3fox** [comment] 2017-05-07 16:33
> Just out of curiosity: which version of Python is used?

**Comment by pombredanne** [comment] 2017-05-07 17:21
@all3fox OK. I guess for now that the build pass within the time limits of travis alright. So there is no way to have a list of env variable (e.g. one for each sub test suite) for macosx and another one (the same) copied for Linux? 

Also I do not get why Linux does not show up in the travis config at all? Is there a way to make it explicit.

**Comment by all3fox** [comment] 2017-05-07 17:40
> So there is no way to have a list of env variable (e.g. one for each sub test suite) for macosx and another one (the same) copied for Linux?

**Comment by all3fox** [comment] 2017-05-07 20:35
Nice, I have restored the matrix of environment variables together with the matrix of python versions. See: https://travis-ci.org/all3fox/scancode-toolkit/builds/229749168

However, there is really ugly environment variable duplication. Looks like you cannot get around it if you want to have `matrix: include:`, see: https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs

At the same time, I remembered the exact reason why I got rid of the previous explicit solution:
```
os:
  - osx
  - linux
```

I described it in my commit message 859042ffae0f3a127f3c1da995cfd7758e5f760b but that message is lengthy and somewhat cryptic. It boils down to:

1. If you use the previous approach, you do not explicitly control the python version.
2. If you go with explicit python version (via `language: python` and `python: 2.7.13`), your MacOS builds do not work. So, you have to explicitly include them into the build matrix.
3. Once you start explicitly including them into the matrix, you are forced to duplicate you environment variables.
4. At this point I decided to drop the environment variables completely and run the entire test package at once.

Now that I know that it brings you to time limit, I reverted to code duplication in `.travis.yml`

Tell me what you think, will make a PR in the meantime. Also, will look at `appveyor`.

**Comment by all3fox** [comment] 2017-05-07 21:12
Also, the build I am linking to above ([this one](https://travis-ci.org/all3fox/scancode-toolkit/builds/229749168)) fails on one `osx` machine and I think it is not these `.travis.yml` changes that are causing it.

**Comment by pombredanne** [comment] 2017-05-29 20:31
This is all merged and I disabled coveralls alright.
Thanks!

**Comment by pombredanne** [comment] 2017-05-30 07:37
Actually, the codecode and dev deps should be bundled. Otherwise alternative, newer versions are picked which are shared with scancode at large and are not tested, supported versions and this make some tests fail (e.g. chardet)

**Comment by pombredanne** [comment] 2017-10-20 15:21
This has all been merged in devel!
Thanks!

**Closed by pombredanne** 2017-10-20 15:21 UTC
Labels: bug, core and api
