### ISSUE TITLE
How to ignore binary files ?

### ISSUE THREAD

**Issue by jpopelka** [nexB/scancode-toolkit#689] opened 2017-07-14 17:21 UTC
I've been thinking about how to speed up scans of packages, which contain big binary files.
I [can](https://github.com/fabric8-analytics/fabric8-analytics-worker/blob/master/f8a_worker/workers/license.py#L20) pass patterns to `--ignore` if I know the extensions I want to ignore, but that's tedious, because there's so many of them.
For example [pypi/alfanous](https://pypi.python.org/pypi/alfanous) contains some index with huge binary files with extensions like `dcz`, `pst`, `tiz`, etc.

Also when scancode reaches timeout while scanning such file it returns non-zero exit code, which is not what I want.

So I've been thinking about something like `--ignore-binaries`, which would tell scancode to scan only text files. But I'm not sure if we can reliable detect binary/text files with Python, see.
https://stackoverflow.com/questions/898669/how-can-i-detect-if-a-file-is-binary-non-text-in-python

Ideas ?

**Comment by pombredanne** [comment] 2017-07-14 20:45
Actually all or most of the information needed to detect mostly reliably binary files is available in ScanCode somehow already:
- there is `libmagic` that is bundled and called through a ctypes binding https://github.com/nexB/scancode-toolkit/blob/4e63a6775a895fdec5a3a53f96013399fa34b1b7/src/typecode/magic2.py#L57 
- there is also @audreyr [binaryornot](https://pypi.python.org/pypi/binaryornot/ ) (to which I also [contributed a few lines](https://github.com/audreyr/binaryornot/graphs/contributors)) 
- also the Python `mimetypes` modules has been enhanced to use the more comprehensive Apache magic DB
- and a few more things (detection of extractable archives, PDFs, etc)

All the collected info are eventually aggregated in this `Type` [object](https://github.com/nexB/scancode-toolkit/blob/4e63a6775a895fdec5a3a53f96013399fa34b1b7/src/typecode/contenttype.py#L114) 
For instance the `is_binary` [property](https://github.com/nexB/scancode-toolkit/blob/4e63a6775a895fdec5a3a53f96013399fa34b1b7/src/typecode/contenttype.py#L261) exposes  a flag based on a `binaryornot` call. There is fairly comprehensive test suite that backs these types detection.
 
So doing an `--ignore-binary` should therefore not be very far way. I reckon I have resisted until now because there are use cases where there are really interesting license and origin bits in certain binaries such as in exe, .so and .dll, or Linux kernel modules. But in the vast majority of the cases scanning binaries is not worth it. 

So having an option makes a lot of sense and is a great idea! 
First on binaries but then it could be refined later to exclude some exe or not, media files, etc.
So let's do it!

**Comment by pombredanne** [comment] 2017-07-14 20:51
Checking some quick info on alfanous, it looks like they are reported as `is_binary=True` alright:
```
$ wget https://pypi.python.org/packages/ba/07/bacae5884f8edc4607a2602d35ffae28eff8b0622e6ca51f3551717e6161/alfanous-0.7.28.tar.gz
```
....
2017-07-14 22:44:21 (2.05 MB/s) - ‘alfanous-0.7.28.tar.gz’ saved [9781872/9781872]
```
Extracting:
```
$ extractcode alfanous-0.7.28.tar.gz
Extracting archives...
[####################]                                   
Extracting done.
```
Scanning:

```
$ ./scancode -f json-pp -i alfanous-0.7.28.tar.gz
alfanous-0.7.28.tar.gz          alfanous-0.7.28.tar.gz-extract/ 
(scancode-toolkit-master) pombreda@COMPUTER:~/w421/scancode-toolkit-master$ ./scancode -f json-pp -i alfanous-0.7.28.tar.gz-extract/
Scanning files for: infos with 1 process(es)...
Scanning files...
[####################] 147                                   
Scanning done.
Scan statistics: 147 files scanned in 0s.
Scan options:    infos with 1 process(es).
Scanning speed:  161.96 files per sec.
Scanning time:   0s.
Indexing time:   0s.
Saving results.
...
[...]

    {
      "path": "alfanous-0.7.28.tar.gz-extract/alfanous-0.7.28/indexes/main/_MAIN_1.dcz",
      "type": "file",
      "name": "_MAIN_1.dcz",
      "base_name": "_MAIN_1",
      "extension": ".dcz",
      "date": "2015-06-30",
      "size": 6058915,
      "sha1": "180b2f3a3c977c168528afbb869a525e4032a190",
      "md5": "e1024df2d254f2c3d23c10ed6939cb3a",
      "files_count": null,
      "mime_type": "application/octet-stream",
      "file_type": "data",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "scan_errors": []
    },
...

    {
      "path": "alfanous-0.7.28.tar.gz-extract/alfanous-0.7.28/indexes/main/_SUBJECT_SPELL_1.dcz",
      "type": "file",
      "name": "_SUBJECT_SPELL_1.dcz",
      "base_name": "_SUBJECT_SPELL_1",
      "extension": ".dcz",
      "date": "2015-06-30",
      "size": 43026,
      "sha1": "f26572f6b023182ad82d3876fd9ad1ba454dfc8e",
      "md5": "6980aeaa270ba72842ed9ae585d7e083",
      "files_count": null,
      "mime_type": "application/octet-stream",
      "file_type": "data",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "scan_errors": []
    },
    {
      "path": "alfanous-0.7.28.tar.gz-extract/alfanous-0.7.28/indexes/main/_MAIN_1.pst",
      "type": "file",
      "name": "_MAIN_1.pst",
      "base_name": "_MAIN_1",
      "extension": ".pst",
      "date": "2015-06-30",
      "size": 6579018,
      "sha1": "0b27880e5ba686190b655fd31614df42816ecc36",
      "md5": "7429c70bd0166e0e35f8a9dea24bcbf1",
      "files_count": null,
      "mime_type": "application/octet-stream",
      "file_type": "data",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "scan_errors": []
    },
    {
      "path": "alfanous-0.7.28.tar.gz-extract/alfanous-0.7.28/indexes/main/_MAIN_1.fvz",
      "type": "file",
      "name": "_MAIN_1.fvz",
      "base_name": "_MAIN_1",
      "extension": ".fvz",
      "date": "2015-06-30",
      "size": 227308,
      "sha1": "e3ada83333ea97b440df2c23717e0c598623c7d9",
      "md5": "22802e1c89b966a07647bc5ee76666ed",
      "files_count": null,
      "mime_type": "application/octet-stream",
      "file_type": "raw G3 data, byte-padded",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "scan_errors": []
    },
    {
      "path": "alfanous-0.7.28.tar.gz-extract/alfanous-0.7.28/indexes/main/_MAIN_1.vps",
      "type": "file",
      "name": "_MAIN_1.vps",
      "base_name": "_MAIN_1",
      "extension": ".vps",
      "date": "2015-06-30",
      "size": 1120750,
      "sha1": "35eb62255cdbe3006deb8eb6bf9b3dd0aca27fd5",
      "md5": "9d3eee763772ea91b3b4255e2db22596",
      "files_count": null,
      "mime_type": "application/octet-stream",
      "file_type": "data",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "scan_errors": []
    },
    {
      "path": "alfanous-0.7.28.tar.gz-extract/alfanous-0.7.28/indexes/main/_AYA_SPELL_1.toc",
      "type": "file",
      "name": "_AYA_SPELL_1.toc",
      "base_name": "_AYA_SPELL_1",
      "extension": ".toc",
      "date": "2015-06-30",
      "size": 1482,
      "sha1": "2ef42ce5f1445980ec84387c60eead8eab649541",
      "md5": "8a213955844b1e81a474c376532c601e",
      "files_count": null,
      "mime_type": "application/octet-stream",
      "file_type": "data",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "scan_errors": []
    },
```

**Comment by pombredanne** [comment] 2017-07-30 09:44
See also https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/159

**Comment by pombredanne** [comment] 2017-08-30 09:55
@jpopelka FYI, the latest work by @yashdsaraf in #738 will allow to cleanly create a pre-scan plugin that can ignore things based on on all available file "info" attributes such as the `is_binary` flag

**Comment by jpopelka** [comment] 2017-08-30 11:34
Great news @pombredanne 
Thank you !

**Comment by jpopelka** [comment] 2017-10-06 10:42
I think this can be closed now. I'll try to create the pre-scan plugin and let you know if I hit any issues. Thank you !

**Comment by sschuberth** [comment] 2018-12-03 19:30
@jpopelka is there any update on the actual pre-scan plugin to ignore binary files (based on content / mine-type)?

**Comment by jpopelka** [comment] 2018-12-04 09:20
@sschuberth I've actually never got to creating the plugin and I don't work on that project anymore.

**Comment by pombredanne** [comment] 2018-12-04 10:14
@sschuberth creating a pre-scan plugin for this should be quite straight forward now.
1. this plugin would require the `--info` option
2. in its `process_codebase` method it would walk the codebase and "remove" the resources that are `resource.type == "file" and (resource.is_binary or resource.is_archive or resource.is_media)`  

With this, binaries will not be scanned at all

**Comment by sschuberth** [comment] 2018-12-04 11:44
Thanks for the pointers, @pombredanne. I know this is asking much, but since I'm very short of time currently, is that something you with your expertise of the code base could add for ScanCode 3.0 yourself?

**Comment by pombredanne** [comment] 2018-12-10 15:12
> And could that plugin be triggered by a new --ignore-binaries command line option?
 yes

>  I know this is asking much, but since I'm very short of time currently, is that something you with your expertise of the code base could add for ScanCode 3.0 yourself?

sure, though there is no dependencies on 3.0 there and this could even be released as  its own wheel.

**Comment by sschuberth** [comment] 2018-12-10 15:37
> sure, though there is no dependencies on 3.0 there and this could even be released as its own wheel.

Great, the sooner, the better 😉

**Comment by pombredanne** [comment] 2019-02-13 08:44
@sschuberth #1325 has a simple enough solution. Do you want that one in 3.0? I am cutting a release candidate dubbed `3.0.0` today.

**Comment by sschuberth** [comment] 2019-02-13 08:54
Yes, it would be great to have this in 3.0.0! Thanks @pombredanne!

**Comment by sschuberth** [comment] 2019-03-04 08:17
@pombredanne, is there some sort of regression? With current `develop` (ScanCode version 3.0.2.post1.a7de3052d), the help screen does not list the `--ignore-binaries` option anymore.

**Comment by pombredanne** [comment] 2019-03-05 06:26
@sschuberth my bad: it has never been installed by default but just merged as a plugin and available but not yet installed with the release.

So to get installed in an already configured scancode you would need to:
1. `source bin/activate` (or `bin\activate` on win)
2. if working from a checkout, use then ` pip install -e plugins/scancode-ignore-binaries`
3. OR if working from a download archive use rather `pip install -plugins/scancode-ignore-binaries`

**Comment by sschuberth** [comment] 2019-03-05 15:41
Thanks for the explanation! So should this ticket be closed?

**Comment by pombredanne** [comment] 2019-03-05 15:50
@sschuberth it this works fine for you, I would like to make it a standard installed plugin may be... so I will keep this open

**Comment by pombredanne** [comment] 2022-02-02 07:58
Closing this as this is part of the standard now.

**Closed by pombredanne** 2022-02-02 07:58 UTC
Labels: new feature, file info
