### ISSUE TITLE
Failing to build / configure ScanCode 30.1.0 in Docker with Ubuntu 18.04 "Bionic Beaver"

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#2762] opened 2021-11-19 14:32 UTC
### Description

When building a Docker image for ORT (also see [here](https://github.com/oss-review-toolkit/ort/pull/4721)), we install ScanCode like

    curl -ksSL https://github.com/nexB/scancode-toolkit/archive/v$SCANCODE_VERSION.tar.gz | \
        tar -zxC /usr/local && \
        # Trigger ScanCode configuration for Python 3 and reindex licenses initially.
        PYTHON_EXE=/usr/bin/python3 /usr/local/scancode-toolkit-$SCANCODE_VERSION/scancode --reindex-licenses && \
        chmod -R o=u /usr/local/scancode-toolkit-$SCANCODE_VERSION && \
        ln -s /usr/local/scancode-toolkit-$SCANCODE_VERSION/scancode /usr/local/bin/scancode

with `SCANCODE_VERSION=30.1.0`. During the Docker build process, we're getting

```
#17 196.1 * Configuring ScanCode for first use...
#17 199.3 created virtual environment CPython3.6.9.final.0-64 in 2913ms
#17 199.3   creator CPython3Posix(dest=/usr/local/scancode-toolkit-30.1.0, clear=False, no_vcs_ignore=True, global=False)
#17 199.3   seeder PipInvoke(download=False, pip=embed, setuptools=embed, wheel=embed)
#17 199.3     added seed packages: pip==21.2.3, setuptools==57.4.0, wheel==0.37.0
#17 199.3   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
#17 199.7 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

Any idea what `requirements.txt` file that error message is talking about?

### How To Reproduce

Checkout the [docker-scancode-version](https://github.com/oss-review-toolkit/ort/tree/docker-scancode-version) branch of ORT and run `docker build --build-arg SCANCODE_VERSION=30.1.0 .`.

### System configuration

Docker with `adoptopenjdk:11-jre-hotspot-bionic` base image.

**Comment by pombredanne** [comment] 2021-11-26 09:02
I was not able to reproduce with the latest version.
But you seem to be using https://github.com/oss-review-toolkit/ort/pull/4721/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R29 an older version?

https://github.com/nexB/scancode-toolkit/archive/v$SCANCODE_VERSION.tar.gz would be the GitHub source archive... I would not recommend to use this:
1. it contains all the tests and is super large
2. it does not contain the tested dependencies
3. it does not contain the license index

Instead you should use of the tar.xz release archives:
1. it does not contain all the tests and is slimmer
2. it does contain the exact needed subset of the dependencies which have been tested
3. it does contain a prebuilt license index and you do not need to `--reindex-licenses` ... a mere `./scancode -h` for a first configuration run would be enough

**Comment by fb33** [comment] 2021-11-29 10:46
Hello,

I've got the same error after updating my ORT dockerfile to use tar.xz.
```
11:40:08  #18 90.55 https://github.com/nexB/scancode-toolkit/releases/download/v30.1.0/scancode-toolkit-30.1.0_py36-linux.tar.xz
11:40:21  #18 101.6 * Configuring ScanCode for first use...
11:40:26  #18 107.4 created virtual environment CPython3.6.9.final.0-64 in 5132ms
11:40:26  #18 107.4   creator CPython3Posix(dest=/usr/local/scancode-toolkit-30.1.0, clear=False, no_vcs_ignore=True, global=False)
11:40:26  #18 107.4   seeder PipInvoke(download=False, pip=embed, setuptools=embed, wheel=embed)
11:40:26  #18 107.4     added seed packages: pip==21.2.3, setuptools==57.4.0, wheel==0.37.0
11:40:26  #18 107.4   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
11:40:26  #18 107.9 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by fb33** [comment] 2021-11-29 15:19
For info : 
I tried ORT dockerfile with these versions :
- https://github.com/nexB/scancode-toolkit/releases/download/v30.1.0/scancode-toolkit-30.1.0_py36-linux.tar.xz : ❌
- https://github.com/nexB/scancode-toolkit/releases/download/v30.0.0/scancode-toolkit-30.0.0_py36-linux.tar.xz : ❌
- https://github.com/nexB/scancode-toolkit/releases/download/v21.8.4/scancode-toolkit-21.8.4_py36-linux.tar.xz : ❌
- https://github.com/nexB/scancode-toolkit/releases/download/v21.7.30/scancode-toolkit-21.7.30_py36-linux.tar.xz : ❌
- https://github.com/nexB/scancode-toolkit/releases/download/v21.6.7/scancode-toolkit-21.6.7_py36-linux.tar.xz : ❌
- https://github.com/nexB/scancode-toolkit/releases/download/v21.3.31/scancode-toolkit-21.3.31_py36-linux.tar.xz : ✔️ 🥇

**Comment by pombredanne** [comment] 2021-11-29 15:22
@fb33 @sschuberth 
I was able to reproduce:
```
/home/pombreda/tmp/sc/scancode-toolkit-30.1.0/scancode -h --verbose
* Configuring ScanCode for first use...
created virtual environment CPython3.6.10.final.0-64 in 2344ms
  creator CPython3Posix(dest=/home/pombreda/tmp/sc/scancode-toolkit-30.1.0, clear=False, no_vcs_ignore=True, global=False)
  seeder PipInvoke(download=False, pip=embed, setuptools=embed, wheel=embed)
    added seed packages: pip==21.2.3, setuptools==57.4.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```
The culprit and bug is that the paths in https://github.com/nexB/scancode-toolkit/blob/1fdf40faabc0cf91fb3e7e8ff11412fcfb358577/configure#L29 are not fully qualified and interpreted as local to the current working directory

**The short term workaround is to `cd` to the installation directory before the first invocation. This would be needed only once for the first run.**

e.g. likely something more or less like this for a Python 3.6:
```
curl -ksSL https://github.com/nexB/scancode-toolkit/releases/download/v$SCANCODE_VERSION/scancode-toolkit-$SCANCODE_VERSION_py36-linux.tar.xz | \
    tar -xC /usr/local && \
    # Trigger ScanCode configuration for Python 3.6
    cd /usr/local/scancode-toolkit-$SCANCODE_VERSION && \
    PYTHON_EXE=/usr/bin/python3.6 /usr/local/scancode-toolkit-$SCANCODE_VERSION/scancode --help && \
    chmod -R o=u /usr/local/scancode-toolkit-$SCANCODE_VERSION && \
    ln -s /usr/local/scancode-toolkit-$SCANCODE_VERSION/scancode /usr/local/bin/scancode
```

**Comment by fb33** [comment] 2021-11-29 15:46
Thanks, the workaround works fine !

**Comment by pombredanne** [comment] 2021-11-29 15:54
@fb33 great.. I will push a fix in the next release. :+1:

**Comment by pombredanne** [comment] 2022-08-17 21:49
The latest Dockerfile at https://github.com/nexB/scancode-toolkit/commit/73a1452926bce10460564fc8c820d33f46b9f38a can be used as a blueprint.
Alternatively I recommend using the application archives or the released PyPI wheels.
I am closing this now. But please reopen if you think this is still an issue!

**Closed as completed by pombredanne** 2022-08-17 21:49 UTC
Labels: bug, os support, installation and packaging
