### ISSUE TITLE
Add instructions how to set up ScanCode for debugging in an IDE

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#457] opened 2017-01-17 09:13 UTC
It would be great if either the [README](https://github.com/nexB/scancode-toolkit/blob/develop/README.rst) or [Wiki](https://github.com/nexB/scancode-toolkit/wiki) would include instructions on how to set up an IDE (like PyCharm / IntelliJ IDEA, Visual Studio Code etc.) for debugging ScanCode. I've tried various approaches, but "something" always seems to be wrong, like the IDE not properly stopping at breakpoints, or statements until the next breakpoint being skipped when doing "Step Over".

**Comment by pombredanne** [comment] 2017-01-17 10:01
That's a great idea. I use an IDE but mostly as a glorified text editor (this is Eclipse + Pydev ...  I used to be an active committer at Eclipse.org in another life). I sometimes dabble with Pycharm.

I can try to help a bit but I have not used debugging in Python in ages. I personally tend to prefer focused tracing with logging and printing and a lot of unit tests of smaller functions rather than debugging.

The thing to setup and IDE and a debugger correctly are likely around making sure that your IDE understands the structure of the project, where the sources files are and eventually what Python interpreter to use (beside using an actual debugging library).

In particular, I would:
1. ensure that `./configure` has been run at least once
2. setup the IDE so that it recognizes where the root of source code paths are:   e.g. `<project root>/src` and `<project root>/tests` primarily
3. setup the IDE so that it recognizes where the standard Python library and installed third-party packages are :  this would be on `<project root>/lib/python2.7/site-packages/` on Linux and Mac and on `<project root>/lib/site-packages/` on Windows ( where the case for 'lib' does not matter on Windows).
4. setup the IDE so that it recognizes where the standard Python interpreter is:  this would be on `<project root>/bin/python` . On windows, `<project root>/bin/python.exe` may be needed. ( or `Scripts` though the configure script creates an NTFS junction on Windows to bin, so the paths are the same on all OSes).
5. If needed and the IDE is `virtualenv` aware, there may be settings to point to where the root of the environment is and this would be the `<project_root>` and it may need to know where the activate scripts is under bin.
6. optionally inform the IDE on how to run tests with py.test and may be how to launch stuffs based on the path above.

With these, (and possibly a debugging library pip-installed from the shell in the activated environment) , I would assume that an IDE has everything it needs to introspection, compilation, content assistance and debugging...  

I would likely focus on debugging a test function run rather than a full command line run which would be more complex and this has the added benefit to eventually force some refactoring to have testable and individually runnable functions.

What is your IDE of choice? and what are you trying to debug?

**Comment by sschuberth** [comment] 2017-01-17 10:10
> What is your IDE of choice?

I recently started to play around with [Visual Studio Code](https://code.visualstudio.com/docs/languages/python), and so far I like it quite a bit.

> and what are you trying to debug?

I was coming across a strange issue where I ran ScanCode on a single `__init__.py` file for testing. It turned out that when scanning this single file, the cache did not have a `sha1` calculated for the file, and SPDX output crashed as it relies on the `sha1` being already calculated. I'm right now adding some fallback code to again calculate a file's SHA1 if for some reason it's not present in the cache. But my understanding is that the `sha1` key *should* always be there, right?

**Comment by pombredanne** [comment] 2017-01-17 12:55
Actually we return `None` as a hash for an empty content/file.
This is because there is a lot of emptyness out there.... Search on google these checksums:
```
      "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
      "md5": "d41d8cd98f00b204e9800998ecf8427e",
```
.... you get a million or more results: https://www.google.com/search?q=da39a3ee5e6b4b0d3255bfef95601890afd80709

So here https://github.com/nexB/scancode-toolkit/blob/2cc515a413b12ae2adf03ef1c823e4cfc93ee3b5/src/commoncode/hash.py#L52
` self.h = msg and hmodule(msg).digest()[:self.digest_size] or None`
the  `msg and ` is a shortcut that will not execute the things after `and` if the `msg` is empty e.g. an empty file.

The issue is that a checksum is meant for reasonably accurate file identification and for instance @majurg is working on a tool to compute deltas between scans... Returning as identical any empty file does not make sense in this and many other use cases. It yield eventually a combinatorial explosion of matching files as nothing resembles void more than void.

On the VSCode side, @JonoYang I think you use this, are you? Would you have any tips for @sschuberth ?

**Comment by sschuberth** [comment] 2017-01-17 13:05
> Returning as identical any empty file does not make sense in this and many other use cases.

I'm actually not sure about that assertion. For the sake of identifying already scanned content to generate delta scans, you might also want to be able to identify e.g. copies of the same file in a project, or even across different projects. As same content produces same scan results, it *does* make sense to uniquely identify file content by hash, and that includes empty files (as all scans of empty files would generate the same, empty, result).

> On the VSCode side [...]

@JonoYang Currently my problem is that sometimes debugging just fails with "Debug adapter process has terminated unexpectedly".

**Comment by JonoYang** [comment] 2017-01-20 20:42
@sschuberth Sorry for the late reply. I have to admit that I do not have much experience with the Python debugging functionality in VS Code.

**Comment by haikoschol** [comment] 2017-11-17 15:00
I tried the latest version of VSCode (1.18) and got it mostly working. The only thing that does not work is stepping over and into functions. But I don't see the issue mentioned by @sschuberth. That one might be Windows specific though, I only tested on Linux so far. I've documented the steps to set up debugging tests in ScanCode in this gist: https://gist.github.com/haikoschol/a36a0f164558ab30b416ee26bbd40daa

@pombredanne @JonoYang Do you want to add this to the wiki or the scancode repo?

**Comment by pombredanne** [comment] 2017-11-17 15:12
@haikoschol that's awesome! I shall say that I am rather at loss when it comes to debugging and IDE as I am rather old school there. I guess I only ever fired a Python debugger once and I may be missing out cool tools :|

Please go ahead and add a wiki page: If you are not authorized, tell me  and I will send you a proper invite

**Comment by sschuberth** [comment] 2017-11-17 15:17
@pombredanne Any objections to actually add the `.vscode/settings.json` file to the repo? @haikoschol can probably file a PR accordingly.

**Comment by sschuberth** [comment] 2017-11-17 15:20
@haikoschol The instructions should probably say that you need to manually run `./configure` once before, otherwise `"${workspaceRoot}/bin/python"` is not available.

**Comment by sschuberth** [comment] 2017-11-17 15:25
@haikoschol Also, you'd probably want to create a `.vscode/launch.json` file, too.

**Comment by pombredanne** [comment] 2017-11-17 15:31
@sschuberth actually I would rather prefer not having IDE-specific things at the root.
One thing that could be done though:
1. add a root entry to ignore at the roor .vscode .gitignore
2. add the json file under `/etc`
3. add a configure script under `etc/conf/dev` that will copy `/.vscode/settings.json` in the root

That way this is not in the way at the root but is configured and available when you are in dev

**Comment by haikoschol** [comment] 2017-11-17 15:33
@sschuberth Yes, I should include something about setting up the virtualenv. But maybe reference the existing docs on that instead of repeating the instructions, so they don't go out of sync.

I'm not sure about `.vscode/launch.json`. When I just tried it with the latest version, there was no need to create a launch configuration and VSCode also didn't create that file itself in the workspace dir.

I agree with @pombredanne to not include `.vscode` directly (same for `.idea` etc.), since it might contain user-specific settings.

**Comment by sschuberth** [comment] 2017-11-17 15:34
I don't that's worth the effort. @haikoschol, no need to file a PR then from my side.

PS: `.vscode` [is already ignored](https://github.com/nexB/scancode-toolkit/blob/develop/.gitignore#L46).

**Comment by pombredanne** [comment] 2017-11-17 15:40
FWIW the patch is rather minimal, but your call:

```
diff --git a/etc/conf/dev/base.py b/etc/conf/dev/base.py
index 31c5fa3..46e4c2e 100644
--- a/etc/conf/dev/base.py
+++ b/etc/conf/dev/base.py
@@ -17,4 +17,19 @@
         sdm.write('This is a tag file to notify that ScanCode is used in development mode.')
 
 
+def setup_vscode():
+    """
+    Add base settings for .vscode
+    """
+    from scancode import root_dir
+    from commoncode.fileutils import create_dir
+    from commoncode.fileutils import copyfile
+
+    vscode = os.path.join(root_dir, '.vscode')
+    create_dir(vscode)
+    if os.path.exists('settings.json'):
+        copyfile('settings.json', vscode)
+
+
 setup_dev_mode()
+setup_vscode()
```

**Comment by haikoschol** [comment] 2017-11-17 17:02
[PR was merged](https://github.com/nexB/scancode-toolkit/pull/846) and wiki page created at https://github.com/nexB/scancode-toolkit/wiki/IDE-Configuration

I think this issue can be closed.

**Comment by pombredanne** [comment] 2017-11-17 18:49
Thank you!

**Closed by pombredanne** 2017-11-17 18:49 UTC
Labels: documentation, help wanted
