### ISSUE TITLE
False positive: sun-bsd-no-nuclear

### ISSUE THREAD

**Issue by sutula** [nexB/scancode-toolkit#2533] opened 2021-05-25 01:20 UTC
### Description

License type sun-bsd-no-nuclear is detected instead of a more correct BSD 3-clause license

### How To Reproduce

Source file: https://archive.softwareheritage.org/browse/content/sha1_git:152044fdb0e884d04ea9efb4df809a01484f6461/raw/
Running current master code yields:
          "key": "sun-bsd-no-nuclear",
          "score": 88.54,
          ...
          "start_line": 5,
          "end_line": 32,
          "matched_rule": {
            "identifier": "sun-bsd-no-nuclear_3.RULE",
            "license_expression": "sun-bsd-no-nuclear",
            "licenses": [
              "sun-bsd-no-nuclear"
           ],

The actual license is a 3-clause BSD license, (C) Sun.  It is definitely *not* the no-nuclear version.  The rest of this report is my guessing:

I see that the sun-no-nuclear license was added mid 2020.  It definitely makes sense to add this license, since there are unique restrictions in the text.  Another Sun license was added at about the same time.  However, I'm guessing that an unexpected consequence of adding it was that a license such as this example, which used to be detected as a BSD 3-clause license, is now closer-matched by this unique license.  So this implies that adding the sun-bsd-no-nuclear license has regressed the ability to detect normal bsd-3 licenses (C) Sun.

I would propose a patch, but am not experienced enough at the best solution.  Certainly, adding a "sun-bsd" license type that matches this text better than the current match (89%) is an option, but this leads to a proliferation of licenses.  Is there a way to insist that the "no-nuclear" license require at least the word "nuclear" in the matched text?

Leaving the solution to the developers, but I'm willing to help.

**Comment by pombredanne** [comment] 2021-05-26 07:05
@sutula Thanks!
It is interesting that you used an SWH link. I like that!
Here someone took mostly the text of the  `sun-bsd-no-nuclear` and stripped it from its trailing nuclear clause.
The root cause of the issue is that the `sun-bsd-no-nuclear` should not be matched unless we have a very high coverage as it otherwise would be confused for a plain 3-clause BSD. 

The solution is IMHO:
- boosting the minimum coverage of a few rules at play e.g. the minimum percentage (in number of words) that must be matched for a detection to be relevant for a rules related to the `sun-bsd-no-nuclear` such that it would not prevail over a  plain BSD unless it is mostly matched
- adding a few new rules (and not a new license) that would be for the plain BSD variant used here.

Let me push a few commits that do that and you can check these out as an example.


You asked also:

>  Is there a way to insist that the "no-nuclear" license require at least the word "nuclear" in the matched text?

Actually no, since we really do massive diffing and pattern matching that is not specific to any license. We also have a list of legalese words that is generics (and nuclear is part of this) .. yet this could be a an enhancement for the future, e.g. add a few must have words attached to a license. Though some part of me cringes at the initial curation and maintenance effort when this may be needed only a few rare cases and the fact that this may be a rare case.


FWIW, the full details of the matches are here (mildly edited for wrapping the matched text. In the matched text you can see the parts not matched in [square] brackets because I used the `--license-text` and `--license-text-diagnostics` options.

```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "21.3.31",
      "options": {
        "input": [
          "bsd/sha1_git_152044fdb0e884d04ea9efb4df809a01484f6461"
        ],
        "--json-pp": "-",
        "--license": true,
        "--license-text": true,
        "--license-text-diagnostics": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2021-05-25T182832.801156",
      "end_timestamp": "2021-05-25T182915.134320",
      "duration": 42.33317708969116,
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "sha1_git_152044fdb0e884d04ea9efb4df809a01484f6461",
      "type": "file",
      "licenses": [
        {
          "key": "sun-bsd-no-nuclear",
          "score": 88.54,
          "name": "Sun BSD-Style with Nuclear Restrictions",
          "short_name": "Sun BSD-Style with Nuclear Restrictions",
          "category": "Free Restricted",
          "is_exception": false,
          "owner": "Oracle (Sun)",
          "homepage_url": null,
          "text_url": "",
          "reference_url": "https://scancode-licensedb.aboutcode.org/sun-bsd-no-nuclear",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/sun-bsd-no-nuclear.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/sun-bsd-no-nuclear.yml",
          "spdx_license_key": "BSD-3-Clause-No-Nuclear-License",
          "spdx_url": "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License",
          "start_line": 5,
          "end_line": 32,
          "matched_rule": {
            "identifier": "sun-bsd-no-nuclear_3.RULE",
            "license_expression": "sun-bsd-no-nuclear",
            "licenses": [
              "sun-bsd-no-nuclear"
            ],
            "is_license_text": true,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "3-seq",
            "rule_length": 246,
            "matched_length": 220,
            "match_coverage": 89.43,
            "rule_relevance": 99
          },

          "matched_text": "Redistribution and use in source and binary forms, with or without\n
 * modification, are permitted provided that the following conditions\n
 * are met:\n\n
*\n
 * [1]. Redistributions of source code must retain the above copyright\n
 *    notice, this list of conditions and the following disclaimer.\n
 *\n
 * [2]. [Redistributions] in binary form must [reproduce] the above copyright\n
 *    notice, this list of conditions and the following disclaimer in the\n
 *    documentation and/or other materials provided with the distribution.\n
 *\n
 * [3]. Neither the name of Sun Microsystems, Inc. [nor] the names of\n
 *    contributors may be used to endorse or promote products derived from\n
 *    this software without specific prior written permission.\n
 *\n
 * This software is provided \"AS IS,\" without a warranty of any kind.\n
 *\n
 * ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES,\n
 * INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A\n
 * PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED.\n
 * SUN AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES OR\n
 * LIABILITIES SUFFERED BY LICENSEE AS A RESULT OF OR RELATING TO USE,\n
 * MODIFICATION OR DISTRIBUTION OF THE SOFTWARE OR ITS DERIVATIVES.\n
 * IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE,\n
 * PROFIT OR DATA, OR FOR DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL,\n
 * INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE\n
 * THEORY OF LIABILITY, ARISING OUT OF THE USE OF OR INABILITY TO USE\n
 * SOFTWARE, EVEN IF SUN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES."        }
      ],
      "license_expressions": [
        "sun-bsd-no-nuclear"
      ],
      "percentage_of_license_text": 39.57,
      "scan_errors": []
    }
  ]
}

```

**Comment by pombredanne** [comment] 2021-05-26 22:20
The commits above have landed in develop. Feedback mucho appreciated!

**Comment by pombredanne** [comment] 2021-08-19 16:10
This is now fixed and released. Closing.
Thank you again for the report. Send us more of these!

**Closed as completed by pombredanne** 2021-08-19 16:10 UTC
Labels: bug, license scan, fixed pending review
