### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#382] opened 2016-11-30 15:53 UTC
I have the following 2 files in a directory: `hadoop-2.7.3.tar.gz` and `hadoop-2.7.3-src.tar.gz`.
Only the hadoop-2.7.3.tar.gz-extract exist after launched the `extractcode`, nothing is performed for the hadoop-2.7.3-src.tar.gz.

In addition, I have the following error messages:
```
ERROR extracting: C:/Users/CYL/Downloads/hadoop/tmp/hadoop-2.7.3.tar.gz-extract/hadoop-2.7.3/share/hadoop/yarn/sources/hadoop-yarn-server-resourcemanager-2.7.3-sources.jar: '[(\'c:\\\\users\\\\cyl\\\\appdata\\\\local\\\\temp\\\\scancode_cyl\\\\extract\\\\w5wadq\\\\org\\\\apache\\\\hadoop\\\\yarn\\\\server\\\\resourcemanager\\\\monitor\\\\capacity\\\\ProportionalCapacityPreemptionPolicy.java\', \'C:\\\\Users\\\\CYL\\\\Downloads\\\\hadoop\\\\tmp\\\\hadoop-2.7.3.tar.gz-extract\\\\hadoop-2.7.3\\\\share\\\\hadoop\\\\yarn\\\\sources\\\\hadoop-yarn-server-resourcemanager-2.7.3-sources.jar-extract\\\\org\\\\apache\\\\hadoop\\\\yarn\\\\server\\\\resourcemanager\\\\monitor\\\\capacity\\\\ProportionalCapacityPreemptionPolicy.java\', "[Errno 2] No such file or directory: \'C:\\\\\\\\Users\\\\\\\\CYL\\\\\\\\Downloads\\\\\\\\hadoop\\\\\\\\tmp\\\\\\\\hadoop-2.7.3.tar.gz-extract\\\\\\\\hadoop-2.7.3\\\\\\\\share\\\\\\\\hadoop\\\\\\\\yarn\\\\\\\\sources\\\\\\\\hadoop-yarn-server-resourcemanager-2.7.3-sources.jar-extract\\\\\\\\org\\\\\\\\apache\\\\\\\\hadoop\\\\\\\\yarn\\\\\\\\server\\\\\\\\resourcemanager\\\\\\\\monitor\\\\\\\\capacity\\\\\\\\ProportionalCapacityPreemptionPolicy.java\'"), (\'c:\\\\users\\\\cyl\\\\appdata\\\\local\\\\temp\\\\scancode_cyl\\\\extract\\\\w5wadq\\\\org\\\\apache\\\\hadoop\\\\yarn\\\\server\\\\resourcemanager\\\\recovery\\\\records\\\\impl\\\\pb\\\\AMRMTokenSecretManagerStatePBImpl.java\', \'C:\\\\Users\\\\CYL\\\\Downloads\\\\hadoop\\\\tmp\\\\hadoop-2.7.3.tar.gz-extract\\\\hadoop-2.7.3\\\\share\\\\hadoop\\\\yarn\\\\sources\\\\hadoop-yarn-server-resourcemanager-2.7.3-sources.jar-extract\\\\org\\\\apache\\\\hadoop\\\\yarn\\\\server\\\\resourcemanager\\\\recovery\\\\records\\\\impl\\\\pb\\\\AMRMTokenSecretManagerStatePBImpl.java\', 
...
```

The archives were downloaded from
https://archive.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3-src.tar.gz
https://archive.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3tar.gz

**Comment by pombredanne** [comment] 2016-12-10 11:20
@chinyeungli Sorry it took me a while to get back on this!
I ran extractcode on the two hadoop archives and then I ran a manual extract with a combo of tar, unzip, bunzip2 and gunzip to reproduce a similar extracted tree. I then ran a diff --brief -r on the two extracted trees.
Except for the slight differences in behavior the extracted  trees where the same ... (e.g. extractcode extracts more and there are some files not skipped like links and few small differences in which subdirectories are created.
Now I did run this on Linux and not on Windows though I will try it next.

**Comment by kira0204** [comment] 2017-03-10 17:32
I ran the extractcode on linux too, the extraction took place smoothly. Will try on windows next

**Comment by pombredanne** [comment] 2017-03-10 18:11
@kira0204 thanks.

**Comment by pombredanne** [comment] 2017-06-16 13:52
@kira0204 were you able to test it on Windows too?

**Comment by kira0204** [comment] 2017-08-24 21:10
@pombredanne Apologies, I got busy. I just started the extraction and will notify as soon it is done.

**Comment by pombredanne** [comment] 2017-08-24 21:39
@kira0204 no problem, and thank you for not dropping the ball entirely!

**Comment by kira0204** [comment] 2017-08-24 22:40
The extraction took place without any errors, although manual extraction is left so as to verify whether both the extraction are similar or not.

**Comment by kira0204** [comment] 2017-08-24 23:55
Both the trees look similar except from the .sh files that manual extraction did not take care of. However I found few .java files missing in the extracted files by scancode, should I send you the output trees?

**Comment by kira0204** [comment] 2017-09-22 03:03
@pombredanne Let's close this issue?

**Comment by pombredanne** [comment] 2017-09-22 03:22
@kira0204 sorry for the latest reply. Yes, if you can then the output trees that would be great!

**Comment by kira0204** [comment] 2017-09-25 21:37
[diff.txt](https://github.com/nexB/scancode-toolkit/files/1331024/diff.txt)
[manual-tree.txt](https://github.com/nexB/scancode-toolkit/files/1331025/manual-tree.txt)
[tree.txt](https://github.com/nexB/scancode-toolkit/files/1331026/tree.txt)

**Comment by kira0204** [comment] 2017-09-30 07:56
@pombredanne

**Comment by pombredanne** [comment] 2017-10-02 01:29
So I ran a seide-by-side extract test on Windows. The issue there is is the same as #749
The paths to the temp directory (that can be set to a shorter path dir with `set SCANCODE_TMP=<alternate temp dir>` exceeds the Windows maximum.... and this is eventually due to the path of the hadoop archive to be too deep for Windows .

This explains the issues of discrepancies and the errors.

Solution: 1. use shorter paths, and shoter temp dir paths and 2. use UNC paths for extracting (and later scanning) as per #749

I am closing this ticket in favor of #749 and will ping participants to this ticket there

**Closed by pombredanne** 2017-10-02 01:29 UTC
Labels: archive extraction, bug, easy
