### ISSUE TITLE
Mac install problem: conflicting dependencies

### ISSUE THREAD

**Issue by lucasgonze** [nexB/scancode-toolkit#2808] opened 2022-01-24 19:12 UTC
### Description

configure script throws error:

> Cannot install scancode-toolkit==30.1.0 because these package versions have conflicting dependencies.
```

The conflict is caused by:
    scancode-toolkit 30.1.0 depends on lxml<5.0.0 and >=4.6.3
    The user requested (constraint) lxml==4.6.3
```

![image](https://user-images.githubusercontent.com/111581/150848760-0ab35890-12e0-4ec0-a5b8-068e5b683584.png)

### How To Reproduce

See 
[log.txt](https://github.com/nexB/scancode-toolkit/files/7928196/log.txt)

1. Download "scancode-toolkit-30.1.0" (latest at this moment). 
2. Unpack tarball, cd into it
3. vi PYTHON_EXECUTABLE and set python version (in my case `python` means Python 3.9.9)
4. ./scancode --help
5. Get error "ERROR: Cannot install scancode-toolkit==30.1.0 because these package versions have conflicting dependencies."

### System configuration

Mac OS X Monterey v12.1

scancode-toolkit-30.1.0

Python 3.9.9

Installation method: downloaded scancode-toolkit-30.1.0_py36-macos.tar.xz

**Comment by pombredanne** [comment] 2022-01-24 22:10
Thank for the report . Sorry for this bug!
There is likely some heisenbug-like condition in Python pip which I am tracking down.... Unless this is a macOS 12 issue? or just a macOS issue.
This is really weird as I just tracked a similar issue on macOS 11 on Friday with @DennisClark

**Comment by pombredanne** [comment] 2022-01-24 22:15
I was just filling this https://github.com/pypa/pip/issues/10824

**Comment by lucasgonze** [comment] 2022-01-25 01:05
It might be related that the system I'm using is noticeably slow. It's a 2017 Air running Monterey and Docker. This tends to trigger race conditions. 

So try running something which overloads your hardware.

**Comment by DennisClark** [comment] 2022-01-25 01:27
I have encountered the same problem on a MacBook Pro (16-inch, 2019) with a 2.6 GHz 6-Core Intel Core I7, and 16 GB RAM.

**Comment by pombredanne** [comment] 2022-01-25 17:27
@DennisClark Thanks

@lucasgonze the short term workaround should be this, once the `./scancode --help` above failed:
1. run `source bin/activate`
2. run `pip install --editable .`
(This will fetch wheels live from PyPI though)

**Comment by DennisClark** [comment] 2022-01-25 17:57
@pombredanne   i confirmed that the short term workaround is helpful in my installation, thanks.  And it means that I can now report other issues  :-)

**Comment by lucasgonze** [comment] 2022-01-25 19:02
> @pombredanne i confirmed that the short term workaround is helpful in my installation, thanks. And it means that I can now report other issues :-)

Ditto. Ibid. What he said.

**Comment by pombredanne** [comment] 2022-01-25 22:23
@lucasgonze I want to keep this open until we have a proper fix with pip

**Comment by usmankhanisb** [comment] 2022-06-28 12:08
I tried it is not working for me . @pombredanne 

<img width="421" alt="image" src="https://user-images.githubusercontent.com/39516394/176174942-6864cafb-d91f-460c-b401-be851dacf7d7.png">
earlier the error was at the end of installation as 

ERROR [6/6] RUN ./scancode --reindex-licenses                                                                          19.8s 
------                                                                                                                           
 > [6/6] RUN ./scancode --reindex-licenses:                                                                                      
#11 0.212 * Configuring ScanCode for first use...                                                                                
#11 19.45 ERROR: Cannot install scancode-toolkit[packages]==31.0.0rc2 because these package versions have conflicting dependencies.
#11 19.45 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
------
executor failed running [/bin/sh -c ./scancode --reindex-licenses]: exit code: 1

**Comment by usmankhanisb** [comment] 2022-06-28 13:22
> * `source bin/activate`

there is no source directory , I user docker installation instruction , running on MAC

**Comment by pombredanne** [comment] 2022-08-17 13:05
This is solved in https://github.com/nexB/scancode-toolkit/pull/3053 and will be released with v31.
Thanks!

**Closed as completed by pombredanne** 2022-08-17 13:05 UTC
Labels: bug, must have, os support, installation and packaging

**Comment by swastkk** [comment] 2024-04-22 21:00
Getting this error 
```
ERROR: Could not find a version that satisfies the requirement extractcode-7z>=16.5.210525; extra == "full" (from extractcode[full]) (from versions: none)
ERROR: No matching distribution found for extractcode-7z>=16.5.210525; extra == "full"
```
### System configuration
macOS 14.4.1 23E224 arm64

scancode-toolkit-32.1.0

Python 3.12.2

Installed via cloning scancode-toolkit with --depth=1

**Comment by pombredanne** [comment] 2024-04-24 17:03
@swastkk can you move this comment to a new issue? Your issue is likely different. You may also need to run in rosetta x86 mode?

**Comment by swastkk** [comment] 2024-04-24 17:14
> @swastkk can you move this comment to a new issue? Your issue is likely different. You may also need to run in rosetta x86 mode?

Ya sure, :")
