### ISSUE TITLE
Error while executing configure script. 

### ISSUE THREAD

**Issue by kartiksibal** [nexB/scancode-toolkit#574] opened 2017-03-26 19:10 UTC
The configure script when executed on the stable version of ScanCode seems to encounter an error.

Log: 

```
Installing collected packages: scancode-toolkit

  Running setup.py develop for scancode-toolkit

Successfully installed scancode-toolkit-2.0.0rc2

Ignoring indexes: https://pypi.python.org/simple

Collecting apipkg (from -r /home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt (line 2))

  Could not find a version that satisfies the requirement apipkg (from -r /home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt (line 2)) (from versions: )

No matching distribution found for apipkg (from -r /home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt (line 2))

Failed to execute command:
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --find-links="/home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/thirdparty/base" --find-links="/home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/thirdparty/prod" -r "/home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt". Aborting...
```
OS: Ubuntu 16.10 Yakety Yak
ScanCode Ver: 2.0.0rc2
 Python Version: 2.7.10

Log: 

```
Installing collected packages: scancode-toolkit

  Running setup.py develop for scancode-toolkit

Successfully installed scancode-toolkit-2.0.0rc2

Ignoring indexes: https://pypi.python.org/simple

Collecting apipkg (from -r /home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt (line 2))

  Could not find a version that satisfies the requirement apipkg (from -r /home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt (line 2)) (from versions: )

No matching distribution found for apipkg (from -r /home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt (line 2))

Failed to execute command:
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --find-links="/home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/thirdparty/base" --find-links="/home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/thirdparty/prod" -r "/home/kartik/Desktop/scancode/scancode-toolkit-2.0.0rc2/etc/conf/dev/base.txt". Aborting...
```
OS: macOS Sierra 10.12
ScanCode Ver: 2.0.0rc2
Python Version: 2.7.10

Another Mac, Similar specs, exactly similar log.

The error seems to occur while the script tries to check for essential dependencies, after installing ScanCode. 

PS: The script works fine on the dev version of ScanCode.

**Comment by kartiksibal** [comment] 2017-03-26 21:03
@pombredanne Why does the configure script on the stable ver, ignore indexes from `pypi.python.org/simple` ?

**Comment by pombredanne** [comment] 2017-03-27 03:07
@kartiksibal Thanks for the report. Do you mind to paste text rather than images? Images are OK for web pages screenshot but not great otherwise for console related things.

The fact to fetch only deps locally is by design and to avoid having dependencies fetched from the network by default.

**Comment by kartiksibal** [comment] 2017-03-27 05:09
@pombredanne I have added a paste, rather than raw log. It wasn't looking neat. If you prefer, should i post the raw log?

**Comment by kartiksibal** [comment] 2017-03-27 05:14
@pombredanne I tried to trace the flow of control and the only difference b/w the execution on the stable version and the dev version, is the dev version is _not_ ignoring indexes from the python repo. Whereas the script on stable version.

**Comment by pombredanne** [comment] 2017-03-27 06:50
@kartiksibal can you confirm you are trying to install from the 2.0.0rc2 tag and not from develop?
If this works OK in develop then this is a non-issue.

@JonoYang @johnmhoran You run Ubuntu 16.x  may be? do you experience any of these issues?

**Comment by JonoYang** [comment] 2017-03-27 18:48
@kartiksibal I can confirm that the configure script does not work on the 2.0.0rc2 release, but it works in develop. For now, use the develop branch. This will be fixed in the next release.

**Closed by JonoYang** 2017-03-27 18:48 UTC
Labels: installation and packaging

**Comment by kartiksibal** [comment] 2017-03-27 18:58
@JonoYang :-)

**Comment by kartiksibal** [comment] 2017-03-27 19:00
@JonoYang I was also a little curious, as to why didn't travis indicate this?
