### ISSUE TITLE
License and Copyright information return errors

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#326] opened 2016-09-19 04:15 UTC
It looks like `licenses` and `copyrights` are no longer arrays. Also, they are returning errors instead of the detected data. 

For example, previously for the file `samples/JGroups/LICENSE` the following was returned:

```
      "licenses": [
        {
          "key": "lgpl-2.1-plus",
          "score": 100,
          "short_name": "LGPL 2.1 or later",
          "category": "Copyleft Limited",
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html",
          "text_url": "http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html",
          "dejacode_url": "https://enterprise.dejacode.com/license_library/Demo/lgpl-2.1-plus/",
          "spdx_license_key": "LGPL-2.1+",
          "spdx_url": "http://spdx.org/licenses/LGPL-2.1+",
          "start_line": 1,
          "end_line": 502
        }
      ],
```

and now the output for the same file is:
```
      "licenses": {
        "errors": "No module named ahocorasick"
      }, 
      "copyrights": {
        "errors": "'Tree' object has no attribute 'label'"
      },
```

These errors are occurring on the develop branch for `"scancode_version": "2.0.0.dev0"`. This is likely from changes related to #322.

When I do a fresh clone, there isn't an issue. It only occurs on a `git pull`.

**Comment by pombredanne** [comment] 2016-09-19 06:38
ok, this happens when there is a scan error, yet this should not change the shape of the returned data.... and there should not be an error either

**Comment by pombredanne** [comment] 2016-09-28 15:09
after your pull, did you run `./configure --clean` and `./configure`?

**Comment by pombredanne** [comment] 2016-10-21 15:16
@jdaguil I verified this and I cannot reproduce after a proper `configure --clean` and `configure`. Closing.

**Closed by pombredanne** 2016-10-21 15:16 UTC
Labels: bug, copyright scan, license scan
