### ISSUE TITLE
Make AppVeyor check PRs (was: Please add CI build badges to the README)

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#330] opened 2016-10-12 09:52 UTC
Could we please get build badges as part of the README, for both TravisCI and AppVeyor, and each for the `master` and `develop` branches? That helps to quickly see the health status, and to access the latest build artifacts for testing.

**Comment by pombredanne** [comment] 2016-10-12 10:47
@sschuberth Build badges have always been there as long as I recall  in the README. See
 https://github.com/nexB/scancode-toolkit#build-and-tests-status 
There is a table with Windows, Mac and Linux and both develop and master branches (and if you look at the raw text I recall this was a bit involved to get right ;) )

May be they should be instead at the top of the readme?

**Comment by sschuberth** [comment] 2016-10-12 10:50
Doh, sorry for that. I was so used from other projects to see these at the top that I simply did not scroll further down. Feel free to close this unchanged, or to move them to the top of the README as you prefer.

But on a related note, I don't see Appveyor builds being enabled for PRs. Is that something you could enable?

**Comment by pombredanne** [comment] 2016-10-12 10:56
OK, so let's move these to the top. 
On the appveyor side, I think things are enabled alright as per this: http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests and I checked the repo webhooks config whcih is correct. Do you have seen a problem?

**Comment by sschuberth** [comment] 2016-10-12 11:01
Well, looking at e.g. https://github.com/nexB/scancode-toolkit/pull/321 and clicking on "Show all checks" I would have expect to see AppVeyor in there, but I only see TravisCI ...

**Comment by pombredanne** [comment] 2016-10-12 11:11
Agreed, I would have loved to see this there too. But the problem is that Appveyor does not offer a "Github integration" but instead only a webhook. Hence the builds do not show up in a GH PR check.
To compound the issue, Appeyor does not have IRC notifications so I cannot even push build notifications  to #aboutcode on freenode.net like I push for Travis.

I will not complain: this is a free service but unfortunately as with many things in MSFT-centric development environments, the appveyor config is often arcane and circumvoluted

**Comment by pombredanne** [comment] 2016-10-12 11:14
As a side note, #321 may need some work and in particular the base url to link to a lincense may need be moved to a config option/config files. As it may also breaks some other features that require Jinja (for custom HTML templates, even though this feature may go away).

**Comment by sschuberth** [comment] 2016-10-12 11:23
> But the problem is that Appveyor does not offer a "Github integration" but instead only a webhook. Hence the builds do not show up in a GH PR check.

That's not correct :-) I recently helped to enable AppVeyor CI checks for PRs for the Git LFS project, see e.g. https://github.com/github/git-lfs/pull/1574.

> Appeyor does not have IRC notifications

At least it's on their list: https://github.com/appveyor/ci/issues/88.

**Comment by pombredanne** [comment] 2016-10-12 11:39
hum, I cannot see a way to enable an Appveyor integration though. 
Appveyor is configured to have access, but never offered as an integration. And never shows up in the list of commit/pr checks for any branch....
Do you have some insight with how this is setup on the git-lfs GH repo settings?

**Comment by pombredanne** [comment] 2016-10-12 11:47
ATM the way appveyor is configured is with a plain webhook added to the GH repo and setup to receive push and pr events

**Comment by sschuberth** [comment] 2016-10-12 11:49
Not sure what went wrong for you. I usually go to https://ci.appveyor.com/projects/new, select the "GitHub" tab, and add the project I want to have built. That makes PRs for me build out of the box.

**Comment by pombredanne** [comment] 2016-10-12 13:13
OK, let me try to delete the integrations and webhook and recreate that from scratch

**Comment by pombredanne** [comment] 2016-10-21 06:16
I deleted and recreated the Appveyor projects and it looks like this fixed the problem.

**Comment by pombredanne** [comment] 2016-10-21 06:22
And added a script forked from @crwood for IRC notifications. This covers appveyor/ci#88 nicely

**Comment by pombredanne** [comment] 2016-10-21 06:29
And you can see the first build working here: https://ci.appveyor.com/project/nexB/scancode-toolkit/build/1
And it was notified on freenode #aboutcode channel alright. Success! I will try a PR next.
Now the only dark side is that we lost the build history.

**Comment by pombredanne** [comment] 2016-10-21 22:38
@sschuberth as you can in https://github.com/nexB/scancode-toolkit/pull/334 we now both IRC notification and PR properly showing Appveyor as a check.
Thanks for the report!
Closing now

**Closed by pombredanne** 2016-10-21 22:38 UTC
