### ISSUE TITLE
Windows Installation Error

### ISSUE THREAD

**Issue by scottctr** [nexB/scancode-toolkit#706] opened 2017-07-28 01:38 UTC
I've tried installing 2.0.1 on Windows 10 twice -- ensuring I followed the directions. I've gotten the same error both times when running ScanCode the first time:

```
....snip....
  File "c:\scancode-toolkit-2.0.1\src\typecode\magic2.py", line 201, in load_lib
    new_path = os.pathsep.join([lib_dir, os.environ['PATH']])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 1447: ordinal not in range(128)

Failed to execute command:
C:\scancode-toolkit-2.0.1\bin\python.exe "C:\scancode-toolkit-2.0.1\etc\conf\base.py". Aborting...
```

**Comment by pombredanne** [comment] 2017-07-28 06:11
@scottctr thank you for this report.
Can you tell which exact command you used for scanning?
And what were you scanning? is this public code?

**Comment by scottctr** [comment] 2017-07-28 11:33
This actually occurred right after decompressing the latest ScanCode files into a new directory and using `scancode -h`. Note that I've previously been using 2.0.0 rc2 and never had a problem.

**Comment by pombredanne** [comment] 2017-07-28 12:11
@scottctr Thanks. This is surprising... but there have been some changes in handling unicode paths... Anything special about your environment? is this is an English installation of Windows 10 or a some other language? 
Is there something special in your `PATH` variable? Would it contain paths with special, non-Ascii like characters may be? I am trying to find a way to reproduce this correctly. 
For instance what shows up if you run this command:
```
c:\python27\python.exe -c "import os; print repr(os.environ['PATH'])"
```

**Comment by scottctr** [comment] 2017-07-28 12:12
I should also add that I'm using the scancode-toolkit-2.0.1.zip download and the Windows 10 decompress tool. I'll try the scancode-toolkit-2.0.1.tar.bz2 and 7zip shortly.

**Comment by pombredanne** [comment] 2017-07-28 12:15
@scottctr using the windows built-in zip should be fine normally I doubt this would make a difference to use another archive type and unarchiver. The reason for the failure is more likely in the `PATH` and some bug on our side about dealing with this

**Comment by scottctr** [comment] 2017-07-28 12:17
This is a standard US/English Windows 10 machine, but I think you're onto something with the path. Notice the entry in the path is `C:\\Program Files (x86)\\V\xf6r Security\\DevAudit\\`, but should be `C:\\Program Files (x86)\\Vör Security\\DevAudit\\`. I'll test this shortly.

```
C:\scancode-toolkit-2.0.1>c:\python27\python.exe -c "import os; print repr(os.environ['PATH'])"
'C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Users\\Scott\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\Tools\\Binn\\ManagementStudio\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\Scott\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Users\\Scott\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files (x86)\\V\xf6r Security\\DevAudit\\'
```

**Comment by pombredanne** [comment] 2017-07-28 12:46
@scottctr thanks. The culprit is the last path segment `C:\\Program Files (x86)\\V\xf6r Security\\DevAudit\\`... That makes for a good test case! If you temporarily remove this from your `PATH` variable, things should work OK normally.

**Comment by pombredanne** [comment] 2017-07-28 12:46
And I will work out a fix

**Comment by pombredanne** [comment] 2017-08-29 15:41
@scottctr the branch https://github.com/nexB/scancode-toolkit/tree/706-PATH-environment-var-with-unicode should fix your issue. Do you mind to test if this works for you?

**Comment by pombredanne** [comment] 2017-08-30 09:56
This has been merged in develop. Closing for now but feedback welcomed. Thanks again!

**Closed by pombredanne** 2017-08-30 09:56 UTC
Labels: bug, fixed pending review, installation and packaging

**Comment by scottctr** [comment] 2017-09-01 20:52
Sorry for the delay, but I tested this today and the problem is no longer occurring -- thanks!
