### ISSUE TITLE
Post-scan plugin for license expression(s) summarization

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#772] opened 2017-09-26 00:32 UTC
There should be a top level view of all the licenses found in the scanned code base. It should be ordered by license type and number of files with that license. Also, a count of files where a license was not detected should also be kept. This can be done in a post-scan plugin.

**Comment by JonoYang** [comment] 2017-09-26 19:09
The post-scan plugins only have access to the scanned files in a scan. We would need to also be able to interact with how the scans are formatted in order to create a new "top" level field to display the different licenses and the number of occurrences. If we do this, it seems that we would need to create a specific format plugin and option for license summarization or modify every current plugin to be able to print the new field.

**Comment by pombredanne** [comment] 2017-09-26 19:15
@JonoYang You have a good point.... yet what is a summarization of data in a file and directory tree? Could  this is be something that you add to the top level directory? In this case, then summarization would not require any new data structure, but only to roll-up data at a directory level may be?

**Comment by pombredanne** [comment] 2018-03-28 15:37
See also #377 ... this may be a dupe?

**Comment by pombredanne** [comment] 2018-04-17 16:03
Actually this is not a dupe of #377 but instead a concrete step of realizing it.

**Comment by pombredanne** [comment] 2018-04-17 16:06
Here is how I can see this license summary working:
1. first we need to have #74 to Report detected license expressions in ScanCode
2. based on these, we will aggregate with an "AND" all the expressions and simplify them in this way:
2.1 for a file, combine all the expressions found in that file
2.2 for a directory or archive/file with children, combine all the expressions found in all the files and directories in this tree

3. this will be reported as a single license expression string under some `license_summary` attribute.

**Comment by pombredanne** [comment] 2018-07-17 15:46
Here is how I can see this license summary working:
Some status:
- #74 is implemented we now report detected license expressions
- we do a direct summarization of expressions in the `summary` in the develop branch with #1130  being merged

For now there is no top level aggregation of all licenses... and it may not be needed.

**Comment by pombredanne** [comment] 2018-08-14 15:08
It has been merged in develop. So closing. 
The one thing that is NOT done and on purpose is treating equivalent expressions as being the same for summarization

**Closed by pombredanne** 2018-08-14 15:08 UTC
Labels: enhancement, license scan, must have, plugin
