### ISSUE TITLE
Package parser looking for current directory, not absolute path 

### ISSUE THREAD

**Issue by cshwan78** [nexB/scancode-toolkit#2517] opened 2021-05-04 06:39 UTC
### Description

> Please leave a brief description of the bug or feature request:

packagedcode/pypi.py opens a "requirements.txt" with relative path, not absolute path. [pypi.py L114](https://github.com/nexB/scancode-toolkit/blob/bb044200ae86770f9bb01560c0033037ee18b947/src/packagedcode/pypi.py#L114)

### How To Reproduce

> Tell us how to reproduce the issue. 

```scancode -clip -json-pp - /absolute_path/codebase```
running above command in other directory.
Of course, I can run scancode in /absolute_path/codebase. 
However the result of /absolute_path/codebase/tools/requirements.txt is from /absolute_path/codebase/requirements.txt, which is a wrong result.

I tried some dirty hacks to solve the problem, such as calling os.chdir at the beginning of parse.
However I cannot tell this is the right way to implement. 
If you can give me some advices, then I can make a pull request to this.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
linux
* What version of scancode-toolkit was used to generate the scan file?
pip install scancode[full] - today
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment] 2021-05-04 16:21
@cshwan78 thank you for the report. That's a great catch. I was not sure I was getting exactly what you meant but I was able to reproduce this alright.

**Comment by cshwan78** [comment] 2021-05-05 16:26
@pombredanne After some debugging, I realized that I was wrong at the first look.
I think the root cause is about parse_dependencies, which calling parse_with_dparse with the return value of os.listdir, which is only a filename without a directory path. [pypi.py L194](https://github.com/nexB/scancode-toolkit/blob/bb044200ae86770f9bb01560c0033037ee18b947/src/packagedcode/pypi.py#L194)

I think something like the below can solve the problem

```
abs_location = os.path.join(location, resource_location)
dependencies = parse_with_dparse(abs_location)
---------- instead of ---------
dependencies = parse_with_dparse(location)
```

I will work on this, and make a test for it.

If you have any other suggestion or some advice, please let me know.

**Comment by pombredanne** [comment] 2021-05-05 17:33
@cshwan78 re:

> I will work on this, and make a test for it.
> If you have any other suggestion or some advice, please let me know.

Thank you, this looks great: you rock.

It is going to be difficult to make a test for it though as it can involve changing directories?

**Comment by pombredanne** [comment] 2021-05-21 14:19
@cshwan78 I made some fairly extensive refactoring of the PyPI code and this commit https://github.com/nexB/scancode-toolkit/pull/2526/files#diff-166f21bb085d47341daf98771ee29cd76e2f68ddeb34b8eb981a9d1f3b05e8b9R471 has your fix!
Thank you ++ :bow:

**Comment by pombredanne** [comment] 2022-02-02 09:28
I am closing this now... Note also that we have since forked dparse in dparse2 ... and use a new https://github.com/nexB/pip-requirements-parser parser for requirements.

**Closed as completed by pombredanne** 2022-02-02 09:28 UTC
Labels: bug
