### ISSUE TITLE
out-of-memory error on --reindex-licenses on Windows10, Python 2.7.15

### ISSUE THREAD

**Issue by Shaker1978** [nexB/scancode-toolkit#1458] opened 2019-03-20 10:32 UTC
### Description
I downloaded and extracted version 3.0.2 and after initializing (first call "scancode --version") I did a --reindex-licenses, resulting in an out-of-memory error.
[Scancode--reindex-licenses.txt](https://github.com/nexB/scancode-toolkit/files/2987700/Scancode--reindex-licenses.txt)
The only modification made is in the configure.bat, because I use a different python path. My colleague has the same error on his machine when using the default python path.
I experienced this out-of-memory situation on Windows in other scancode versions, too when adding some licenses.
I can watch the python.exe process just before the error is reported, that it grows up to 800MB of memory usage.

In a Docker container (Linux) given 2GB of memory, this scancode version 3.0.2 works!

### System configuration
Windows 10 Pro (x64), Core-i7, 16GB RAM
scancode-toolkit-3.0.2,  source download, scancode.bat

**Comment by pombredanne** [comment] 2019-03-20 16:16
@Shaker1978 thank you for the report and sorry for the bug. It sounds like this is something that is because of the fact ScanCode requires a Python 32 bits on Windows... though should be possible to run 64 bits now. Let me check this

**Comment by pombredanne** [comment] 2019-03-20 16:18
@dineshr93 I am merging your report #1459 here as this is the same bug. 
```
### Description
I was just following the initial setup and ran the command in the help.
I get the out of memory error

### System configuration
For bug reports, it really helps us to know:
* Windows 10 64 bit
* https://github.com/nexB/scancode-toolkit/tree/v3.0.2
* scancode -h



> (scancode-toolkit-3.0.2) D:\software\scancode-toolkit-3.0.2> scancode --license --copyright --json-pp scancode_result.json samples
> Setup plugins...
> d:\software\scancode-toolkit-3.0.2\src\licensedcode\index.py:796: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   old_tid = old_dictionary_get(token)
> ERROR: failed to setup plugin: scan:licenses:
> Traceback (most recent call last):
>   File "d:\software\scancode-toolkit-3.0.2\src\scancode\cli.py", line 592, in scancode
>     plugin.setup(**kwargs)
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\plugin_license.py", line 119, in setup
>     get_index(return_value=False)
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\cache.py", line 67, in get_index
>     _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\cache.py", line 247, in get_cached_index
>     ifc.write(idx.dumps())
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\index.py", line 723, in dumps
>     return pickle.dumps(self, protocol=cPickle.HIGHEST_PROTOCOL)
>   File "c:\python27\Lib\pickle.py", line 1380, in dumps
>     Pickler(file, protocol).dump(obj)
>   File "c:\python27\Lib\pickle.py", line 224, in dump
>     self.save(obj)
>   File "c:\python27\Lib\pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "c:\python27\Lib\pickle.py", line 425, in save_reduce
>     save(state)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 554, in save_tuple
>     save(element)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 655, in save_dict
>     self._batch_setitems(obj.iteritems())
>   File "c:\python27\Lib\pickle.py", line 687, in _batch_setitems
>     save(v)
>   File "c:\python27\Lib\pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "c:\python27\Lib\pickle.py", line 401, in save_reduce
>     save(args)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 568, in save_tuple
>     save(element)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 495, in save_string
>     self.memoize(obj)
>   File "c:\python27\Lib\pickle.py", line 246, in memoize
>     self.write(self.put(memo_len))
> MemoryError: out of memory
> 
> Removing temporary files...done.
> (scancode-toolkit-3.0.2) D:\software\scancode-toolkit-3.0.2>
```

**Comment by pombredanne** [comment] 2019-03-22 14:26
@linexb do you think you could check this issue? 
We can get time limited VMs (for Virtual BOX) for 64 bits from there: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and these are not too big. You would need to use a 64 bits VM image for VB and set it up using the default RAM (which I think is 4GB)

**Comment by pombredanne** [comment] 2019-03-22 14:28
@Shaker1978  you wrote:
> In a Docker container (Linux) given 2GB of memory, this scancode version 3.0.2 works!
as an anecdote, I noticed that memory management seems much more efficient on Linux than Windows... but no hard data for this. The real issue here is IMHO 32 vs. 64 bits

**Comment by linexb** [comment] 2019-06-21 12:52
@pombredanne  I am starting working on it.

**Comment by linexb** [comment] 2019-06-24 02:14
I tried on Windows 7 64bit, I didn't reproduce the error. It might be a problem on Windows 10 only, I will try to setup the enviroment and give a shot. Or the problem was already fixed, I will keep this updated.

**Comment by linexb** [comment] 2019-06-25 14:27
I tried on Windows server 2012 64bit, and I can't reproduce the error either. I believe the issue might be already fixed...

**Comment by linexb** [comment] 2019-06-25 14:30
@Shaker1978 Could you please run again with latest version of scancode, I tried with the latest version on develop branch on windows 7 and windows 2012 server 64bit, it works fine.

One thing I noticed that we only support Python 32bit, so please make sure your Python is 32bit 2.7.x.

Please let me know if it still doesn't work. Thank you.

**Comment by pombredanne** [comment] 2021-09-24 12:39
we now bundle a pre-built index, dropped support for 32 bits windows and now reindexing should run fine and  will always require some serious RAM. closing now!

**Closed by pombredanne** 2021-09-24 12:39 UTC
Labels: bug, major, core and api, installation and packaging
