### ISSUE TITLE
UnicodeDecodeError backtrace during scan

### ISSUE THREAD

**Issue by dengste** [nexB/scancode-toolkit#688] opened 2017-07-14 08:21 UTC
Using scancode 2.0.1. I get an abort with a UnicodeDecodeError backtrace. I'm guessing this is due to same illegal encoding in some file, but I cannot figure out which file exactly is responsible. The backtrace does not tell me much because I cannot see the original backtrace that triggered this but only the one from the multiprocessing pool:

```
Traceback (most recent call last):
  File "/home/engsterd/scancode-toolkit-2.0.1/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/home/engsterd/scancode-toolkit-2.0.1/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/engsterd/scancode-toolkit-2.0.1/src/scancode/utils.py", line 76, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/engsterd/scancode-toolkit-2.0.1/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/engsterd/scancode-toolkit-2.0.1/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/engsterd/scancode-toolkit-2.0.1/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/engsterd/scancode-toolkit-2.0.1/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/engsterd/scancode-toolkit-2.0.1/src/scancode/cli.py", line 402, in scancode
    ignore=user_ignore)
  File "/home/engsterd/scancode-toolkit-2.0.1/src/scancode/cli.py", line 515, in scan
    result = scanned.next()
  File "/home/engsterd/scancode-toolkit-2.0.1/local/lib/python2.7/site-packages/click/_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "/home/engsterd/scancode-toolkit-2.0.1/src/scancode/pool.py", line 46, in wrap
    return func(self, timeout=timeout or 1e10)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 28: ordinal not in range(128)
```

**Comment by pombredanne** [comment] 2017-07-14 10:35
@dengste 
Couple questions to help track this bug:

- Can you paste the exact scancode args and  options you have used? 
- Is this while scanning public or private code? If public can you send a link?
- Was the code being scanned extracted from an archive? if so which tool did you use to extract this?
- Can you rerun your scan adding these options `--verbose --diag --processes 1` : these will provide a different style for progress (one line per file), printout more diagnostic information and run on a single process. Eventually this should provide more details.
- What is your locale (run `locale`)?
- Can you and paste the output of this:
`python -c "import sys;print('filesystem encoding:', repr(sys.getfilesystemencoding()), 'default encoding:', repr(sys.getdefaultencoding()))"`

**Comment by dengste** [comment] 2017-07-14 11:39
I simply ran scancode with

    ./scancode <directory> test.json

Unfortunately, it's private data and I cannot share it. It's a git repo, so the files were not extracted from an archive. Running with the suggested options simply says

    [....]
    Scanned: path1/path2/somefile
    Traceback (most recent call last):

and it follows the exact same backtrace as above. Funny thing is: If I rerun scancode on the subdirectory path1/path2, it works...

Locale output:
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Python output:
`('filesystem encoding:', "'UTF-8'", 'default encoding:', "'ascii'")`

Is there some way to modify the code so that I can see the original backtrace that triggers this? Then I can debug this further myself.

**Comment by dengste** [comment] 2017-07-14 12:17
I found the offending file: it has a plus-minus sign in iso-encoding in it. On my shell (zsh) I can create such a file with

   touch foo$'\261'bar

Scanning that file will create the above backtrace. The file exists this way because it was checked in with an old MSysGit version for Windows, which still used codepages instead of UTF-8.

**Comment by pombredanne** [comment] 2017-07-14 12:30
@dengste Thanks. Let add a test and track this pesky bug

**Comment by pombredanne** [comment] 2017-07-14 14:54
@dengste I pushed some tests (failing) in a branch that show the problem thanks to your research.
Now there are various ways to resolve this:
1. always return a proper error for a path that is not unicode decodable: Do not scan but the scan will have a clear error message for this path.
2. if a path is not unicode decodable, do not error and fall back to bytes. Then in the scan outputs (that demand unicode encoded as UTF-8) return %-encoded paths for these pesky paths.

None of these solutions is entirely satisfying: 1. skips a file to scan but is quite visible (though I even wonder if we might not need to also %-encode this somehow)  while 2. does the work quietly but is a tad more complex and the paths reported in the outputs may not be easy to recreate and relate to an actual path.

Note: we used to have %-encoding and dropped it in favor of unicode/utf-8.  
@sschuberth Ping: I recall you reported some tickets in this area too.

**Comment by pombredanne** [comment] 2017-07-14 15:00
FWIW the error exists also in the std Python and is not so much a Python error per se.
Dealing with unknown encodings (aka. bytes) is always a potential issue when you want unicode out.

```
Python 2.7.13 (default, Jun 16 2017, 16:03:08) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> list(os.walk(u'non_unicode'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pombreda/.pyenv/versions/2.7.13/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/home/pombreda/.pyenv/versions/2.7.13/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 4: ordinal not in range(128)
>>> list(os.walk('non_unicode'))
[('non_unicode', [], ['foo\xb1bar'])]
>>> 
```

**Comment by pombredanne** [comment] 2017-07-14 15:01
Actually this is no longer a bug on Python 3....
```
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> list(os.walk('non_unicode'))
[('non_unicode', [], ['foo\udcb1bar'])]
>>> list(os.walk(b'non_unicode'))
[(b'non_unicode', [], [b'foo\xb1bar'])]
>>> 
```

**Comment by sschuberth** [comment] 2017-07-14 15:01
I indeed did see the same issue not too long ago in one of our scans, but I forgot to file a ticket about it.

**Comment by pombredanne** [comment] 2017-07-14 15:08
@sschuberth thanks!

So since this is eventually a bug in Python that is fixed in Py3, here is what I suggest:

Do not let a scan fail (ever) but do not attempt to scan the file either since most everything is expecting Unicode throughout inside in preparation to the Py3 move. Instead return an error for this path as a percent encoded path and also add its bytes representation in the error message. 

And when Python3 support is there with #295 there will be no error messages anymore on these type of files (hopefully... as things get complicated at times with the expectations of third-party libraries and natives wrt to unicode, paths and file system encodings).

**Comment by sschuberth** [comment] 2017-07-21 09:46
Some more info from my side: I saw this happening on our CI when scanning https://github.com/expressjs/serve-static/tree/v1.12.3, however, locally the scan completed just fine. `locale` output is the same on both machines, so what could make a difference?

In any case, I guess the problematic path is this one: https://github.com/expressjs/serve-static/tree/v1.12.3/test/fixtures/snow%20%E2%98%83

**Comment by pombredanne** [comment] 2017-07-21 11:32
@sschuberth Thanks! are you sure you use the same scancode version on each sides?

**Comment by sschuberth** [comment] 2017-07-21 12:31
No, I'm not. On CI it's `ScanCode version 2.0.1.post77.05aa65a` (failing), locally I'm using `ScanCode version 2.0.1.post76.865d2487` (succeeding). I didn't think it would make a difference as this issue is still open and you didn't submit a fix, or?

**Comment by sschuberth** [comment] 2017-07-21 12:49
Ha, nailed it: The difference in CI is that stdout and stderr get redirected. I can reproduce the error locally by doing

    $ scancode --verbose . > log.txt 2>&1
    $ grep UnicodeEncodeError log.txt
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 28: ordinal not in range(128)

**Comment by sschuberth** [comment] 2017-07-21 13:29
Thanks to [this article](http://chase-seibert.github.io/blog/2014/01/12/python-unicode-console-output.html) I learned that I can work around my new stack trace issue by doing `export PYTHONIOENCODING=UTF-8`.

**Comment by pombredanne** [comment] 2017-07-21 13:32
@sschuberth thanks++ for tracking this. This is indeed related but different and linked to the fact that we are unicode inside and the console may not be.  This will require a tad less engaged fix to deal with the stdout/stderr portions of outputs and to ensure that things (here path) are properly encoded as bytes on Linux.

For the FS path issue initially reported, at this stage after a bit of research since this initial submission the crux of the issue is that on Linux-only and Python2 we can have `os.listdir()` that when given a unicode path may still return some bytes rather than unicode. Py3 uses surrogate pairs escape encoding instead and always return unicode.
I can think of two routes:
- only on Linux, use always bytes for paths and redo some smarter per-path-segment UTF-8 or FS-encoding decoding to unicode for final reporting. If this fails, attempt to use backport of escaping to surrogate pairs (which would be in the case of a pure byte, non-unicode decodable path segment)
- use unicode throughout as it is today on all OSes. On Linux and when walking paths, check that each segment is unicode. If not use surrogate pair encoding to force unicode. When passing paths to other functions and tools, always pass path encoded back to bytes using the fsencoding ....

So, unicode is fun is it? note that this is only a tiny bit because of some python weirdness or bug, and a lot because of the support of Windows, Linux and Mac in a single codebase when there is no compatible semantics on all the filesystems and arbitrary that come from any OS, FS and encoding possible.

and thanks for the link to the article too!

**Comment by pombredanne** [comment] 2017-07-21 13:33
that env `PYTHONIOENCODING` will solve nicely the console part!

**Comment by pombredanne** [comment] 2017-07-28 14:11
FYI, I am doing experiments with https://github.com/jaraco/path.py and also direct support of Unicode surrogate pairs encoding of bytes to ensure we can still use Unicode throughout and handle bytes paths correctly.

**Comment by pombredanne** [comment] 2017-08-16 14:30
Just to restate the core of the issue:
```
$ touch foo$'\261'bar
$ touch plain
$ python2 -c "import os;print os.listdir('.');print os.listdir(u'.')"
['foo\xb1bar', 'plain']
['foo\xb1bar', u'plain']    <<<<==== here we have a mix of bytes and unicode items
$ python3 -c "import os;print(os.listdir('.'))"
['foo\udcb1bar', 'plain']
```

Now I tried `path.py` without luck https://github.com/jaraco/path.py/issues/130 as well as `scandir` without luck either https://github.com/benhoyt/scandir/issues/86

`python-future` provides `surrogateescape` support but does not have any specific support for dealing with path proper.

`pathlib2` is a backport of Python 3 and works on python 3 but returns only bytes on Linux in the backport.

So the only thing left todo is to deal with bytes throughout on Linux and unicode elsewhere.

**Comment by pombredanne** [comment] 2017-08-23 09:10
@dengste I have made quite a bit of progress and we are almost there... there are only a few important but easy to fix tests left to address...  FWIW, the approach used is explained in #723

**Comment by pombredanne** [comment] 2017-08-29 15:43
@dengste the code in the branch https://github.com/nexB/scancode-toolkit/tree/688-non-utf8-path is now passing the tests on all the supported OSes... 
Do you mind to check if this branch works for you before I merge? Thanks!

**Comment by pombredanne** [comment] 2017-08-29 15:46
In the end the solution has been to use the backports.os(https://github.com/pjdelport/backports.os) by @pjdelport (Thanks!) that provides a proper and working os.fsencode/os.fsdecode as in Python 3... and use bytes everywhere on Linux and Unicode everywhere else.

**Comment by pombredanne** [comment] 2017-08-30 09:56
@dengste this has been merged in develop. Feedback welcomed and thank you for the report!

**Comment by sschuberth** [comment] 2017-09-07 11:04
@pombredanne, unfortunately, even with ScanCode version 2.0.1.post183.a9d16661, I get

    Traceback (most recent call last):
      File "/workspace/tools/scancode/bin/scancode", line 11, in <module>
        load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/workspace/tools/scancode/src/scancode/utils.py", line 74, in main
        standalone_mode=standalone_mode, **extra)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 486, in scancode
        pre_scan_plugins=pre_scan_plugins)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 634, in scan
        result = scanned.next()
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/_termui_impl.py", line 257, in next
        return next(self.iter)
      File "/workspace/tools/scancode/src/scancode/pool.py", line 46, in wrap
        return func(self, timeout=timeout or 1e10)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
        raise value
    UnicodeEncodeError: 'ascii' codec can't encode character u'\udce2' in position 19: ordinal not in range(128)

when scanning the [NPM serve-static package version 1.12.4](https://github.com/expressjs/serve-static/tree/v1.12.4).

**Comment by pombredanne** [comment] 2017-09-07 15:40
@sschuberth this is weird: I cannot repdroduce.
Using the exact same ScanCode version as you and 1.12.4 from serve-static
```
$ git describe
v1.2.2-201-gc16b4d1
```
I get no error:
```
$ scancode --copyright --license --info --diag --only-findings --strip-root . test.json 
Scanning files for: infos, licenses, copyrights with 1 process(es)...
Building license detection index...Done.
Scanning files...
[####################] 32                                                     
Scanning done.
Scan statistics: 32 files scanned in 4s.
Scan options:    infos, licenses, copyrights with 1 process(es).
Scanning speed:  12.17 files per sec.
Scanning time:   2s.
Indexing time:   1s.
Running post-scan plugin: only-findings...
Saving results.
```

Could you rerun this with the `-n0` option? this disables entirely multiprocessing and threading and provides therefore detailed stack traces.

Also can you do a `./configure --clean` ?

**Comment by sschuberth** [comment] 2017-09-07 15:49
> Also can you do a `./configure --clean` ?

We're doing a `git clean -fdx` befor each run, and ScanCode says `Configuring ScanCode for first use`, so `./configure --clean` should not be necessary, correct?

> Could you rerun this with the `-n0` option?

I'll do that ASAP.

Doh, wait a second, I just noticed it's now a Unicode**Encode**Error as opposed to Unicode**Decode**Error.

Original report:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 28: ordinal not in range(128)

My last report:

    UnicodeEncodeError: 'ascii' codec can't encode character u'\udce2' in position 19: ordinal not in range(128)

Sorry for that, so it's a new issue now!

**Comment by pombredanne** [comment] 2017-09-07 15:59
Note that `./configure --clean` also deleted dangling .pyc files

**Comment by sschuberth** [comment] 2017-09-07 16:01
Which `git clean -fdx` (note the `-x`) also does, right?

**Comment by sschuberth** [comment] 2017-09-08 09:11
Just wild guessing as Python is not my primary language, but isn't it suspicious that in `u'\udce2'` there seems to be some sort of double-conversion to Unicode? Like `\udce2` already denotes a Unicode char, but it's then converted to Unicode via the `u` prefix again?

**Comment by pombredanne** [comment] 2017-09-08 10:12
@sschuberth can you tell some details about your os/version/arch, locale and file system encoding?
And try from a fresh git clone too?
Again I cannot reproduce on Linux when scanning a clone of server-static

**Comment by sschuberth** [comment] 2017-09-08 10:30
I cannot reproduce it locally either :-( Here's a traceback from running with `-n0`:

    Scanning product source code in '/workspace/scanroot/serve-static'...
    Scanning files for: infos, licenses, copyrights with 0 process(es)...

    Building license detection index...Done.
    Disabling multi-processing and multi-threading...
    Scanning files...

    Traceback (most recent call last):
      File "/workspace/tools/scancode/bin/scancode", line 11, in <module>
        load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/workspace/tools/scancode/src/scancode/utils.py", line 74, in main
        standalone_mode=standalone_mode, **extra)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 486, in scancode
        pre_scan_plugins=pre_scan_plugins)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 634, in scan
        result = scanned.next()
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/click/_termui_impl.py", line 257, in next
        return next(self.iter)
      File "/workspace/tools/scancode/src/scancode/cli.py", line 729, in _resource_logger
        file_logger(logfile_fd, rel_path)
      File "/workspace/tools/scancode/src/scancode/cache.py", line 219, in log_file_path
        path = path_to_bytes(path) + b'\n'
      File "/workspace/tools/scancode/src/commoncode/fileutils.py", line 231, in path_to_bytes
        return osb.fsencode(path)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/backports/os.py", line 133, in fsencode
        return filename.encode(encoding, errors)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\udce2' in position 19: ordinal not in range(128)

Will try to get your other requested infos..

**Comment by pombredanne** [comment] 2017-09-08 10:34
Could you also add a print statement just before:
`"/workspace/tools/scancode/src/commoncode/fileutils.py", line 231, in path_to_bytes`

e.g. `print('path', repr(path))`

?

**Comment by sschuberth** [comment] 2017-09-08 10:52
That gives

    XXX path u'test/fixtures/snow \udce2\udc98\udc83'

**Comment by pombredanne** [comment] 2017-09-08 11:12
ok, here what could help:
1. go to the rootdir of scancode, run `source bin/activate`
2. run `python` and post the two first lines that are printed 
something like
```
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
```
3. in python collect encoding and a few more info:
```
>>> import sys
>>> sys.getfilesystemencoding()
'UTF-8'
>>> sys.getdefaultencoding()
'ascii'
>>> sys.maxunicode
1114111
>>> sys.maxsize
9223372036854775807
>>> import os
>>> os.environ['LANGUAGE']
'en_US'
>>> os.environ['LANG']
'en_US.UTF-8'
```

4. exit python and back in the shell run `locale`

5. past the outputs of all this here

**Comment by pombredanne** [comment] 2017-09-08 11:17
@sschuberth actually hold that for a sec. There is a bug I think I found

**Comment by pombredanne** [comment] 2017-09-08 11:29
Somehow this all important line change: https://github.com/nexB/scancode-toolkit/commit/f3ce0e2fe62773a1518b92dcbd2ae7df1d72ccda#diff-1e37ecfb9a8c3fccd8ecdfb2ce51f591R346 got lost in merges ... can you still post the data from https://github.com/nexB/scancode-toolkit/issues/688#issuecomment-328076177 ?

**Comment by pombredanne** [comment] 2017-09-08 11:40
This latest commit and PR #752 should fix it I hope!

**Comment by pombredanne** [comment] 2017-09-08 17:13
@sschuberth I would need to get your data from https://github.com/nexB/scancode-toolkit/issues/688#issuecomment-328076177 to fix this

**Comment by sschuberth** [comment] 2017-09-08 17:27
Here's the output, in order:

    ANSI_X3.4-1968
    ascii
    1114111
    9223372036854775807
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/workspace/tools/scancode/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'LANGUAGE'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/workspace/tools/scancode/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'LANG'
    LANG=
    LANGUAGE=
    LC_CTYPE="POSIX"
    LC_NUMERIC="POSIX"
    LC_TIME="POSIX"
    LC_COLLATE="POSIX"
    LC_MONETARY="POSIX"
    LC_MESSAGES="POSIX"
    LC_PAPER="POSIX"
    LC_NAME="POSIX"
    LC_ADDRESS="POSIX"
    LC_TELEPHONE="POSIX"
    LC_MEASUREMENT="POSIX"
    LC_IDENTIFICATION="POSIX"
    LC_ALL=

**Comment by sschuberth** [comment] 2017-09-08 17:30
Could it be that [this](https://stackoverflow.com/a/37246853/1127485) is the problem ( I *do* `export PYTHONIOENCODING=UTF-8` globally)?

**Comment by sschuberth** [comment] 2017-09-08 17:36
BTW, our strange locale seems to be due to the fact that we run ScanCode inside a Docker container. Need to investigate further.

**Comment by pombredanne** [comment] 2017-09-08 19:36
Your file system encoding is actually plain ASCII, which is uncommon but OK for Linux.
```
>>> import codecs
>>> c = codecs.lookup('ANSI_X3.4-1968')
>>> c.name
'ascii'
```
`export PYTHONIOENCODING=UTF-8` may be an issue and is unlikely needed.

You lack of proper locale and LANG/LANGUAGE is likely an issue in general and likely for scancode too.
See for instance: https://github.com/openshift/jenkins/issues/279

**Comment by sschuberth** [comment] 2017-09-11 18:30
I can confirm that with a proper locale set inside the Docker container (as described at https://askubuntu.com/a/601498) I'm not seeing the `UnicodeEncodeError` (nor the original `UnicodeDecodeError`) anymore. Should we still keep this open until #752 is merged?

**Comment by pombredanne** [comment] 2017-09-12 22:16
@sschuberth Thanks. We still want this opened until #752 is merged alright. If I do not get some reply from @pjdelport I might just build and publish an alternate wheel with the patch to get this moving.

**Comment by sschuberth** [comment] 2017-09-13 04:33
I believe @pjdelport is waiting for an answer to [the question](https://github.com/pjdelport/backports.os/pull/4#issuecomment-328369845)

> Are there any potential ill or compatibility-breaking side effects to normalising the codec name earlier like this?

**Comment by sschuberth** [comment] 2017-12-15 10:29
@pombredanne, I believe this can be closed now, or?

**Comment by pombredanne** [comment] 2017-12-15 14:08
@sschuberth sure, the behavior is now correct AND in anycase, a Docker image should set it's LOCALE to avoid any (other) issues too.

**Comment by pombredanne** [comment] 2017-12-15 14:09
@dengste Please reopen if you still experience this.... but we should be good now

**Closed by pombredanne** 2017-12-15 14:08 UTC
Labels: bug, core and api, major
