### ISSUE TITLE
scancode with --summary throws warnings about missing logger handlers

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1691] opened 2019-08-23 20:20 UTC
### Description
Please leave a brief discription of the bug or feature request:

When running scancode with the --summary option I get warnings:

    No handlers could be found for logger "bs4.dammit"

Scancode was run as follows:

    $ ./scancode --full-root -l --license-text -c -e -u -n 8 --summary --json-pp=/tmp/output.json2 /tmp/busybox-1.28.0/

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux) - Fedora 30
* What version of scancode-toolkit was used to generate the scan file? - develop branch, commit 483e47a69e24a0b9ac08f0861ce63dbb7be457f9
* What installation method was used to install/run scancode? (pip/source download/other) - source download

**Comment by pombredanne** [comment] 2019-08-30 17:57
Thank you for this. Dammit dammit!

**Comment by Iamshankhadeep** [comment] 2019-10-14 16:32
@pombredanne What do I need to do exactly?

**Comment by pombredanne** [comment] 2019-10-14 18:01
@Iamshankhadeep thanks for willing to help!
I guess you would need to try to reproduce this bug first with the help of @armijnhemel 
Then I am not sure how to fix this... it could be that this is a bug in bs4 https://pypi.org/project/beautifulsoup4/ ?

**Comment by Iamshankhadeep** [comment] 2019-10-14 18:07
thanks for replying @pombredanne . so, @armijnhemel how did you get to that error?

**Comment by armijnhemel** [comment] 2019-10-14 18:37
> thanks for replying @pombredanne . so, @armijnhemel how did you get to that error?

I ran scancode ;-)

My system is Fedora 30. The command I used can be found in the first post in this thread.

**Comment by johnmhoran** [comment] 2019-10-14 23:52
@pombredanne I am also now getting this alert running scans on my Windows 10 box -- pretty sure I only started seeing this recently.  Running on `develop` branch `version 3.1.1.post82.d7c826308,`.  Excerpt:

```
. . .
Setup plugins...
Collect file inventory...
Scan files for: info with 2 process(es)...
No handlers could be found for logger "bs4.dammit"
No handlers could be found for logger "bs4.dammit"
No handlers could be found for logger "bs4.dammit"
Scanning done.
. . .
```

**Comment by pombredanne** [comment] 2019-10-15 09:54
@Iamshankhadeep  use this.
We get either `No handlers could be found for logger "bs4.dammit"` on some OS or `Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.` otherwise. A problem in anycase. The culprit is this in @leonardr 's bs4.dammit https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/bs4/dammit.py#L379 but we should be able to fix this rogue logging on our side IMHO


```
$ wget https://www.busybox.net/downloads/busybox-1.28.0.tar.bz2
$ tar -xf busybox-1.28.0.tar.bz2
$ ./scancode -c  --json-pp bb.json busybox-1.28.0/shell/ash_test/ash-quoting/
Setup plugins...
Collect file inventory...
Scan files for: copyrights with 1 process(es)...
[--------------------] 4 Scanned: dollar_squote_bash1.tests    Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
[--------------------] 5 Scanned: dollar_squote_bash2.right    Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
[####################] 12                                      
Scanning done.
Summary:        copyrights with 1 process(es)
Errors count:   0
Scan Speed:     29.45 files/sec. 
Initial counts: 13 resource(s): 12 file(s) and 1 directorie(s) 
Final counts:   13 resource(s): 12 file(s) and 1 directorie(s) 
Timings:
  scan_start: 2019-10-15T094603.228253
  scan_end:   2019-10-15T094603.642153
  scan: 0.41s
  total: 0.42s
Removing temporary files...done.

```

**Comment by pombredanne** [comment] 2019-10-15 10:48
A simple fix is to configure a null handler for the root logger ONLY when scancode is started as a command line application :
```
diff --git a/src/scancode/cli.py b/src/scancode/cli.py
index 4b0857f..510f280 100644
--- a/src/scancode/cli.py
+++ b/src/scancode/cli.py
@@ -36,6 +36,7 @@
 from collections import defaultdict
 from collections import OrderedDict
 from functools import partial
+import logging
 from commoncode.system import on_windows
 
 # Python 2 and 3 support
@@ -483,6 +484,10 @@
     Other **kwargs are passed down to plugins as CommandOption indirectly
     through Click context machinery.
     """
+    # configure a null root handler ONLY when used as a command line
+    # otherwise no root handler is set 
+    logging.getLogger().addHandler(logging.NullHandler())
+
     success = False
     try:
         # Validate CLI UI options dependencies and other CLI-specific inits

```

**Comment by leonardr** [comment] 2019-10-15 11:40
Hi, I got tagged in to this and I'm interested in helping to fix the problem but I'm missing some context.

The discussion that led to this decision within Beautiful Soup is in [Launchpad issue 1013862](https://bugs.launchpad.net/beautifulsoup/+bug/1013862). We decided to use `logging.warn` here because "there is nothing the client application can do about the situation, but the event should still be noted", as per [When to use logging](https://docs.python.org/3/howto/logging.html#when-to-use-logging).

From _this_ issue history, it looks like 'the situation' is that some data comes in that can't be fully converted to Unicode. Is this right? If so, then given the nature of the scancode-toolkit project I do think this falls into the realm of "nothing the client application can do", and in that case suppressing the warnings with a `NullHandler` makes sense.

**Comment by pombredanne** [comment] 2019-10-15 13:44
@leonardr thank you for chiming in! your code is delicious and mighty useful :bowing_man:  

I tagged you as I thought this might be of interest to you.

> From this issue history, it looks like 'the situation' is that some data comes in that can't be fully converted to Unicode. Is this right?

Correct. I have attached a small culprit test file extracted from busybox https://git.busybox.net/busybox/tree/shell/ash_test/ash-quoting/dollar_squote_bash2.right
[dollar_squote_bash2.right.txt](https://github.com/nexB/scancode-toolkit/files/3729539/dollar_squote_bash2.right.txt)

whatever is fed to scancode-toolkit is eventually arbitrary.

> If so, then given the nature of the scancode-toolkit project I do think this falls into the realm of "nothing the client application can do", and in that case suppressing the warnings with a NullHandler makes sense.

Exactly. What is surprising is that it started happening only recently (I should bisect to find out) and we do not define any handler for sure... yet the error or a message comes up and is different on different Python version!

**Comment by Iamshankhadeep** [comment] 2019-10-16 06:00
@pombredanne why can't I reach to [this](https://www.busybox.net/downloads/busybox-1.28.0.tar.bz2)  server?

**Comment by pombredanne** [comment] 2019-10-17 07:41
This is fixed and merged in develop... but I am keeping open as we need to have a test too for this

**Comment by pombredanne** [comment] 2019-10-22 18:04
This is now all fixed and merged in develop!
@armijnhemel  @leonardr and @Iamshankhadeep thank you ++ respectively for your report, your support and your fix! :bowing_man:

**Closed by pombredanne** 2019-10-22 18:04 UTC
Labels: GUI and outputs, fixed pending review, good first issue, minor, summaries
