### ISSUE TITLE
ImportError: No module named schematics.exceptions

### ISSUE THREAD

**Issue by aquette** [nexB/scancode-toolkit#276] opened 2016-06-28 13:39 UTC
happens for a few days now

```
Scanning files...
  [------------------------------------]  1  Scanning: .xxx
Scanning done.
Traceback (most recent call last):
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.3.7', 'console_scripts', 'scancode')()
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/utils.py", line 61, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/cli.py", line 248, in scancode
    results = scan(input, copyright, license, package, email, url, info, verbose, quiet)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/cli.py", line 315, in scan
    scan_result.update(scan_one(res, scanners))
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/cli.py", line 332, in scan_one
    scan = scan_func(input_file)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/api.py", line 177, in get_package_infos
    from packagedcode.recognize import recognize_packaged_archives
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/packagedcode/__init__.py", line 25, in <module>
    from packagedcode import models
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/packagedcode/models.py", line 32, in <module>
    from schematics.exceptions import StopValidation
ImportError: No module named schematics.exceptions
```

**Comment by pombredanne** [comment] 2016-06-28 14:36
@aquette How did you install ScanCode? It looks like you havce some combo of the devel branch (which is unstable and not yet ready to consumption) and a 1.3.7 version which was never released?

Can you tell me how this was installed? and what happens when you install the stable 1.6.0 release? 
https://github.com/nexB/scancode-toolkit/releases/tag/v1.6.0 ?

**Comment by aquette** [comment] 2016-06-28 14:47
simple "git clone https://github.com/nexB/scancode-toolkit.git" (so current master) running on a bamboo CI, reproduced on my Debian laptop.
I'll try with the 1.6.0 archive and report back

**Comment by aquette** [comment] 2016-06-28 14:55
good with the 1.6.0 archive, scanned as usual. so in between the release and some commit ~ 3 days ago (our CI started to fail around that time)

**Comment by pombredanne** [comment] 2016-06-28 15:05
`git clone https://github.com/nexB/scancode-toolkit.git` gives you the current develop branch which is the default and not a stable branch. You would need to check out the master branch instead

**Comment by pombredanne** [comment] 2016-06-28 17:00
@aquette Does this make sense?

**Comment by pombredanne** [comment] 2016-06-28 17:01
You wrote:
> so in between the release and some commit ~ 3 days ago (our CI started to fail around that time)

This is when I merged in devel the new package branch.... Now something is bugging me: even when using the devel branch things should not fail: Can you tell me which OS/version/architecture you are running?

**Comment by aquette** [comment] 2016-06-28 18:19
Indeef makes sense, and sorry for not having checked the default branch on
which I'm sitting ;)

The OS is Debian 8 Jessie on both my laptop and the CI agents.

(sent from my S3... please excuse my brevity)
Le 28 juin 2016 19:01, "Philippe Ombredanne" <notifications@github.com> a
écrit :

**Comment by pombredanne** [comment] 2016-06-28 18:59
Thanks. Not you are getting me worried that the devel branch may not work on Debian 8.... I will need to run some tests.... But you are saying that if you fetch and install this  https://github.com/nexB/scancode-toolkit/releases/tag/v1.6.3 for instance, it will not run correctly on Debian 8?

**Comment by pombredanne** [comment] 2016-06-28 19:00
On another note, if you are running scans on each commit, one thing I have been thinking about is to be run scans on the increments only.

**Comment by aquette** [comment] 2016-06-29 08:33
hi Philippe,
confirming that switching to the master branch works as expected.
The archive I've tested was scancode-toolkit-1.6.0, not 1.6.3.
I've just retried with the tag v1.6.3 and it fails.
Quickly ramping down, v1.6.2 fails too, v1.6.1 seems to work... So, issue between 1.6.1 and 1.6.2...
If you need me to run some tests on Jessie, don't hesitate to tell me ;)

**Comment by pombredanne** [comment] 2016-06-29 14:41
@aquette Thanks! If you do not mind pasting your failure log here on 1.6.3 that would be really helpful.

**Comment by aquette** [comment] 2016-06-29 14:48
sure, here we go:
`$ git checkout v1.6.3
La position précédente de HEAD était 10eea0c... New temporary unpublished version 1.6.1
HEAD est maintenant sur 2e271ba... Bump to experimental 1.6.3
$ ./scancode -f html src/ > test.html
Traceback (most recent call last):
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.3.7', 'console_scripts', 'scancode')()
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/utils.py", line 61, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/cli.py", line 248, in scancode
    results = scan(input, copyright, license, package, email, url, info, verbose, quiet)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/cli.py", line 315, in scan
    scan_result.update(scan_one(res, scanners))
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/cli.py", line 332, in scan_one
    scan = scan_func(input_file)
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/scancode/api.py", line 177, in get_package_infos
    from packagedcode.recognize import recognize_packaged_archives
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/packagedcode/__init__.py", line 25, in <module>
    from packagedcode import models
  File "/home/arno/Projects/Eaton/BIOS/Legal/scancode-toolkit/src/packagedcode/models.py", line 32, in <module>
    from schematics.exceptions import StopValidation
ImportError: No module named schematics.exceptions
`

**Comment by aquette** [comment] 2016-06-29 14:50
sure, here we go:
`$ git checkout v1.6.3
La position précédente de HEAD était 10eea0c... New temporary unpublished version 1.6.1
HEAD est maintenant sur 2e271ba... Bump to experimental 1.6.3

$ ./scancode -f html src/ > test.html
Traceback (most recent call last):
  File "/home/arno/Projects/Legal/scancode-toolkit/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.3.7', 'console_scripts', 'scancode')()
  File "/home/arno/Projects/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/arno/Projects/Legal/scancode-toolkit/src/scancode/utils.py", line 61, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/arno/Projects/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/arno/Projects/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arno/Projects/Legal/scancode-toolkit/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/arno/Projects/Legal/scancode-toolkit/src/scancode/cli.py", line 248, in scancode
    results = scan(input, copyright, license, package, email, url, info, verbose, quiet)
  File "/home/arno/Projects/Legal/scancode-toolkit/src/scancode/cli.py", line 315, in scan
    scan_result.update(scan_one(res, scanners))
  File "/home/arno/Projects/Legal/scancode-toolkit/src/scancode/cli.py", line 332, in scan_one
    scan = scan_func(input_file)
  File "/home/arno/Projects/Legal/scancode-toolkit/src/scancode/api.py", line 177, in get_package_infos
    from packagedcode.recognize import recognize_packaged_archives
  File "/home/arno/Projects/Legal/scancode-toolkit/src/packagedcode/__init__.py", line 25, in <module>
    from packagedcode import models
  File "/home/arno/Projects/Legal/scancode-toolkit/src/packagedcode/models.py", line 32, in <module>
    from schematics.exceptions import StopValidation
ImportError: No module named schematics.exceptions
`

**Comment by pombredanne** [comment] 2016-06-29 14:56
could you try this right after checking out a branch?
`./configure --clean`
then you can run scancode as usual?

**Comment by pombredanne** [comment] 2016-06-29 14:57
If this works, then you have a short term fix and I know what to do to provide a permanent fix

**Comment by aquette** [comment] 2016-06-30 07:27
salut @pombredanne
I've tried with your solution, back to origin/develop branch and doing a "./configure --clean", still fails.
Same for tag v1.6.3. Or did I misunderstand your comment?
For now, I'll stick with using master, and that's good.
I'll let you close the bug once you have the permanent fix.
Thanks again very much for scancode and your platinum support ;)
And all the best from France / Grenoble

**Comment by pombredanne** [comment] 2016-06-30 15:15
@aquette Thanks for trying. I will check all this on a VM or container as this should work alright. And this will be fixed before we push devel as a new release to master for sure!
And thank you for your nice words :+1:

**Comment by pombredanne** [comment] 2016-06-30 15:19
Btw, which Ci do you use? I am curious of this because I want to document examples of integration of ScanCode in various CI for #254 and #210 ....

**Comment by aquette** [comment] 2016-07-01 06:51
hi @pombredanne 
glad to hear that everything will get fixed in time.
don't hesitate to call me for testing, can be easier.
As for the CI, the main one is Atlassian Bamboo, but we also have Jenkins running as a 2ndary one.
For now, it's ran once a day (not upon every commit) on a bunch of repos. and then results are integrated into a homebrew dashboard.
VCS integration is not optimal with Bamboo. Would be great to have a module that takes the list of project(s) to monitor, and have post-commit hooks to get a smooth integration.
I'm running scancode in dual mode: once for simple html output, and a 2nd time for JSON output, which is then parsed by a Python script to check the (C) and license for all files according to some defined conf.
I'll contribute this script, probably around the end of the year, after some improvements. Can help scancode community hopefully...

**Comment by pombredanne** [comment] 2016-08-30 06:34
@aquette would you mind trying the latest `develop` (and ensure you run a `./configure --clean` ) ?
The problem should not exist and I really could not find a way to reproduce. Thanks!

**Comment by pombredanne** [comment] 2016-08-30 06:36
You wrote: 
> which is then parsed by a Python script to check the (C) and license for all files according to some defined conf. I'll contribute this script, probably around the end of the year, after some improvements. Can help scancode community hopefully...

very nice! .... the sooner you can eventually contribute this the better: eventually the JSON spitted by scancode is likely to go through a major transformation quite soon!

**Comment by pombredanne** [comment] 2016-11-30 14:24
@aquette anything left to do here?

**Comment by aquette** [comment] 2016-12-01 11:11
Hi @pombredanne 
our CI plan is still running on scancode master and everything seems fine :)

If you want another test run on the *develop* branch, please let me now.
otherwise, this ticket can be closed if everything is in master already...

As for the python script I've mentioned, I've still that contribution in mind, but that will have to wait a bit more since we're in the release process of the [42ITy](http://42ity.org) project, that we run scancode against...

**Comment by pombredanne** [comment] 2016-12-01 11:32
@aquette Thank you for the feedback... 42ITy looks intriguing so keep me posted for sure!. In the meantime I will close this ticket for now since all is good for you..

FWIW, the latest and greatest code in develop as several significant improvements that you are likely to benefit from. You can wait alright for the 2.0 release in master though.

Some notable new and improved bits:
- detection of packaged code (such as NPMs, Pypi, Gems, Jars, etc)
- a better and faster license detection engine
- support for scanning on multiple processes for speed
- reduce memory usage
- and many more goodies...

**Closed by pombredanne** 2016-12-01 11:32 UTC

**Comment by aquette** [comment] 2016-12-06 10:12
Hi @pombredanne

Just a final confirmation before closing the ticket.
I've made some more tests today, on both the master and develop branch.
For both, I did the git checkout then called "./configure --clean && ./configure" then ran a quick test.

Everything worked as expected.
Thanks and cheers

**Comment by pombredanne** [comment] 2016-12-06 10:40
@aquette Thank you ++ for taking the time to retest this!
I am trying to keep the develop branch stable and we are about to cut a v2.0 release soon.
In general as long as the CI builds are green on develop (as you can see with the CI badges at the top of of the README ) then develop is good to go.

Otherwise, master is where we cut stable releases and is ALWAYS green, all tests passing.
