### ISSUE TITLE
The tool does not scan hidden directory

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#881] opened 2018-01-03 23:14 UTC
I have the following hidden directory which scancode ignore scan on it: `/devel/project/.repo/` 
I believe the tool should not skip even it's a hidden directory/file.

**Comment by pombredanne** [comment] 2018-01-18 07:17
@chinyeungli Thanks you for this. The `.repo` dirs are explicitly excluded as part of the CVS standard ignores. They should not and this is a bug.

**Comment by pombredanne** [comment] 2018-02-07 16:53
This is fixed in develop now. Thank you for the report!
If you can review that would be great!

**Comment by pombredanne** [comment] 2018-03-02 01:52
Closing

**Comment by sschuberth** [comment] 2018-03-23 14:32
@pombredanne, it was me adding `.repo` to the list of VCS ignores, because that's a VCS directory as used by [the git-repo tool](https://source.android.com/setup/using-repo). So skipping it was intentional and we just ran into the regression that `.repo` contents are now scanned again.

@chinyeungli, is the `.repo` directory a git-repo directory in your case?

Can we somehow make the check more strict and only ignore `.repo` directories e.g. only if they contain a  `manifest.xml` file?

**Comment by pombredanne** [comment] 2018-03-23 16:19
@sschuberth

**Comment by pombredanne** [comment] 2018-03-23 16:24
@sschuberth 

re: So skipping it was intentional and we just ran into the regression that .repo contents are now scanned again.

We surely can do this. To get it right this time, I wonder what doc/spec on the repo tool we can get. And I think that the use case of @chinyeungli and your use case may conflict?
I am under the impression that:

- @chinyeungli wants these `.repo` directories scanned because they contains git clones of dependencies

- you do not want these `.repo` directories scanned because they contains git clones of dependencies

FWIW I think that the common and significant usage of the `repo` tool are  Android, possibly Chromium and Yocto.

**Comment by sschuberth** [comment] 2018-03-24 06:53
> you do not want these .repo directories scanned because they contains git clones of dependencies

Not quite. In the git-repo case, the `.repo` directory contains what would usually go into the individual `.git` directories (plus some additional meta-data). I.e. it does not contain the working tree files, those are one level above, it only contains the VCS meta-data (which you really do not want to scan).

**Comment by pombredanne** [comment] 2018-03-24 16:43
@sschuberth ok, so is there any known case where a .repo contains actual full git working directories?
I think that's where the disconnect is.

**Comment by sschuberth** [comment] 2018-03-24 16:45
No, I don't know such a (real-world) case. Which is why I was asking about @chinyeungli's case.

**Comment by chinyeungli** [comment] 2018-03-25 22:06
@pombredanne @sschuberth I checked back the project that I'm working and confirmed 99% of the files under the `.repo` is metadata, config etc..

However, there are still some python files in it. For instance,
```
/devel/project/.repo/repo/color.py
/devel/project/.repo/repo/command.py
/devel/project/.repo/repo/editor.py
/devel/project/.repo/repo/error.py
/devel/project/.repo/repo/git_command.py
/devel/project/.repo/repo/git_config.py
/devel/project/.repo/repo/git_refs.py
/devel/project/.repo/repo/gitc_utils.py
/devel/project/.repo/repo/manifest_xml.py
/devel/project/.repo/repo/pager.py
```

and the above scripts only exist under the `.repo` , I am not very familiar with the git, perhaps the above are generated code? If that is the case, I think we can safely ignore the `.repo`.

My initial concern was if it's an info scan (--info option), it should include everything.

**Comment by sschuberth** [comment] 2018-03-26 07:07
@chinyeungli Those Python files in `.repo/repo` are the source code to the git-repo tool itself. Upon running `repo init`, git-repo bootstraps itself to the `.repo` directory, so it can be updated independently of the globally installed version. So this source code is not part of the working tree, and you don't want to scan it as it's just the source code of a VCS tool you're using, just like you do not want to scan the source code of Git just because you're using a Git working tree.

**Comment by chinyeungli** [comment] 2018-03-26 07:15
@sschuberth Thanks for the information.
I agree we don't want/need to scan these if these are not "project-related" code. @pombredanne any input?

**Closed** 2018-03-26 15:29 UTC
Labels: bug, core and api
