### ISSUE TITLE
Scancode tool kit 2.9.2 not running on Ubuntu 14.04

### ISSUE THREAD

**Issue by Drive2018** [nexB/scancode-toolkit#1197] opened 2018-09-30 19:38 UTC
Hi Phillippe,

Thanks for the immediate response.  Sorry for the confusion.

1. We have downloaded  Scancode tool kit 2.9.2.

2.We have installed the python from the commands enlisted here from the below url..

 

 

3.   From this url I have downloaded the bInaries for Scancode tool kit 2.9.2 tar.gz2 file.

            https://github.com/nexB/scancode-toolkit/releases/tag/v2.9.2 ?

![capture2](https://user-images.githubusercontent.com/35925093/46261804-adb02f00-c4f0-11e8-8483-6aa20dd43378.png)

![capture1](https://user-images.githubusercontent.com/35925093/46261792-83f70800-c4f0-11e8-96ac-0c7fe32acf5c.PNG)

Please let us know if still needs any wrong in settings to be corrected.

Cordially 
Sirisha.

**Comment by pombredanne** [comment] 2018-09-30 20:48
@Drive2018 Thanks for this report. It should work.
So can you extract the https://github.com/nexB/scancode-toolkit/releases/download/v2.9.2/scancode-toolkit-2.9.2.tar.bz2 tarball in another fresh and empty new directory then open a shell in this directory run this command and then send me the results?
`./configure`

Also what are the specification of your machine BTW (CPU, RAM, disk) ?

**Comment by Drive2018** [comment] 2018-10-01 08:16
Its a T2.micro instance in AWS.  8GB volume. Yes I was able to un tar the file and pls find the below image for after running ./configure command.
![capture3](https://user-images.githubusercontent.com/35925093/46277315-ad4c7e00-c55a-11e8-9171-63ddaadb1069.PNG)

**Comment by pombredanne** [comment] 2018-10-01 12:20
Ok, could you run this instead:
`./configure --clean` and then `./configure etc/conf` ?
This is my test setup for Ubuntu 14.04:
```
$ uname -a
Linux COMPUTER 4.4.0-135-generic #161~14.04.1-Ubuntu SMP Tue Aug 28 11:17:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
$ python -V
Python 2.7.6
```
And I can this sequence of commands without trouble:
```
mkdir testscan
cd testscan/
wget https://github.com/nexB/scancode-toolkit/releases/download/v2.9.2/scancode-toolkit-2.9.2.tar.bz2
tar -xf scancode-toolkit-2.9.2.tar.bz2 
cd scancode-toolkit-2.9.2/
./scancode --copyright --license --json-pp - samples/
```
Note that on the first run (only then), an index is built and is can take a minute to create.

**Comment by pombredanne** [comment] 2018-10-09 18:35
@Drive2018 any update? is this working OK now?

**Comment by pombredanne** [comment] 2018-10-12 16:04
@Drive2018 ping?

**Comment by pombredanne** [comment] 2018-10-16 19:50
@Drive2018 I am closing this for now since you have not replied. Feel free to reopen if this is still an issue, but I was not able to reproduce this on a vanilla Ubuntu 14.x 
It could be something with AWS only?

**Closed by pombredanne** 2018-10-16 19:50 UTC
Labels: bug, installation and packaging
