### ISSUE TITLE
Incomplete copyright detected

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2420] opened 2021-03-02 21:20 UTC
`Copyright (c) 2009, 2018 Robert Bosch GmbH and its subsidiaries. ` is detected only as `"Copyright (c) 2009, 2018 Robert Bosch GmbH"`

**Comment by s4-2** [comment] 2021-03-12 12:39
Hello @pombredanne , I think there is a typo in this issue topic.

**Comment by akugarg** [comment] 2021-03-25 19:28
Hey! @pombredanne I want to work on this issue Can you please explain a little bit more on this? I couldn't find a license corresponding to this .

**Comment by Divyansh2512** [comment] 2021-03-25 19:47
@akugarg

> `Copyright (c) 2009, 2018 Robert Bosch GmbH and its subsidiaries. `

Try running a copyright scan against this you'll see that `and its subsidiaries` would be missing. This is majorly because of the copyrights detection technique that scancode follows and can be seen in scancode-toolkit/src/cluecode/copyrights.py

I'll be more than happy to help if you encounter any problem because I myself spent an awful lot of time working on this issue but wasn't able to figure out a way for resolving this.

**Comment by akugarg** [comment] 2021-03-25 19:51
@Divyansh2512 Thanks :)
Will try to look into it.

**Comment by pombredanne** [comment] 2021-03-25 23:47
There are two environment variables that can help to debug this: SCANCODE_DEBUG_COPYRIGHT and SCANCODE_DEBUG_COPYRIGHT_DEEP
See https://github.com/nexB/scancode-toolkit/blob/59851db8028bdd3e2a011d52ffdba2b3f057ec72/src/cluecode/copyrights.py#L22
The first one provides tokenization details and parse tree and the second one provides which "grammar" rules are fired and their results.

Use it this way:
```
$ echo "Copyright (c) 2009, 2018 Robert Bosch GmbH and its subsidiaries."  > cp.txt
$ SCANCODE_DEBUG_COPYRIGHT=yes scancode --copyright --json-pp - cp.tx
 or
$ SCANCODE_DEBUG_COPYRIGHT_DEEP=yes scancode --copyright --json-pp - cp.tx
```

`$ SCANCODE_DEBUG_COPYRIGHT=yes scancode --copyright --json-pp - cp.tx` yields these debug outputs: 
```
DEBUG:cluecode.copyrights:CopyrightDetector:tagged_text: [('Copyright', 'COPY'), ('(c)', 'COPY'), ('2009,', 'YR'), ('2018', 'YR'), ('Robert', 'NNP'), ('Bosch', 'NNP'), ('GmbH', 'COMP'), ('and', 'CC'), ('its', 'NN'), ('subsidiaries.', 'NN')]
DEBUG:cluecode.copyrights:CopyrightDetector:parse tree: (S
  (COPYRIGHT
    Copyright/COPY
    (c)/COPY
    (NAME-YEAR
      (NAME-YEAR
        (NAME-YEAR
          (YR-RANGE (YR-RANGE 2009,/YR 2018/YR))
          (COMPANY Robert/NNP Bosch/NNP GmbH/COMP)))))
  and/CC
  its/NN
  subsidiaries./NN)
DEBUG:cluecode.copyrights:detect:node_text: Copyright (c) 2009, 2018 Robert Bosch GmbH
DEBUG:cluecode.copyrights:CopyrightDetector:Copyright tree node: (COPYRIGHT
  Copyright/COPY
  (c)/COPY
  (NAME-YEAR
    (NAME-YEAR
      (NAME-YEAR
        (YR-RANGE (YR-RANGE 2009,/YR 2018/YR))
        (COMPANY Robert/NNP Bosch/NNP GmbH/COMP)))))
DEBUG:cluecode.copyrights:CopyrightDetector: detected copyrights: Copyright (c) 2009, 2018 Robert Bosch GmbH 1 1
DEBUG:cluecode.copyrights:CopyrightDetector: detected holders: Robert Bosch GmbH 1 1
```


where you see that `subsidiaries.` is tagged as an NN aka. Plain NOUN and its not recognized as something special such as `COMP` tag aka. COMPANY.
The likely first step may be to ensure that an optional trailing period is correctly detected with a subsidiary|ies to mots likely cure fix this in https://github.com/nexB/scancode-toolkit/blob/59851db8028bdd3e2a011d52ffdba2b3f057ec72/src/cluecode/copyrights.py#L1176

**Comment by Divyansh2512** [comment] 2021-03-26 08:21
@pombredanne Thank you for such a detailed explanation. I'll get back to you on this.

**Comment by Divyansh2512** [comment] 2021-03-26 19:02
It seems like the problem is with the way we are generating the tokens.
> [('Copyright', 'COPY'), ('(c)', 'COPY'), ('2009,', 'YR'), ('2018', 'YR'), ('Robert', 'NNP'), ('Bosch', 'NNP'), ('GmbH', 'COMP'), ('and', 'CC'), ('its', 'NN'), ('subsidiaries.', 'NN')]

If you see closely we are generating `subsidiaries.`, now due to this additional `.` we are unable to match the regex pattern that is why it is getting tagged as `'NN'` instead of `'COMP'`.

@pombredanne @majurg Any thoughts on how to fix this?

**Comment by pombredanne** [comment] 2021-03-26 19:12
>  Any thoughts on how to fix this?

You need to update the regex for subsidiaries -> COMP to optional accept a trailing period.

**Comment by Divyansh2512** [comment] 2021-03-26 19:17
Well that would fix this particular issue but what about rest, like if we have `Copyright (c) 2009, 2018 Robert Bosch GmbH and foundation.`

**Comment by Divyansh2512** [comment] 2021-03-26 21:18
Is there a need to write test case for this?

**Closed as completed** 2021-03-31 21:55 UTC
Labels: bug, copyright scan
