### ISSUE TITLE
  license: Apache Software will be found as "unknown"

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1606] opened 2019-06-18 14:13 UTC
### Description
When parsing meta.yaml file from Conda, the line:

Apache Software

will be detected as

unknown.

The license in yaml file is at: https://github.com/nexB/scancode-toolkit/blob/1447-conda-support/tests/packagedcode/data/conda/meta.yaml#L42

The detected result is at: https://github.com/nexB/scancode-toolkit/blob/1447-conda-support/tests/packagedcode/data/conda/meta.yaml.expected.json#L24

**Comment by rajashreetutgirl** [comment] 2019-07-19 05:55
innersvg.js  js library has Apache 2.0 license. But Scan code is detecting it has unknown, This seems to be not reliable being license scan as the major feature.

Please look into it. Thanks in advance.

**Comment by rajashreetutgirl** [comment] 2019-07-19 11:30
Hi,
Below is the license statement, for which the Scancode-toolkit 3.0.2 detecting as "unknown"
/**
 * innerHTML property for SVGElement
 * Copyright(c) 2010, Jeff Schiller
 *
 * Licensed under the Apache License, Version 2
 *
 * Minor modifications by Chris Price to only polyfill when required.
 */

So we have high alert for unknown licenses. It is unnecessarily grabs attention.
Any help will be more useful.

Thanks in Advance

**Comment by rajashreetutgirl** [comment] 2019-07-25 06:50
Hi,

When can I have this change in official release? For time being how to use this fix?

Thanks
Rajashree

**Comment by pombredanne** [comment] 2019-07-25 14:20
@rajashreetutgirl You are welcomed and it would be great if you can test this in this branch/PR: https://github.com/nexB/scancode-toolkit/compare/license-updates-07-12
Process-wise, once merged this will be in the next release.
The next release is in the works and we should have a release candidate soon...

**Comment by rajashreetutgirl** [comment] 2019-07-26 06:43
@pombredanne 
Thanks a lot!! I cloned this branch license-updates-07-12. It is detecting apache 2.0 for the statement Licensed under the Apache License, Version 2.

"matched_rule": {
            "identifier": "apache-2.0_291.RULE",
            "license_expression": "apache-2.0",
            "licenses": [
              "apache-2.0"
            ],

Does this branch has all features so that I can use it till the next release?

Thanks
Rajashree

**Comment by rajashreetutgirl** [comment] 2019-07-26 10:59
@pombredanne 

I got one exceptional scenario Unknown and Apache 2.0 both getting detected. Could you please look into it.

File: vis.min.js
/**
 * vis.js
 * https://github.com/almende/vis
 *
 * A dynamic, browser-based visualization library.
 *
 * @version 4.20.1-SNAPSHOT
 * @date    2017-10-12
 *
 * @license
 * Copyright (C) 2011-2017 Almende B.V, http://almende.com
 *
 * Vis.js is dual licensed under both
 *
 * * The Apache 2.0 License
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * and
 *
 * * The MIT License
 *   http://opensource.org/licenses/MIT
 *
 * Vis.js may be distributed under either license.
 */

licenses list from result json:
"licenses": [
        {
          "key": "apache-2.0",
          "score": 44.44,
          "name": "Apache License 2.0",
          "short_name": "Apache 2.0",
          "category": "Permissive",
          "is_exception": false,
          "owner": "Apache Software Foundation",
          "homepage_url": "http://www.apache.org/licenses/",
          "text_url": "http://www.apache.org/licenses/LICENSE-2.0",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:apache-2.0",
          "spdx_license_key": "Apache-2.0",
          "spdx_url": "https://spdx.org/licenses/Apache-2.0",
          "start_line": 10,
          "end_line": 21,
          "matched_rule": {
            "identifier": "apache-2.0_or_mit7.RULE",
            "license_expression": "apache-2.0 OR mit",
            "licenses": [
              "apache-2.0",
              "mit"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 45,
            "matched_length": 20,
            "match_coverage": 44.44,
            "rule_relevance": 100
          }
        },
        {
          "key": "mit",
          "score": 44.44,
          "name": "MIT License",
          "short_name": "MIT License",
          "category": "Permissive",
          "is_exception": false,
          "owner": "MIT",
          "homepage_url": "http://opensource.org/licenses/mit-license.php",
          "text_url": "http://opensource.org/licenses/mit-license.php",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:mit",
          "spdx_license_key": "MIT",
          "spdx_url": "https://spdx.org/licenses/MIT",
          "start_line": 10,
          "end_line": 21,
          "matched_rule": {
            "identifier": "apache-2.0_or_mit7.RULE",
            "license_expression": "apache-2.0 OR mit",
            "licenses": [
              "apache-2.0",
              "mit"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 45,
            "matched_length": 20,
            "match_coverage": 44.44,
            "rule_relevance": 100
          }
        },
        {
          "key": "unknown",
          "score": 100.0,
          "name": "Unknown license detected but not recognized",
          "short_name": "unknown",
          "category": "Unstated License",
          "is_exception": false,
          "owner": "Unspecified",
          "homepage_url": null,
          "text_url": "",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:unknown",
          "spdx_license_key": null,
          "spdx_url": "",
          "start_line": 13,
          "end_line": 13,
          "matched_rule": {
            "identifier": "unknown_30.RULE",
            "license_expression": "unknown",
            "licenses": [
              "unknown"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "2-aho",
            "rule_length": 3,
            "matched_length": 3,
            "match_coverage": 100.0,
            "rule_relevance": 100.0
          }
        },
        {
          "key": "unknown",
          "score": 11.0,
          "name": "Unknown license detected but not recognized",
          "short_name": "unknown",
          "category": "Unstated License",
          "is_exception": false,
          "owner": "Unspecified",
          "homepage_url": null,
          "text_url": "",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:unknown",
          "spdx_license_key": null,
          "spdx_url": "",
          "start_line": 23,
          "end_line": 23,
          "matched_rule": {
            "identifier": "unknown_53.RULE",
            "license_expression": "unknown",
            "licenses": [
              "unknown"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": true,
            "is_license_tag": false,
            "matcher": "2-aho",
            "rule_length": 2,
            "matched_length": 2,
            "match_coverage": 100.0,
            "rule_relevance": 11
          }
        }
      ]

**Comment by pombredanne** [comment] 2019-07-26 16:41
@rajashreetutgirl thanks... Let me move this to another brand new ticket https://github.com/nexB/scancode-toolkit/issues/1666 such that this is easier to track. We are trying to get one problem means one issue

**Comment by pombredanne** [comment] 2019-07-26 16:43
This is otherwise confirmed as fixed.... This is still in the branch but I am closing now to avoid confusion. @linexb @rajashreetutgirl Thank you ++

**Closed by pombredanne** 2019-07-26 16:43 UTC
Labels: bug, license scan
