### ISSUE TITLE
Error reported by scancode in few files while scanning.

### ISSUE THREAD

**Issue by jarnugirdhar** [nexB/scancode-toolkit#655] opened 2017-06-23 16:54 UTC
While going through a repository on git [stackoverflow copy-paste](https://github.com/eggheadio-github/stack-overflow-copy-paste), I thought I should try scancode on that so while doing that following error occurred on few files.

![screenshot from 2017-06-23 15-45-42](https://user-images.githubusercontent.com/28496978/27492032-4a9bb890-5862-11e7-9658-7841a8f34abd.png)

Files attached:

[Erroraneous files.tar.gz](https://github.com/nexB/scancode-toolkit/files/1098474/Erroraneous.files.tar.gz)

**Comment by pombredanne** [comment] 2017-06-28 15:22
Thanks. This is a pesky one that seems to be related to some very long tokenizing time for these generated JS parser files. I am on it!

**Comment by pombredanne** [comment] 2017-06-28 15:28
Note that this is only a timeout so it is mostly harmless.

**Comment by pombredanne** [comment] 2017-06-29 11:32
So the root cause of the timeout of scanning these files is this regex: https://github.com/nexB/scancode-toolkit/blob/cb99c8b60349494d3d52eeba406342a89f341684/src/licensedcode/tokenize.py#L73 .... which chokes on the data that's at the bottom of the parser.js .... this is likely getting in some corner case. This regex is pretty bad anyway and that's a great deep you found there!

**Comment by pombredanne** [comment] 2017-06-29 17:32
@jarnugirdhar This is fixed in develop. Thanks ++

**Comment by pombredanne** [comment] 2017-07-03 16:30
Fixed and released in 2.0.1. Thanks!

**Closed by pombredanne** 2017-07-03 16:30 UTC
Labels: fixed pending review, license scan
