### ISSUE TITLE
Path with space is replaced by `+` 

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#545] opened 2017-03-07 07:59 UTC
For instance,
If my project is located at `code/Source Code Package/test/`, the scan result will have the following as path:
```
"path":"code/Source+Code+Package/test/"
```

I don't think this is correct to replace space by `+`

**Comment by pombredanne** [comment] 2017-03-07 08:19
@chinyeungli You are right! I think this is a dupe of #542 ... Let's track there.

**Closed** 2017-03-07 08:20 UTC
Labels: duplicate
