### ISSUE TITLE
Nugets not reported as packages (2.9.2)

### ISSUE THREAD

**Issue by tomeks666** [nexB/scancode-toolkit#1088] opened 2018-06-01 10:16 UTC
I used this:
extractcode c:\src\solution\main
then
scancode -l -p -c -i -n 2 --verbose c:\src\solution\main --json-pp solution.json

It took 8 hours to scan the folder. Unfortunately only zip,cab ans msi are detected as packages. Nugets are not and they are the main priority.

Is there something needed to be done like loading some additional module?

**Comment by pombredanne** [comment] 2018-06-01 14:41
@tomeks666 thank you for the report. Which was not detected?
A Nuget manifest will be detected if this is a "*.nuspec" file. This can surely be improved.
Is there some details on your code that you can share such to have a reproducible test case?

**Comment by tomeks666** [comment] 2018-06-01 15:04
I just ran scancode directly on a single package folder. Nuspec file is there.
scancode -l -p -c -i -n 2 --verbose  "C:\src\MeLEDES\main\packages\Castle.Core.4.2.1" --json-pp castlenuget.json
The result is attached. 

[castlereport.zip](https://github.com/nexB/scancode-toolkit/files/2063132/castlereport.zip)

**Comment by pombredanne** [comment] 2018-06-01 15:22
thanks!

**Comment by pombredanne** [comment] 2018-06-04 09:46
@tomeks666 do you mind testing again with the latest `develop` branch? this should be fixed.

On another note, I find a scan that runs for 8 hours a tad suspicious:
- is this a very large codebase? or a slow machine? or both?
- was there any timeout errors on some files, and if yes, that would be great if you can point me to these files assuming they would be public/open source or provide some indication of their type and size.

Thank you.

**Comment by tomeks666** [comment] 2018-06-04 10:04
The number of files is large like 30000+. I did not find any category I could exclude to make significant cut in this number. The file inventory alone takes many minutes. During scanning it makes around 1 file per second. The machine is not very fast - a laptop with i5-4300U 1.9/2.5 GHz with an SSD drive. The disk has full encryption and there is some corporate DLP/security services. But they do not seem to have a visible impact on other operations like solution rebuild. dir /s > dir.txt takes only 13 seconds. So maybe there is some other reason e.g. something wrong with python installation. Even when using --from-json option the file inventory takes minutes. On other hand importing to SQLite database in AboutCode-Manager.exe is normal - less that one minute.

**Comment by pombredanne** [comment] 2018-08-06 09:48
@tomeks666 sorry for the late reply. Some comments:
- i5-4300U is only a dual core processor that is OK, but not super fast. In any case using the --process/-n option to run on multiple threads should help. 1 file per second is a tad slow for sure. You could also use a short `--timeout=5` of 5 seconds such that slow/large file will timeout and not slow down the whole scan too much 
- the whole disk encryption if this is an SSD that handles it in hardware should be OK. If this is software-based, and since scancode creates a lot of small temporary files, this could be a serious drag on performances

- > Even when using --from-json option the file inventory takes minutes. 

If you have enough RAM, you could try to disable disk caching entirely with ` --max-in-memory=0` 

The other thing that could things down would be if your installation or temp file are on network drive of sorts?

**Comment by pombredanne** [comment] 2018-10-31 16:13
The nuget detection issue is fixed and is available in develop and released. I am closing ... feel free to reopen or open a new ticket if you have further  problem and thank you for the report!

**Closed by pombredanne** 2018-10-31 16:13 UTC
Labels: package scan
